git clone --depth 1 https://github.com/Boti2-0/product-identifier-products.git /data/ucov/repro/jsoup/Clients/Boti2-0/product-identifier-products
git clone --depth 1 https://github.com/Alex-HCF/drg.git /data/ucov/repro/jsoup/Clients/Alex-HCF/drg
git clone --depth 1 https://github.com/hoangon1z/sanbo1.git /data/ucov/repro/jsoup/Clients/hoangon1z/sanbo1
git clone --depth 1 https://github.com/shuanglangdeliubei/Timo.git /data/ucov/repro/jsoup/Clients/shuanglangdeliubei/Timo
git clone --depth 1 https://github.com/CrackerCat/YongyouNC-Unserialize-Tools.git /data/ucov/repro/jsoup/Clients/CrackerCat/YongyouNC-Unserialize-Tools
git clone --depth 1 https://github.com/DenisGIT1/Unic.git /data/ucov/repro/jsoup/Clients/DenisGIT1/Unic
git clone --depth 1 https://github.com/Kirill112002/Software.git /data/ucov/repro/jsoup/Clients/Kirill112002/Software
git clone --depth 1 https://github.com/syllogism1123/webcrawler_XinDu.git /data/ucov/repro/jsoup/Clients/syllogism1123/webcrawler_XinDu
git clone --depth 1 https://github.com/yida-lxw/spider4j.git /data/ucov/repro/jsoup/Clients/yida-lxw/spider4j
git clone --depth 1 https://github.com/star-table/lesscode-form.git /data/ucov/repro/jsoup/Clients/star-table/lesscode-form
git clone --depth 1 https://github.com/felippepg/simpleCrawler.git /data/ucov/repro/jsoup/Clients/felippepg/simpleCrawler
git clone --depth 1 https://github.com/automationbytes/TestNG_POM_Aug_2023.git /data/ucov/repro/jsoup/Clients/automationbytes/TestNG_POM_Aug_2023
git clone --depth 1 https://github.com/srival1/internetBankingV2.git /data/ucov/repro/jsoup/Clients/srival1/internetBankingV2
git clone --depth 1 https://github.com/seomar2022/caesar.git /data/ucov/repro/jsoup/Clients/seomar2022/caesar
git clone --depth 1 https://github.com/Callian/devsecops-gitlab-java-vulnerable-application.git /data/ucov/repro/jsoup/Clients/Callian/devsecops-gitlab-java-vulnerable-application
git clone --depth 1 https://github.com/AleksM86/SearchEngine.git /data/ucov/repro/jsoup/Clients/AleksM86/SearchEngine
git clone --depth 1 https://github.com/hxc236/SE-practical-traing.git /data/ucov/repro/jsoup/Clients/hxc236/SE-practical-traing
git clone --depth 1 https://github.com/sqlidan/CCLI.git /data/ucov/repro/jsoup/Clients/sqlidan/CCLI
git clone --depth 1 https://github.com/PastorGL/datacooker-etl.git /data/ucov/repro/jsoup/Clients/PastorGL/datacooker-etl
git clone --depth 1 https://github.com/Super-nerd-ctrl/yusou-backend.git /data/ucov/repro/jsoup/Clients/Super-nerd-ctrl/yusou-backend
git clone --depth 1 https://github.com/favsarfavsar/ctech.git /data/ucov/repro/jsoup/Clients/favsarfavsar/ctech
git clone --depth 1 https://github.com/klintron-test-org/web-goat-3.git /data/ucov/repro/jsoup/Clients/klintron-test-org/web-goat-3
git clone --depth 1 https://github.com/HighlandProger/LivingWageBot.git /data/ucov/repro/jsoup/Clients/HighlandProger/LivingWageBot
git clone --depth 1 https://github.com/Datasiast/ghas-bootcamp-webgoat.git /data/ucov/repro/jsoup/Clients/Datasiast/ghas-bootcamp-webgoat
git clone --depth 1 https://github.com/laxmangandi369/Auth0LoginExample.git /data/ucov/repro/jsoup/Clients/laxmangandi369/Auth0LoginExample
git clone --depth 1 https://github.com/d4span/freemind.git /data/ucov/repro/jsoup/Clients/d4span/freemind
git clone --depth 1 https://github.com/rowan-tich/busybadgerscraper.git /data/ucov/repro/jsoup/Clients/rowan-tich/busybadgerscraper
git clone --depth 1 https://github.com/leyla1991/job4j_grabber.git /data/ucov/repro/jsoup/Clients/leyla1991/job4j_grabber
git clone --depth 1 https://github.com/kgobemoses/farming.git /data/ucov/repro/jsoup/Clients/kgobemoses/farming
git clone --depth 1 https://github.com/khurshidbek-bakhromjonov/EPAM-training.git /data/ucov/repro/jsoup/Clients/khurshidbek-bakhromjonov/EPAM-training
git clone --depth 1 https://github.com/BenHamoudaHichem/TnCities.git /data/ucov/repro/jsoup/Clients/BenHamoudaHichem/TnCities
git clone --depth 1 https://github.com/kingbaibai/myleadnews.git /data/ucov/repro/jsoup/Clients/kingbaibai/myleadnews
git clone --depth 1 https://github.com/ircecam/module_12.git /data/ucov/repro/jsoup/Clients/ircecam/module_12
git clone --depth 1 https://github.com/bengmend/WebGoat.git /data/ucov/repro/jsoup/Clients/bengmend/WebGoat
git clone --depth 1 https://github.com/HubSpot/maven-dependency-plugin.git /data/ucov/repro/jsoup/Clients/HubSpot/maven-dependency-plugin
git clone --depth 1 https://github.com/Alexandre-COURBOIS/NFS_LAGOSANTO_ALGORITHME.git /data/ucov/repro/jsoup/Clients/Alexandre-COURBOIS/NFS_LAGOSANTO_ALGORITHME
git clone --depth 1 https://github.com/monaztic/youtube-local-compare.git /data/ucov/repro/jsoup/Clients/monaztic/youtube-local-compare
git clone --depth 1 https://github.com/SouljaBoy-tell-em/NetCracker.git /data/ucov/repro/jsoup/Clients/SouljaBoy-tell-em/NetCracker
git clone --depth 1 https://github.com/chkal/junit-xml-transform-plugin.git /data/ucov/repro/jsoup/Clients/chkal/junit-xml-transform-plugin
git clone --depth 1 https://github.com/windseedgee/EMAN.git /data/ucov/repro/jsoup/Clients/windseedgee/EMAN
git clone --depth 1 https://github.com/kd-praveen/web-scrapping-springboot.git /data/ucov/repro/jsoup/Clients/kd-praveen/web-scrapping-springboot
git clone --depth 1 https://github.com/hqgaofeng/cnceact.git /data/ucov/repro/jsoup/Clients/hqgaofeng/cnceact
git clone --depth 1 https://github.com/KevinGaoZF/spring-boot-demo.git /data/ucov/repro/jsoup/Clients/KevinGaoZF/spring-boot-demo
git clone --depth 1 https://github.com/BesyadaV/WebGoat.git /data/ucov/repro/jsoup/Clients/BesyadaV/WebGoat
git clone --depth 1 https://github.com/rostislavYurievich/java_labs.git /data/ucov/repro/jsoup/Clients/rostislavYurievich/java_labs
git clone --depth 1 https://github.com/vishnukolluri/RewardCalculator.git /data/ucov/repro/jsoup/Clients/vishnukolluri/RewardCalculator
git clone --depth 1 https://github.com/fawMetersphere/metersphere.git /data/ucov/repro/jsoup/Clients/fawMetersphere/metersphere
git clone --depth 1 https://github.com/charlielduong/charliewebapps.git /data/ucov/repro/jsoup/Clients/charlielduong/charliewebapps
git clone --depth 1 https://github.com/Spartak101/java_basics.git /data/ucov/repro/jsoup/Clients/Spartak101/java_basics
git clone --depth 1 https://github.com/BussanQ/MySpringboot-KuangJia.git /data/ucov/repro/jsoup/Clients/BussanQ/MySpringboot-KuangJia
git clone --depth 1 https://github.com/chanhyub/Gimhae-Swim.git /data/ucov/repro/jsoup/Clients/chanhyub/Gimhae-Swim
git clone --depth 1 https://github.com/yujinn001/Spring.git /data/ucov/repro/jsoup/Clients/yujinn001/Spring
git clone --depth 1 https://github.com/HL-eng/git-demo.git /data/ucov/repro/jsoup/Clients/HL-eng/git-demo
git clone --depth 1 https://github.com/Baeyonghyeon/NoticeBoard.git /data/ucov/repro/jsoup/Clients/Baeyonghyeon/NoticeBoard
git clone --depth 1 https://github.com/rajiselva05/MovieBooking.git /data/ucov/repro/jsoup/Clients/rajiselva05/MovieBooking
git clone --depth 1 https://github.com/ZakharovNerd/metadata-extractor-java.git /data/ucov/repro/jsoup/Clients/ZakharovNerd/metadata-extractor-java
git clone --depth 1 https://github.com/JessySnow/zhizhuzi.git /data/ucov/repro/jsoup/Clients/JessySnow/zhizhuzi
git clone --depth 1 https://github.com/hanseongv/DCardGame.git /data/ucov/repro/jsoup/Clients/hanseongv/DCardGame
git clone --depth 1 https://github.com/ppppps5/noticeForProfessional.git /data/ucov/repro/jsoup/Clients/ppppps5/noticeForProfessional
git clone --depth 1 https://github.com/StanislavBozhko/web-parsing-indexing-search.git /data/ucov/repro/jsoup/Clients/StanislavBozhko/web-parsing-indexing-search
git clone --depth 1 https://github.com/2278686667/spider-flow.git /data/ucov/repro/jsoup/Clients/2278686667/spider-flow
git clone --depth 1 https://github.com/lztXiaoG/12011417lab3.git /data/ucov/repro/jsoup/Clients/lztXiaoG/12011417lab3
git clone --depth 1 https://github.com/yexuejc/solo.git /data/ucov/repro/jsoup/Clients/yexuejc/solo
git clone --depth 1 https://github.com/svn131/ZaprosKakOtBrauzera.git /data/ucov/repro/jsoup/Clients/svn131/ZaprosKakOtBrauzera
git clone --depth 1 https://github.com/tangxiqqq/SSTL.git /data/ucov/repro/jsoup/Clients/tangxiqqq/SSTL
git clone --depth 1 https://github.com/tonifdemocorp1-Mend/WebGoat.git /data/ucov/repro/jsoup/Clients/tonifdemocorp1-Mend/WebGoat
git clone --depth 1 https://github.com/ryhaldenys/Poems.git /data/ucov/repro/jsoup/Clients/ryhaldenys/Poems
git clone --depth 1 https://github.com/IliasBrinias/SpaceRoomApi.git /data/ucov/repro/jsoup/Clients/IliasBrinias/SpaceRoomApi
git clone --depth 1 https://github.com/VassBass/webparser.git /data/ucov/repro/jsoup/Clients/VassBass/webparser
git clone --depth 1 https://github.com/seonghuncode/CrawlingOss.git /data/ucov/repro/jsoup/Clients/seonghuncode/CrawlingOss
git clone --depth 1 https://github.com/Nasc1mento/TrieSearchGUI.git /data/ucov/repro/jsoup/Clients/Nasc1mento/TrieSearchGUI
git clone --depth 1 https://github.com/Mohesh-Borah/aem-core-components.git /data/ucov/repro/jsoup/Clients/Mohesh-Borah/aem-core-components
git clone --depth 1 https://github.com/Choudhary1986/Cassandra.git /data/ucov/repro/jsoup/Clients/Choudhary1986/Cassandra
git clone --depth 1 https://github.com/wangy-thu/e-commerce-skynet.git /data/ucov/repro/jsoup/Clients/wangy-thu/e-commerce-skynet
git clone --depth 1 https://github.com/jananiorganiza/test5.git /data/ucov/repro/jsoup/Clients/jananiorganiza/test5
git clone --depth 1 https://github.com/OpenSundsvall/api-service-archive.git /data/ucov/repro/jsoup/Clients/OpenSundsvall/api-service-archive
git clone --depth 1 https://github.com/cdrommens/comicosmos.git /data/ucov/repro/jsoup/Clients/cdrommens/comicosmos
git clone --depth 1 https://github.com/Wassermanreaction/MTG_Deck_Manager.git /data/ucov/repro/jsoup/Clients/Wassermanreaction/MTG_Deck_Manager
git clone --depth 1 https://github.com/YannisTzitzikas/CS561playground.git /data/ucov/repro/jsoup/Clients/YannisTzitzikas/CS561playground
git clone --depth 1 https://github.com/TansanMilMil/birds-eye-scraping.git /data/ucov/repro/jsoup/Clients/TansanMilMil/birds-eye-scraping
git clone --depth 1 https://github.com/cornetto013/spring-tutorials.git /data/ucov/repro/jsoup/Clients/cornetto013/spring-tutorials
git clone --depth 1 https://github.com/anhchangaotim89/WebGoat.git /data/ucov/repro/jsoup/Clients/anhchangaotim89/WebGoat
git clone --depth 1 https://github.com/bakero10/Programacion_Servicios_Y_Procesos.git /data/ucov/repro/jsoup/Clients/bakero10/Programacion_Servicios_Y_Procesos
git clone --depth 1 https://github.com/richard5zx/others.git /data/ucov/repro/jsoup/Clients/richard5zx/others
git clone --depth 1 https://github.com/uni-aau/cleancode-webcrawler.git /data/ucov/repro/jsoup/Clients/uni-aau/cleancode-webcrawler
git clone --depth 1 https://github.com/lykkeee/SpringBoredomHelperBot.git /data/ucov/repro/jsoup/Clients/lykkeee/SpringBoredomHelperBot
git clone --depth 1 https://github.com/syc98syc/KB04_TeamProject.git /data/ucov/repro/jsoup/Clients/syc98syc/KB04_TeamProject
git clone --depth 1 https://github.com/coshelev/jp4v1.git /data/ucov/repro/jsoup/Clients/coshelev/jp4v1
git clone --depth 1 https://github.com/ThakurMangesh2171/docker.git /data/ucov/repro/jsoup/Clients/ThakurMangesh2171/docker
git clone --depth 1 https://github.com/WuYff/flow-cve.git /data/ucov/repro/jsoup/Clients/WuYff/flow-cve
git clone --depth 1 https://github.com/LukaMaranic/AtlassianJava.git /data/ucov/repro/jsoup/Clients/LukaMaranic/AtlassianJava
git clone --depth 1 https://github.com/Randyblo7/openhab-addons.git /data/ucov/repro/jsoup/Clients/Randyblo7/openhab-addons
git clone --depth 1 https://github.com/zhu-niubi/personal-blog.git /data/ucov/repro/jsoup/Clients/zhu-niubi/personal-blog
git clone --depth 1 https://github.com/johancc/software-product-sprint-2022.git /data/ucov/repro/jsoup/Clients/johancc/software-product-sprint-2022
git clone --depth 1 https://github.com/leedyx/wcbot.git /data/ucov/repro/jsoup/Clients/leedyx/wcbot
git clone --depth 1 https://github.com/seonysun/HelloBoot.git /data/ucov/repro/jsoup/Clients/seonysun/HelloBoot
git clone --depth 1 https://github.com/YeeZC/java-profiler.git /data/ucov/repro/jsoup/Clients/YeeZC/java-profiler
git clone --depth 1 https://github.com/2yu33/FileConverter.git /data/ucov/repro/jsoup/Clients/2yu33/FileConverter
git clone --depth 1 https://github.com/nkanyisom/Vulnado.git /data/ucov/repro/jsoup/Clients/nkanyisom/Vulnado
git clone --depth 1 https://github.com/skillbox-java/images_downloader.git /data/ucov/repro/jsoup/Clients/skillbox-java/images_downloader
git clone --depth 1 https://github.com/yasineryigit/Currency-Socket.git /data/ucov/repro/jsoup/Clients/yasineryigit/Currency-Socket
git clone --depth 1 https://github.com/franciscotis/simple-library-api.git /data/ucov/repro/jsoup/Clients/franciscotis/simple-library-api
git clone --depth 1 https://github.com/thek2range/OrNG.git /data/ucov/repro/jsoup/Clients/thek2range/OrNG
git clone --depth 1 https://github.com/kavitbang/WebGoat.git /data/ucov/repro/jsoup/Clients/kavitbang/WebGoat
git clone --depth 1 https://github.com/Csanoo/kevic.git /data/ucov/repro/jsoup/Clients/Csanoo/kevic
git clone --depth 1 https://github.com/JackWang1230/knowledge-learning-summary.git /data/ucov/repro/jsoup/Clients/JackWang1230/knowledge-learning-summary
git clone --depth 1 https://github.com/MohammedThalha2002/training-module-system-backend.git /data/ucov/repro/jsoup/Clients/MohammedThalha2002/training-module-system-backend
git clone --depth 1 https://github.com/SINGALman/fang.git /data/ucov/repro/jsoup/Clients/SINGALman/fang
git clone --depth 1 https://github.com/milan011/flowing-project.git /data/ucov/repro/jsoup/Clients/milan011/flowing-project
git clone --depth 1 https://github.com/KWONSUYEO/TeamProject.git /data/ucov/repro/jsoup/Clients/KWONSUYEO/TeamProject
git clone --depth 1 https://github.com/carlucci71/colossium.git /data/ucov/repro/jsoup/Clients/carlucci71/colossium
git clone --depth 1 https://github.com/enesbahtiyar/PortfolioGameWebsite.git /data/ucov/repro/jsoup/Clients/enesbahtiyar/PortfolioGameWebsite
git clone --depth 1 https://github.com/pavithrahatharasinghe/Melody.git /data/ucov/repro/jsoup/Clients/pavithrahatharasinghe/Melody
git clone --depth 1 https://github.com/open-vertical-media/open-nav.git /data/ucov/repro/jsoup/Clients/open-vertical-media/open-nav
git clone --depth 1 https://github.com/klaud-speech/jsoup.git /data/ucov/repro/jsoup/Clients/klaud-speech/jsoup
git clone --depth 1 https://github.com/minhyeok08/springBoot.git /data/ucov/repro/jsoup/Clients/minhyeok08/springBoot
git clone --depth 1 https://github.com/dringdwing/ManagementProject.git /data/ucov/repro/jsoup/Clients/dringdwing/ManagementProject
git clone --depth 1 https://github.com/yangyang1040553/testjava.git /data/ucov/repro/jsoup/Clients/yangyang1040553/testjava
git clone --depth 1 https://github.com/hanqiufengGit/sanri-tools-maven.git /data/ucov/repro/jsoup/Clients/hanqiufengGit/sanri-tools-maven
git clone --depth 1 https://github.com/elivinus/webgoat.git /data/ucov/repro/jsoup/Clients/elivinus/webgoat
git clone --depth 1 https://github.com/Shimadzusan/dataAnalyzer.git /data/ucov/repro/jsoup/Clients/Shimadzusan/dataAnalyzer
git clone --depth 1 https://github.com/RePlaze/LoL_Bot.git /data/ucov/repro/jsoup/Clients/RePlaze/LoL_Bot
git clone --depth 1 https://github.com/FabuDev7/MangaApp.git /data/ucov/repro/jsoup/Clients/FabuDev7/MangaApp
git clone --depth 1 https://github.com/akashgupta2307g/Smart-Buyer-.git /data/ucov/repro/jsoup/Clients/akashgupta2307g/Smart-Buyer-
git clone --depth 1 https://github.com/doecode/server.git /data/ucov/repro/jsoup/Clients/doecode/server
git clone --depth 1 https://github.com/Ansdance/Nike.git /data/ucov/repro/jsoup/Clients/Ansdance/Nike
git clone --depth 1 https://github.com/yx-Yaoxaing/these-thing.git /data/ucov/repro/jsoup/Clients/yx-Yaoxaing/these-thing
git clone --depth 1 https://github.com/ginkotte/railwayGenerator.git /data/ucov/repro/jsoup/Clients/ginkotte/railwayGenerator
git clone --depth 1 https://github.com/mrAntonZenkov/ForkJoinPool.git /data/ucov/repro/jsoup/Clients/mrAntonZenkov/ForkJoinPool
git clone --depth 1 https://github.com/dangngocphuc/DATN-BE.git /data/ucov/repro/jsoup/Clients/dangngocphuc/DATN-BE
git clone --depth 1 https://github.com/DojinP/metahouse.git /data/ucov/repro/jsoup/Clients/DojinP/metahouse
git clone --depth 1 https://github.com/ddaGarrido/oauth.git /data/ucov/repro/jsoup/Clients/ddaGarrido/oauth
git clone --depth 1 https://github.com/lycGitHub123/MallChat.git /data/ucov/repro/jsoup/Clients/lycGitHub123/MallChat
git clone --depth 1 https://github.com/MurtazoLutfulloyev/give-bot.git /data/ucov/repro/jsoup/Clients/MurtazoLutfulloyev/give-bot
git clone --depth 1 https://github.com/RuidiChang/Distributed-Systems.git /data/ucov/repro/jsoup/Clients/RuidiChang/Distributed-Systems
git clone --depth 1 https://github.com/gbdishant/Website-Contact-Detail.git /data/ucov/repro/jsoup/Clients/gbdishant/Website-Contact-Detail
git clone --depth 1 https://github.com/amineMbarki1/local_news_miner.git /data/ucov/repro/jsoup/Clients/amineMbarki1/local_news_miner
git clone --depth 1 https://github.com/PastushenkoIlya/CitiesGame.git /data/ucov/repro/jsoup/Clients/PastushenkoIlya/CitiesGame
git clone --depth 1 https://github.com/wmz-personal/heima-leadnews.git /data/ucov/repro/jsoup/Clients/wmz-personal/heima-leadnews
git clone --depth 1 https://github.com/pyatikin/ParseHabr.git /data/ucov/repro/jsoup/Clients/pyatikin/ParseHabr
git clone --depth 1 https://github.com/paramint/Autowasp.git /data/ucov/repro/jsoup/Clients/paramint/Autowasp
git clone --depth 1 https://github.com/MaxAntonioDeSouza/test-jenkins.git /data/ucov/repro/jsoup/Clients/MaxAntonioDeSouza/test-jenkins
git clone --depth 1 https://github.com/rajeshyemul/Java_Selenium_Framework2.git /data/ucov/repro/jsoup/Clients/rajeshyemul/Java_Selenium_Framework2
git clone --depth 1 https://github.com/ankit979n/Web-Scraping-using-Java.git /data/ucov/repro/jsoup/Clients/ankit979n/Web-Scraping-using-Java
git clone --depth 1 https://github.com/kvn746/store_grabber.git /data/ucov/repro/jsoup/Clients/kvn746/store_grabber
git clone --depth 1 https://github.com/spitty/VKConnector.git /data/ucov/repro/jsoup/Clients/spitty/VKConnector
git clone --depth 1 https://github.com/DreamFlower14/MongoPRJ.git /data/ucov/repro/jsoup/Clients/DreamFlower14/MongoPRJ
git clone --depth 1 https://github.com/100rootrain/KeunWooRepository.git /data/ucov/repro/jsoup/Clients/100rootrain/KeunWooRepository
git clone --depth 1 https://github.com/shk95/GitEditor-backend.git /data/ucov/repro/jsoup/Clients/shk95/GitEditor-backend
git clone --depth 1 https://github.com/OneDayOnePost/ODOP.git /data/ucov/repro/jsoup/Clients/OneDayOnePost/ODOP
git clone --depth 1 https://github.com/ChristinaK97/KnowledgeGraphs.git /data/ucov/repro/jsoup/Clients/ChristinaK97/KnowledgeGraphs
git clone --depth 1 https://github.com/karimerri04/Azelha.git /data/ucov/repro/jsoup/Clients/karimerri04/Azelha
git clone --depth 1 https://github.com/finos/legend-engine.git /data/ucov/repro/jsoup/Clients/finos/legend-engine
git clone --depth 1 https://github.com/tyronewj/FakeNetEaseMusicPlayer.git /data/ucov/repro/jsoup/Clients/tyronewj/FakeNetEaseMusicPlayer
git clone --depth 1 https://github.com/neatlogic/neatlogic-parent.git /data/ucov/repro/jsoup/Clients/neatlogic/neatlogic-parent
git clone --depth 1 https://github.com/SimonRth/Scrapper_JAVA.git /data/ucov/repro/jsoup/Clients/SimonRth/Scrapper_JAVA
git clone --depth 1 https://github.com/xiaofan0408/View-Back-End.git /data/ucov/repro/jsoup/Clients/xiaofan0408/View-Back-End
git clone --depth 1 https://github.com/eahau/douyin-openapi.git /data/ucov/repro/jsoup/Clients/eahau/douyin-openapi
git clone --depth 1 https://github.com/chlwjddn7/spring-legacy-proejct-sample.git /data/ucov/repro/jsoup/Clients/chlwjddn7/spring-legacy-proejct-sample
git clone --depth 1 https://github.com/bigskysoftware/chill.git /data/ucov/repro/jsoup/Clients/bigskysoftware/chill
git clone --depth 1 https://github.com/TobiasTheDanish/MovieScraping.git /data/ucov/repro/jsoup/Clients/TobiasTheDanish/MovieScraping
git clone --depth 1 https://github.com/DannyGalvan/Project_boletos.git /data/ucov/repro/jsoup/Clients/DannyGalvan/Project_boletos
git clone --depth 1 https://github.com/Satyabrata6gb/Twitter-Clone.git /data/ucov/repro/jsoup/Clients/Satyabrata6gb/Twitter-Clone
git clone --depth 1 https://github.com/RacabRasulov/ariwalPort.git /data/ucov/repro/jsoup/Clients/RacabRasulov/ariwalPort
git clone --depth 1 https://github.com/zhangjushun/xms-base.git /data/ucov/repro/jsoup/Clients/zhangjushun/xms-base
git clone --depth 1 https://github.com/xiphis/swingutils.git /data/ucov/repro/jsoup/Clients/xiphis/swingutils
git clone --depth 1 https://github.com/priyamtiwari1245/SearchEngine.git /data/ucov/repro/jsoup/Clients/priyamtiwari1245/SearchEngine
git clone --depth 1 https://github.com/hassanazh-telenor/Webgoat-Devops.git /data/ucov/repro/jsoup/Clients/hassanazh-telenor/Webgoat-Devops
git clone --depth 1 https://github.com/kylelin1998/ReleasesMonitorTelegramBot.git /data/ucov/repro/jsoup/Clients/kylelin1998/ReleasesMonitorTelegramBot
git clone --depth 1 https://github.com/SAP-samples/security-research-cruzzer.git /data/ucov/repro/jsoup/Clients/SAP-samples/security-research-cruzzer
git clone --depth 1 https://github.com/Ngazoa/ci-cd.git /data/ucov/repro/jsoup/Clients/Ngazoa/ci-cd
git clone --depth 1 https://github.com/pologood/anvars.git /data/ucov/repro/jsoup/Clients/pologood/anvars
git clone --depth 1 https://github.com/spiliti/oldgrams.git /data/ucov/repro/jsoup/Clients/spiliti/oldgrams
git clone --depth 1 https://github.com/AP-Kai/MyWebScanner.git /data/ucov/repro/jsoup/Clients/AP-Kai/MyWebScanner
git clone --depth 1 https://github.com/danielgoren14/CurrencyExchangeRate1.git /data/ucov/repro/jsoup/Clients/danielgoren14/CurrencyExchangeRate1
git clone --depth 1 https://github.com/bellmit/andwell235.git /data/ucov/repro/jsoup/Clients/bellmit/andwell235
git clone --depth 1 https://github.com/Chiping28/WeatherParser.git /data/ucov/repro/jsoup/Clients/Chiping28/WeatherParser
git clone --depth 1 https://github.com/go-for-naver/Spring_Legacy_Templates.git /data/ucov/repro/jsoup/Clients/go-for-naver/Spring_Legacy_Templates
git clone --depth 1 https://github.com/markarko/dawson-scheduler-api.git /data/ucov/repro/jsoup/Clients/markarko/dawson-scheduler-api
git clone --depth 1 https://github.com/MYEHUB0/starlink.git /data/ucov/repro/jsoup/Clients/MYEHUB0/starlink
git clone --depth 1 https://github.com/JVictorC/partly-repo.git /data/ucov/repro/jsoup/Clients/JVictorC/partly-repo
git clone --depth 1 https://github.com/Dima2021/SecShepherdReachability.git /data/ucov/repro/jsoup/Clients/Dima2021/SecShepherdReachability
git clone --depth 1 https://github.com/SamudithaD97/ElctroGrid-Individual.git /data/ucov/repro/jsoup/Clients/SamudithaD97/ElctroGrid-Individual
git clone --depth 1 https://github.com/guy0090/bdo-market-api.git /data/ucov/repro/jsoup/Clients/guy0090/bdo-market-api
git clone --depth 1 https://github.com/JeraCodeHub/testPublic.git /data/ucov/repro/jsoup/Clients/JeraCodeHub/testPublic
git clone --depth 1 https://github.com/Ahmadedu/webgoat.git /data/ucov/repro/jsoup/Clients/Ahmadedu/webgoat
git clone --depth 1 https://github.com/HariharanBaskarraj/Camunda8.git /data/ucov/repro/jsoup/Clients/HariharanBaskarraj/Camunda8
git clone --depth 1 https://github.com/alex-petkevich/joplin-forwarder-server.git /data/ucov/repro/jsoup/Clients/alex-petkevich/joplin-forwarder-server
git clone --depth 1 https://github.com/sudham16/WebDataExtractor.git /data/ucov/repro/jsoup/Clients/sudham16/WebDataExtractor
git clone --depth 1 https://github.com/GDj001010/springstudy.git /data/ucov/repro/jsoup/Clients/GDj001010/springstudy
git clone --depth 1 https://github.com/MikolaChe/JavaSpringTelegramBot.git /data/ucov/repro/jsoup/Clients/MikolaChe/JavaSpringTelegramBot
git clone --depth 1 https://github.com/qatester121/filpkart.git /data/ucov/repro/jsoup/Clients/qatester121/filpkart
git clone --depth 1 https://github.com/gag068/WebGoat1.git /data/ucov/repro/jsoup/Clients/gag068/WebGoat1
git clone --depth 1 https://github.com/liubangde88/oooo.git /data/ucov/repro/jsoup/Clients/liubangde88/oooo
git clone --depth 1 https://github.com/rakeshthumar111/WebGoat-DevOps.git /data/ucov/repro/jsoup/Clients/rakeshthumar111/WebGoat-DevOps
git clone --depth 1 https://github.com/alexves-b/searchengine.git /data/ucov/repro/jsoup/Clients/alexves-b/searchengine
git clone --depth 1 https://github.com/Kolivim/search-engine.git /data/ucov/repro/jsoup/Clients/Kolivim/search-engine
git clone --depth 1 https://github.com/CMTcode/sign-in-assistant.git /data/ucov/repro/jsoup/Clients/CMTcode/sign-in-assistant
git clone --depth 1 https://github.com/arkadasgupta17/TeamSAP.git /data/ucov/repro/jsoup/Clients/arkadasgupta17/TeamSAP
git clone --depth 1 https://github.com/DDOSer1337/SiteSearchEngine.git /data/ucov/repro/jsoup/Clients/DDOSer1337/SiteSearchEngine
git clone --depth 1 https://github.com/nylm9/MovieReservation.git /data/ucov/repro/jsoup/Clients/nylm9/MovieReservation
git clone --depth 1 https://github.com/nikitinaak/Search_engine.git /data/ucov/repro/jsoup/Clients/nikitinaak/Search_engine
git clone --depth 1 https://github.com/HihaoWang/123.git /data/ucov/repro/jsoup/Clients/HihaoWang/123
git clone --depth 1 https://github.com/XAHTEPC/MyCarManager.git /data/ucov/repro/jsoup/Clients/XAHTEPC/MyCarManager
git clone --depth 1 https://github.com/timi137137/EatWhatLibrary.git /data/ucov/repro/jsoup/Clients/timi137137/EatWhatLibrary
git clone --depth 1 https://github.com/bootiful-podcast/podcast-search-service.git /data/ucov/repro/jsoup/Clients/bootiful-podcast/podcast-search-service
git clone --depth 1 https://github.com/Cupcake-master/2023_ITIS_IS_11-906_BilalovBF.git /data/ucov/repro/jsoup/Clients/Cupcake-master/2023_ITIS_IS_11-906_BilalovBF
git clone --depth 1 https://github.com/cristiantfs/Web-goat-code-test.git /data/ucov/repro/jsoup/Clients/cristiantfs/Web-goat-code-test
git clone --depth 1 https://github.com/DataGremlin/SonarBot.git /data/ucov/repro/jsoup/Clients/DataGremlin/SonarBot
git clone --depth 1 https://github.com/shiva-art/webgoat2906.git /data/ucov/repro/jsoup/Clients/shiva-art/webgoat2906
git clone --depth 1 https://github.com/liwagu/liwa-so.git /data/ucov/repro/jsoup/Clients/liwagu/liwa-so
git clone --depth 1 https://github.com/zhongfeather/JAVA-.git /data/ucov/repro/jsoup/Clients/zhongfeather/JAVA-
git clone --depth 1 https://github.com/webbnba/restaurant_voting.git /data/ucov/repro/jsoup/Clients/webbnba/restaurant_voting
git clone --depth 1 https://github.com/Evolution-X/external_cldr.git /data/ucov/repro/jsoup/Clients/Evolution-X/external_cldr
git clone --depth 1 https://github.com/bentrieu/NRA.git /data/ucov/repro/jsoup/Clients/bentrieu/NRA
git clone --depth 1 https://github.com/swade222/UCSDstarter.git /data/ucov/repro/jsoup/Clients/swade222/UCSDstarter
git clone --depth 1 https://github.com/indexss/EMeiYou.git /data/ucov/repro/jsoup/Clients/indexss/EMeiYou
git clone --depth 1 https://github.com/GhofraneFerchichi/blog-front.git /data/ucov/repro/jsoup/Clients/GhofraneFerchichi/blog-front
git clone --depth 1 https://github.com/dharanimoram/yourstoreapplication.git /data/ucov/repro/jsoup/Clients/dharanimoram/yourstoreapplication
git clone --depth 1 https://github.com/aiapo/RepoGrabber.git /data/ucov/repro/jsoup/Clients/aiapo/RepoGrabber
git clone --depth 1 https://github.com/yangjing-start/GXA-web.git /data/ucov/repro/jsoup/Clients/yangjing-start/GXA-web
git clone --depth 1 https://github.com/surajkr23/GmailAPI.git /data/ucov/repro/jsoup/Clients/surajkr23/GmailAPI
git clone --depth 1 https://github.com/MatejBujdak/Webcrawler_oldversion.git /data/ucov/repro/jsoup/Clients/MatejBujdak/Webcrawler_oldversion
git clone --depth 1 https://github.com/sukhi90/simpli-project.git /data/ucov/repro/jsoup/Clients/sukhi90/simpli-project
git clone --depth 1 https://github.com/leRequiem/BD.git /data/ucov/repro/jsoup/Clients/leRequiem/BD
git clone --depth 1 https://github.com/yuejianli/Stock_Api.git /data/ucov/repro/jsoup/Clients/yuejianli/Stock_Api
git clone --depth 1 https://github.com/Christianqling2/Haggle.git /data/ucov/repro/jsoup/Clients/Christianqling2/Haggle
git clone --depth 1 https://github.com/kiransg89/chatgpt.git /data/ucov/repro/jsoup/Clients/kiransg89/chatgpt
git clone --depth 1 https://github.com/EvgeniiSamarin/JavaCrawler.git /data/ucov/repro/jsoup/Clients/EvgeniiSamarin/JavaCrawler
git clone --depth 1 https://github.com/yazsul/media-nav.git /data/ucov/repro/jsoup/Clients/yazsul/media-nav
git clone --depth 1 https://github.com/END888/yincy-springboot-init.git /data/ucov/repro/jsoup/Clients/END888/yincy-springboot-init
git clone --depth 1 https://github.com/RSHKwee/GnuCashCharts.git /data/ucov/repro/jsoup/Clients/RSHKwee/GnuCashCharts
git clone --depth 1 https://github.com/dzasta997/super_projekt.git /data/ucov/repro/jsoup/Clients/dzasta997/super_projekt
git clone --depth 1 https://github.com/emretterzi/Scraper-App-Web.git /data/ucov/repro/jsoup/Clients/emretterzi/Scraper-App-Web
git clone --depth 1 https://github.com/sergey-zabolotnyi/javaPro.git /data/ucov/repro/jsoup/Clients/sergey-zabolotnyi/javaPro
git clone --depth 1 https://github.com/jaimeizuz/jenkins-docker.git /data/ucov/repro/jsoup/Clients/jaimeizuz/jenkins-docker
git clone --depth 1 https://github.com/yeozhenhao/Java_HTMLtoPDF.git /data/ucov/repro/jsoup/Clients/yeozhenhao/Java_HTMLtoPDF
git clone --depth 1 https://github.com/Void-XKG/test01.git /data/ucov/repro/jsoup/Clients/Void-XKG/test01
git clone --depth 1 https://github.com/Nipuna1234567/ElectroGrid.git /data/ucov/repro/jsoup/Clients/Nipuna1234567/ElectroGrid
git clone --depth 1 https://github.com/maz004/webgoqt2.git /data/ucov/repro/jsoup/Clients/maz004/webgoqt2
git clone --depth 1 https://github.com/Alicechui/Web-Scraping-NLP-App.git /data/ucov/repro/jsoup/Clients/Alicechui/Web-Scraping-NLP-App
git clone --depth 1 https://github.com/icWinter/common-util.git /data/ucov/repro/jsoup/Clients/icWinter/common-util
git clone --depth 1 https://github.com/ZMitya9/SearchEngine.git /data/ucov/repro/jsoup/Clients/ZMitya9/SearchEngine
git clone --depth 1 https://github.com/yasith1234/CustomerManagement.git /data/ucov/repro/jsoup/Clients/yasith1234/CustomerManagement
git clone --depth 1 https://github.com/yzqnmg/heima-leadnews.git /data/ucov/repro/jsoup/Clients/yzqnmg/heima-leadnews
git clone --depth 1 https://github.com/ircecam/module_10.git /data/ucov/repro/jsoup/Clients/ircecam/module_10
git clone --depth 1 https://github.com/Exanily/java_basics.git /data/ucov/repro/jsoup/Clients/Exanily/java_basics
git clone --depth 1 https://github.com/saulmella12/Formula1.git /data/ucov/repro/jsoup/Clients/saulmella12/Formula1
git clone --depth 1 https://github.com/daomanhluan/ai.stock.git /data/ucov/repro/jsoup/Clients/daomanhluan/ai.stock
git clone --depth 1 https://github.com/victory460/K8S.git /data/ucov/repro/jsoup/Clients/victory460/K8S
git clone --depth 1 https://github.com/guzevka/telegram-bot.git /data/ucov/repro/jsoup/Clients/guzevka/telegram-bot
git clone --depth 1 https://github.com/brianb1996/CompSci_2261-Project-6.git /data/ucov/repro/jsoup/Clients/brianb1996/CompSci_2261-Project-6
git clone --depth 1 https://github.com/Nasidiqi/ControversyInNews.git /data/ucov/repro/jsoup/Clients/Nasidiqi/ControversyInNews
git clone --depth 1 https://github.com/karimyasser107/search-engine-java.git /data/ucov/repro/jsoup/Clients/karimyasser107/search-engine-java
git clone --depth 1 https://github.com/1975947214/paicoding.git /data/ucov/repro/jsoup/Clients/1975947214/paicoding
git clone --depth 1 https://github.com/spacezyx/DataGovernancePlatform_Backend.git /data/ucov/repro/jsoup/Clients/spacezyx/DataGovernancePlatform_Backend
git clone --depth 1 https://github.com/timbercld/timbercld-sys-service.git /data/ucov/repro/jsoup/Clients/timbercld/timbercld-sys-service
git clone --depth 1 https://github.com/tianxiaotouyuna/lianghua_java_service.git /data/ucov/repro/jsoup/Clients/tianxiaotouyuna/lianghua_java_service
git clone --depth 1 https://github.com/jwdeveloper/TikTokLiveJava.git /data/ucov/repro/jsoup/Clients/jwdeveloper/TikTokLiveJava
git clone --depth 1 https://github.com/EsionCHEN/Esion.git /data/ucov/repro/jsoup/Clients/EsionCHEN/Esion
git clone --depth 1 https://github.com/globalbioticinteractions/nomer.git /data/ucov/repro/jsoup/Clients/globalbioticinteractions/nomer
git clone --depth 1 https://github.com/botkoda/moex.git /data/ucov/repro/jsoup/Clients/botkoda/moex
git clone --depth 1 https://github.com/backendgame/JavaBackend.git /data/ucov/repro/jsoup/Clients/backendgame/JavaBackend
git clone --depth 1 https://github.com/DGoyal29/Maven-dependency.git /data/ucov/repro/jsoup/Clients/DGoyal29/Maven-dependency
git clone --depth 1 https://github.com/AlexandrKhalilulin/crypto.git /data/ucov/repro/jsoup/Clients/AlexandrKhalilulin/crypto
git clone --depth 1 https://github.com/KingPrimes/NyxBot.git /data/ucov/repro/jsoup/Clients/KingPrimes/NyxBot
git clone --depth 1 https://github.com/woshilmx/animer-backend.git /data/ucov/repro/jsoup/Clients/woshilmx/animer-backend
git clone --depth 1 https://github.com/AnnaPotupalo/QuotesRunet_github.git /data/ucov/repro/jsoup/Clients/AnnaPotupalo/QuotesRunet_github
git clone --depth 1 https://github.com/SadCryFamily/DataOxScrapingTask.git /data/ucov/repro/jsoup/Clients/SadCryFamily/DataOxScrapingTask
git clone --depth 1 https://github.com/AlekseyShibayev/additional-education-info.git /data/ucov/repro/jsoup/Clients/AlekseyShibayev/additional-education-info
git clone --depth 1 https://github.com/jaig1995/accionistas-eebp.git /data/ucov/repro/jsoup/Clients/jaig1995/accionistas-eebp
git clone --depth 1 https://github.com/Aztroe/Scraper.git /data/ucov/repro/jsoup/Clients/Aztroe/Scraper
git clone --depth 1 https://github.com/AndreiBudevich/cryptocurrencywatcher.git /data/ucov/repro/jsoup/Clients/AndreiBudevich/cryptocurrencywatcher
git clone --depth 1 https://github.com/oropeza/sat-cfdi-web-scraper.git /data/ucov/repro/jsoup/Clients/oropeza/sat-cfdi-web-scraper
git clone --depth 1 https://github.com/dhieff73/CampsideForumBackend.git /data/ucov/repro/jsoup/Clients/dhieff73/CampsideForumBackend
git clone --depth 1 https://github.com/shinyeeun789/haebeop.git /data/ucov/repro/jsoup/Clients/shinyeeun789/haebeop
git clone --depth 1 https://github.com/saifali1035/Jenkins-ZerotoHero.git /data/ucov/repro/jsoup/Clients/saifali1035/Jenkins-ZerotoHero
git clone --depth 1 https://github.com/5kylight/wikiscrap.git /data/ucov/repro/jsoup/Clients/5kylight/wikiscrap
git clone --depth 1 https://github.com/evgenyzhulpa/searchengine.git /data/ucov/repro/jsoup/Clients/evgenyzhulpa/searchengine
git clone --depth 1 https://github.com/AlejandraMUBA/3_WebGoat-JAVA.git /data/ucov/repro/jsoup/Clients/AlejandraMUBA/3_WebGoat-JAVA
git clone --depth 1 https://github.com/duTianze/memo.git /data/ucov/repro/jsoup/Clients/duTianze/memo
git clone --depth 1 https://github.com/rezzgabriel/webcrawler.git /data/ucov/repro/jsoup/Clients/rezzgabriel/webcrawler
git clone --depth 1 https://github.com/addy360/whizzy.git /data/ucov/repro/jsoup/Clients/addy360/whizzy
git clone --depth 1 https://github.com/Mutess/SpringStudy.git /data/ucov/repro/jsoup/Clients/Mutess/SpringStudy
git clone --depth 1 https://github.com/Maxbleu/AccountManager.git /data/ucov/repro/jsoup/Clients/Maxbleu/AccountManager
git clone --depth 1 https://github.com/RolinFirelink/orange-backend.git /data/ucov/repro/jsoup/Clients/RolinFirelink/orange-backend
git clone --depth 1 https://github.com/jt5766/final_project.git /data/ucov/repro/jsoup/Clients/jt5766/final_project
git clone --depth 1 https://github.com/ritesh107/jenkinsbackup.git /data/ucov/repro/jsoup/Clients/ritesh107/jenkinsbackup
git clone --depth 1 https://github.com/chiencao2402/BookShop1234.git /data/ucov/repro/jsoup/Clients/chiencao2402/BookShop1234
git clone --depth 1 https://github.com/lequangtoi202/good_news.git /data/ucov/repro/jsoup/Clients/lequangtoi202/good_news
git clone --depth 1 https://github.com/chen769330532/20230309.git /data/ucov/repro/jsoup/Clients/chen769330532/20230309
git clone --depth 1 https://github.com/thirtycapital/hanger.git /data/ucov/repro/jsoup/Clients/thirtycapital/hanger
git clone --depth 1 https://github.com/jainteg2/jainteg2.git /data/ucov/repro/jsoup/Clients/jainteg2/jainteg2
git clone --depth 1 https://github.com/a943356255/GrouthRecord.git /data/ucov/repro/jsoup/Clients/a943356255/GrouthRecord
git clone --depth 1 https://github.com/Adact-NGN/priskalkulator-service.git /data/ucov/repro/jsoup/Clients/Adact-NGN/priskalkulator-service
git clone --depth 1 https://github.com/jaymulani/ScraperSmart.git /data/ucov/repro/jsoup/Clients/jaymulani/ScraperSmart
git clone --depth 1 https://github.com/yinxs2003/flink.git /data/ucov/repro/jsoup/Clients/yinxs2003/flink
git clone --depth 1 https://github.com/ProductManage-Leo/alldata.git /data/ucov/repro/jsoup/Clients/ProductManage-Leo/alldata
git clone --depth 1 https://github.com/SulaimanHumaid/ParallelWebCrawler.git /data/ucov/repro/jsoup/Clients/SulaimanHumaid/ParallelWebCrawler
git clone --depth 1 https://github.com/gopichandpuli06/lab1.git /data/ucov/repro/jsoup/Clients/gopichandpuli06/lab1
git clone --depth 1 https://github.com/Arielnoder/news.git /data/ucov/repro/jsoup/Clients/Arielnoder/news
git clone --depth 1 https://github.com/Lees0-0/Team_project_group_3.git /data/ucov/repro/jsoup/Clients/Lees0-0/Team_project_group_3
git clone --depth 1 https://github.com/nareshbabumandula/Flipkart_Automation.git /data/ucov/repro/jsoup/Clients/nareshbabumandula/Flipkart_Automation
git clone --depth 1 https://github.com/akter4855/Group-B.git /data/ucov/repro/jsoup/Clients/akter4855/Group-B
git clone --depth 1 https://github.com/Hooorus/mshive-backend.git /data/ucov/repro/jsoup/Clients/Hooorus/mshive-backend
git clone --depth 1 https://github.com/pantelicn/nms-be.git /data/ucov/repro/jsoup/Clients/pantelicn/nms-be
git clone --depth 1 https://github.com/rodrigobash-eld/gitlab-java-vuln.git /data/ucov/repro/jsoup/Clients/rodrigobash-eld/gitlab-java-vuln
git clone --depth 1 https://github.com/ctcampbellcom/WebGoat.git /data/ucov/repro/jsoup/Clients/ctcampbellcom/WebGoat
git clone --depth 1 https://github.com/Kevil-Karnage/WHO_WINS.git /data/ucov/repro/jsoup/Clients/Kevil-Karnage/WHO_WINS
git clone --depth 1 https://github.com/GuardMY/demo.git /data/ucov/repro/jsoup/Clients/GuardMY/demo
git clone --depth 1 https://github.com/Jxxchxn/Board.git /data/ucov/repro/jsoup/Clients/Jxxchxn/Board
git clone --depth 1 https://github.com/SulthanFahrein/UAS_ConfigMaster_MKPL.git /data/ucov/repro/jsoup/Clients/SulthanFahrein/UAS_ConfigMaster_MKPL
git clone --depth 1 https://github.com/suryaoff/Weby.git /data/ucov/repro/jsoup/Clients/suryaoff/Weby
git clone --depth 1 https://github.com/junkkookk/saffron_cloud.git /data/ucov/repro/jsoup/Clients/junkkookk/saffron_cloud
git clone --depth 1 https://github.com/ekgame/storasbot.git /data/ucov/repro/jsoup/Clients/ekgame/storasbot
git clone --depth 1 https://github.com/PattonLi/music-player-server-java.git /data/ucov/repro/jsoup/Clients/PattonLi/music-player-server-java
git clone --depth 1 https://github.com/AvihayBenAmi/MonitoringSystem.git /data/ucov/repro/jsoup/Clients/AvihayBenAmi/MonitoringSystem
git clone --depth 1 https://github.com/richnou/vui2.git /data/ucov/repro/jsoup/Clients/richnou/vui2
git clone --depth 1 https://github.com/dmitriy-utkin/searchengine.git /data/ucov/repro/jsoup/Clients/dmitriy-utkin/searchengine
git clone --depth 1 https://github.com/AcceleratorMX/javaCoreTeamProject.git /data/ucov/repro/jsoup/Clients/AcceleratorMX/javaCoreTeamProject
git clone --depth 1 https://github.com/dlalfo1/springstudy.git /data/ucov/repro/jsoup/Clients/dlalfo1/springstudy
git clone --depth 1 https://github.com/Ale1x/rss-scraper.git /data/ucov/repro/jsoup/Clients/Ale1x/rss-scraper
git clone --depth 1 https://github.com/Vidula16/PMS.git /data/ucov/repro/jsoup/Clients/Vidula16/PMS
git clone --depth 1 https://github.com/youbenwu/abs-cloud.git /data/ucov/repro/jsoup/Clients/youbenwu/abs-cloud
git clone --depth 1 https://github.com/aaejo/institution-finder.git /data/ucov/repro/jsoup/Clients/aaejo/institution-finder
git clone --depth 1 https://github.com/suryaoff/WGT.git /data/ucov/repro/jsoup/Clients/suryaoff/WGT
git clone --depth 1 https://github.com/ytlou/Rurate.git /data/ucov/repro/jsoup/Clients/ytlou/Rurate
git clone --depth 1 https://github.com/YaroslavBrek/api-tests.git /data/ucov/repro/jsoup/Clients/YaroslavBrek/api-tests
git clone --depth 1 https://github.com/paulguckian/WebGoat-DevOps.git /data/ucov/repro/jsoup/Clients/paulguckian/WebGoat-DevOps
git clone --depth 1 https://github.com/intrapus/WebGoat.git /data/ucov/repro/jsoup/Clients/intrapus/WebGoat
git clone --depth 1 https://github.com/asmaaadel0/Search_Engine.git /data/ucov/repro/jsoup/Clients/asmaaadel0/Search_Engine
git clone --depth 1 https://github.com/Longren2458/AvitoParser.git /data/ucov/repro/jsoup/Clients/Longren2458/AvitoParser
git clone --depth 1 https://github.com/Zuko44/job4j_threads.git /data/ucov/repro/jsoup/Clients/Zuko44/job4j_threads
git clone --depth 1 https://github.com/Sidhanta3366/sid_Project.git /data/ucov/repro/jsoup/Clients/Sidhanta3366/sid_Project
git clone --depth 1 https://github.com/Acareld/JDAMusicBot.git /data/ucov/repro/jsoup/Clients/Acareld/JDAMusicBot
git clone --depth 1 https://github.com/1021862752/CommunityAppletBackend.git /data/ucov/repro/jsoup/Clients/1021862752/CommunityAppletBackend
git clone --depth 1 https://github.com/ghas-results/htl-tck.git /data/ucov/repro/jsoup/Clients/ghas-results/htl-tck
git clone --depth 1 https://github.com/Yura09/tour-booking.git /data/ucov/repro/jsoup/Clients/Yura09/tour-booking
git clone --depth 1 https://github.com/Arrowplaz/BetterPokedex.git /data/ucov/repro/jsoup/Clients/Arrowplaz/BetterPokedex
git clone --depth 1 https://github.com/GeekMasher/WebGoat.git /data/ucov/repro/jsoup/Clients/GeekMasher/WebGoat
git clone --depth 1 https://github.com/cyPark95/My-Study.git /data/ucov/repro/jsoup/Clients/cyPark95/My-Study
git clone --depth 1 https://github.com/serhioms/Zoo.git /data/ucov/repro/jsoup/Clients/serhioms/Zoo
git clone --depth 1 https://github.com/SamTL91/Webgoat-DevOps.git /data/ucov/repro/jsoup/Clients/SamTL91/Webgoat-DevOps
git clone --depth 1 https://github.com/zw543190914/cloud.git /data/ucov/repro/jsoup/Clients/zw543190914/cloud
git clone --depth 1 https://github.com/christosservosNCIN/WebGoat.git /data/ucov/repro/jsoup/Clients/christosservosNCIN/WebGoat
git clone --depth 1 https://github.com/sandeep-negi/web-testing-b2b.git /data/ucov/repro/jsoup/Clients/sandeep-negi/web-testing-b2b
git clone --depth 1 https://github.com/wujun728/jun_java_plugin.git /data/ucov/repro/jsoup/Clients/wujun728/jun_java_plugin
git clone --depth 1 https://github.com/sukkyun2/cbnu-allimi.git /data/ucov/repro/jsoup/Clients/sukkyun2/cbnu-allimi
git clone --depth 1 https://github.com/dayeaha/moviefan.git /data/ucov/repro/jsoup/Clients/dayeaha/moviefan
git clone --depth 1 https://github.com/Akhil-Samineni/FlightPricesTracker.git /data/ucov/repro/jsoup/Clients/Akhil-Samineni/FlightPricesTracker
git clone --depth 1 https://github.com/AbdulkareemAliu/SudokuSuggest.git /data/ucov/repro/jsoup/Clients/AbdulkareemAliu/SudokuSuggest
git clone --depth 1 https://github.com/jensdietrich/xshady.git /data/ucov/repro/jsoup/Clients/jensdietrich/xshady
git clone --depth 1 https://github.com/zmoony/multi-util.git /data/ucov/repro/jsoup/Clients/zmoony/multi-util
git clone --depth 1 https://github.com/yanghuaiGit/hadooplaab.git /data/ucov/repro/jsoup/Clients/yanghuaiGit/hadooplaab
git clone --depth 1 https://github.com/tchuno/projeto-tcc.git /data/ucov/repro/jsoup/Clients/tchuno/projeto-tcc
git clone --depth 1 https://github.com/alohahawaii1004/NEW_LMS.git /data/ucov/repro/jsoup/Clients/alohahawaii1004/NEW_LMS
git clone --depth 1 https://github.com/ck7526296/tiktok-api.git /data/ucov/repro/jsoup/Clients/ck7526296/tiktok-api
git clone --depth 1 https://github.com/TeamLeadder/WebGoat-DevOps.git /data/ucov/repro/jsoup/Clients/TeamLeadder/WebGoat-DevOps
git clone --depth 1 https://github.com/LapTopLT/taogeSearch.git /data/ucov/repro/jsoup/Clients/LapTopLT/taogeSearch
git clone --depth 1 https://github.com/jini67/web.git /data/ucov/repro/jsoup/Clients/jini67/web
git clone --depth 1 https://github.com/wittyphantom333/SkarsisOSRS.git /data/ucov/repro/jsoup/Clients/wittyphantom333/SkarsisOSRS
git clone --depth 1 https://github.com/UrosKastel/WebGoat.git /data/ucov/repro/jsoup/Clients/UrosKastel/WebGoat
git clone --depth 1 https://github.com/shergazievdanred/test-api-parser.git /data/ucov/repro/jsoup/Clients/shergazievdanred/test-api-parser
git clone --depth 1 https://github.com/Sumy-Coding/atlas-rest-client-groovy.git /data/ucov/repro/jsoup/Clients/Sumy-Coding/atlas-rest-client-groovy
git clone --depth 1 https://github.com/Fresh-Coding/student-app.git /data/ucov/repro/jsoup/Clients/Fresh-Coding/student-app
git clone --depth 1 https://github.com/HeChuangJun/springcloud-demo.git /data/ucov/repro/jsoup/Clients/HeChuangJun/springcloud-demo
git clone --depth 1 https://github.com/KINGxhao/Online-Test-System.github.io.git /data/ucov/repro/jsoup/Clients/KINGxhao/Online-Test-System.github.io
git clone --depth 1 https://github.com/EvgeniyGal/TelegramBot.git /data/ucov/repro/jsoup/Clients/EvgeniyGal/TelegramBot
git clone --depth 1 https://github.com/smeligrana/amazon-buybox.git /data/ucov/repro/jsoup/Clients/smeligrana/amazon-buybox
git clone --depth 1 https://github.com/llyyzzs/cloud-bcyy.git /data/ucov/repro/jsoup/Clients/llyyzzs/cloud-bcyy
git clone --depth 1 https://github.com/libo-create/sephora-aisa-china.git /data/ucov/repro/jsoup/Clients/libo-create/sephora-aisa-china
git clone --depth 1 https://github.com/aviyan7/networkProgramming.git /data/ucov/repro/jsoup/Clients/aviyan7/networkProgramming
