git clone --depth 1 https://github.com/Tiefkuehlpizze/OABXDecrypt.git /data/ucov/repro/commons-cli/Clients/Tiefkuehlpizze/OABXDecrypt
git clone --depth 1 https://github.com/weihsin2002/IBQuantTrade.git /data/ucov/repro/commons-cli/Clients/weihsin2002/IBQuantTrade
git clone --depth 1 https://github.com/tnapat2000/ZorkArtOnline.git /data/ucov/repro/commons-cli/Clients/tnapat2000/ZorkArtOnline
git clone --depth 1 https://github.com/safrant/robot.git /data/ucov/repro/commons-cli/Clients/safrant/robot
git clone --depth 1 https://github.com/renjieliu/raspberrypi.git /data/ucov/repro/commons-cli/Clients/renjieliu/raspberrypi
git clone --depth 1 https://github.com/flpfraga/Solid-UseCase-DesbravandoSolid.git /data/ucov/repro/commons-cli/Clients/flpfraga/Solid-UseCase-DesbravandoSolid
git clone --depth 1 https://github.com/caoluobin/rocketmq-4.8.git /data/ucov/repro/commons-cli/Clients/caoluobin/rocketmq-4.8
git clone --depth 1 https://github.com/orbisgis/framework.git /data/ucov/repro/commons-cli/Clients/orbisgis/framework
git clone --depth 1 https://github.com/marrodoso/Acme-Jobs.git /data/ucov/repro/commons-cli/Clients/marrodoso/Acme-Jobs
git clone --depth 1 https://github.com/orgTestCodacy11KRepos110MB/repo-9310-metron.git /data/ucov/repro/commons-cli/Clients/orgTestCodacy11KRepos110MB/repo-9310-metron
git clone --depth 1 https://github.com/SimonHofmeister1992/HSP-Project-AlphaZero-Reversi.git /data/ucov/repro/commons-cli/Clients/SimonHofmeister1992/HSP-Project-AlphaZero-Reversi
git clone --depth 1 https://github.com/paul-huber1999/Paul_thesis2022.git /data/ucov/repro/commons-cli/Clients/paul-huber1999/Paul_thesis2022
git clone --depth 1 https://github.com/archangelproject/JDreamsKit.git /data/ucov/repro/commons-cli/Clients/archangelproject/JDreamsKit
git clone --depth 1 https://github.com/carol233/SDKUpdateMining.git /data/ucov/repro/commons-cli/Clients/carol233/SDKUpdateMining
git clone --depth 1 https://github.com/LionelBK/libreplanSoapui.git /data/ucov/repro/commons-cli/Clients/LionelBK/libreplanSoapui
git clone --depth 1 https://github.com/lukoou3/flink-1.12-source.git /data/ucov/repro/commons-cli/Clients/lukoou3/flink-1.12-source
git clone --depth 1 https://github.com/Shoulaxiao/zookeeper-.git /data/ucov/repro/commons-cli/Clients/Shoulaxiao/zookeeper-
git clone --depth 1 https://github.com/jexxa-projects/JexxaTutorials.git /data/ucov/repro/commons-cli/Clients/jexxa-projects/JexxaTutorials
git clone --depth 1 https://github.com/bsamarnath/testamar1.git /data/ucov/repro/commons-cli/Clients/bsamarnath/testamar1
git clone --depth 1 https://github.com/sa-group-yzz/SQLAnalysis.git /data/ucov/repro/commons-cli/Clients/sa-group-yzz/SQLAnalysis
git clone --depth 1 https://github.com/gn20018/GradesUTP.git /data/ucov/repro/commons-cli/Clients/gn20018/GradesUTP
git clone --depth 1 https://github.com/maribelrb22/Acme-One.git /data/ucov/repro/commons-cli/Clients/maribelrb22/Acme-One
git clone --depth 1 https://github.com/shannah/jdeploy.git /data/ucov/repro/commons-cli/Clients/shannah/jdeploy
git clone --depth 1 https://github.com/WinterSilence/swagger-codegen.git /data/ucov/repro/commons-cli/Clients/WinterSilence/swagger-codegen
git clone --depth 1 https://github.com/CyberFlameGO/OpenTripPlanner.git /data/ucov/repro/commons-cli/Clients/CyberFlameGO/OpenTripPlanner
git clone --depth 1 https://github.com/fasten-project/incremental-maven-crawler.git /data/ucov/repro/commons-cli/Clients/fasten-project/incremental-maven-crawler
git clone --depth 1 https://github.com/samq-ghdemo/hadoop.git /data/ucov/repro/commons-cli/Clients/samq-ghdemo/hadoop
git clone --depth 1 https://github.com/alibenmessaoud/JSF-Application-that-uses-managed-bean-and-ejb.git /data/ucov/repro/commons-cli/Clients/alibenmessaoud/JSF-Application-that-uses-managed-bean-and-ejb
git clone --depth 1 https://github.com/ekmixon/nifi.git /data/ucov/repro/commons-cli/Clients/ekmixon/nifi
git clone --depth 1 https://github.com/dd-test5/ripme.git /data/ucov/repro/commons-cli/Clients/dd-test5/ripme
git clone --depth 1 https://github.com/FDSInfoMontp-HAI916I-GLIA/TP1.git /data/ucov/repro/commons-cli/Clients/FDSInfoMontp-HAI916I-GLIA/TP1
git clone --depth 1 https://github.com/google/infra-structured-map.git /data/ucov/repro/commons-cli/Clients/google/infra-structured-map
git clone --depth 1 https://github.com/Rindadevi/apachetomcat.git /data/ucov/repro/commons-cli/Clients/Rindadevi/apachetomcat
git clone --depth 1 https://github.com/todd-fritz/ldap_in_memory.git /data/ucov/repro/commons-cli/Clients/todd-fritz/ldap_in_memory
git clone --depth 1 https://github.com/zhining-lu/netty-quic-proxy.git /data/ucov/repro/commons-cli/Clients/zhining-lu/netty-quic-proxy
git clone --depth 1 https://github.com/SeppPenner/openapi-generator.git /data/ucov/repro/commons-cli/Clients/SeppPenner/openapi-generator
git clone --depth 1 https://github.com/ruofanxing/webmagic.git /data/ucov/repro/commons-cli/Clients/ruofanxing/webmagic
git clone --depth 1 https://github.com/qitianfeng/rocketmq-new.git /data/ucov/repro/commons-cli/Clients/qitianfeng/rocketmq-new
git clone --depth 1 https://github.com/hata6502/verilog-format.git /data/ucov/repro/commons-cli/Clients/hata6502/verilog-format
git clone --depth 1 https://github.com/isaaceindhoven/swagger-docgen.git /data/ucov/repro/commons-cli/Clients/isaaceindhoven/swagger-docgen
git clone --depth 1 https://github.com/harshaputtaswamy/aai-common.git /data/ucov/repro/commons-cli/Clients/harshaputtaswamy/aai-common
git clone --depth 1 https://github.com/tkcmada/athena-kdb3.git /data/ucov/repro/commons-cli/Clients/tkcmada/athena-kdb3
git clone --depth 1 https://github.com/FedorBelyakoff/CabdiagFormatter.git /data/ucov/repro/commons-cli/Clients/FedorBelyakoff/CabdiagFormatter
git clone --depth 1 https://github.com/xwzl/nacos.git /data/ucov/repro/commons-cli/Clients/xwzl/nacos
git clone --depth 1 https://github.com/Indhumathi397/Bills2U_TestNG_Updated.git /data/ucov/repro/commons-cli/Clients/Indhumathi397/Bills2U_TestNG_Updated
git clone --depth 1 https://github.com/2lambda123/odc.git /data/ucov/repro/commons-cli/Clients/2lambda123/odc
git clone --depth 1 https://github.com/adfwer233/ThssDB.git /data/ucov/repro/commons-cli/Clients/adfwer233/ThssDB
git clone --depth 1 https://github.com/ep-infosec/33_apache_druid.git /data/ucov/repro/commons-cli/Clients/ep-infosec/33_apache_druid
git clone --depth 1 https://github.com/avineshwar/tutorials.git /data/ucov/repro/commons-cli/Clients/avineshwar/tutorials
git clone --depth 1 https://github.com/vaginessa/uber-apk-signer.git /data/ucov/repro/commons-cli/Clients/vaginessa/uber-apk-signer
git clone --depth 1 https://github.com/miven/nlp4.git /data/ucov/repro/commons-cli/Clients/miven/nlp4
git clone --depth 1 https://github.com/bbrk364/ha-nva.git /data/ucov/repro/commons-cli/Clients/bbrk364/ha-nva
git clone --depth 1 https://github.com/dwu/schema-compatibility.git /data/ucov/repro/commons-cli/Clients/dwu/schema-compatibility
git clone --depth 1 https://github.com/changjinjin/woven-dsp.git /data/ucov/repro/commons-cli/Clients/changjinjin/woven-dsp
git clone --depth 1 https://github.com/Techatonic/Sudoku.git /data/ucov/repro/commons-cli/Clients/Techatonic/Sudoku
git clone --depth 1 https://github.com/malomarrec/openapi-generator.git /data/ucov/repro/commons-cli/Clients/malomarrec/openapi-generator
git clone --depth 1 https://github.com/hellokwmin/apollo.git /data/ucov/repro/commons-cli/Clients/hellokwmin/apollo
git clone --depth 1 https://github.com/kamaux0r/athenz.git /data/ucov/repro/commons-cli/Clients/kamaux0r/athenz
git clone --depth 1 https://github.com/qbox/spark-1.git /data/ucov/repro/commons-cli/Clients/qbox/spark-1
git clone --depth 1 https://github.com/yolee20/fabric-sdk-java.git /data/ucov/repro/commons-cli/Clients/yolee20/fabric-sdk-java
git clone --depth 1 https://github.com/pl89/bootstrap-simulation.git /data/ucov/repro/commons-cli/Clients/pl89/bootstrap-simulation
git clone --depth 1 https://github.com/AngeloFerrando/3-valuedSL.git /data/ucov/repro/commons-cli/Clients/AngeloFerrando/3-valuedSL
git clone --depth 1 https://github.com/aerogear/ups-mock-data-loader.git /data/ucov/repro/commons-cli/Clients/aerogear/ups-mock-data-loader
git clone --depth 1 https://github.com/jeromgonch/job_test_task_telnet_server.git /data/ucov/repro/commons-cli/Clients/jeromgonch/job_test_task_telnet_server
git clone --depth 1 https://github.com/JoKrus/j-chess-server.git /data/ucov/repro/commons-cli/Clients/JoKrus/j-chess-server
git clone --depth 1 https://github.com/dicastro/financemanager.git /data/ucov/repro/commons-cli/Clients/dicastro/financemanager
git clone --depth 1 https://github.com/banxue-dev/bxmall-backend.git /data/ucov/repro/commons-cli/Clients/banxue-dev/bxmall-backend
git clone --depth 1 https://github.com/fagnercandido/pocquinha-strategy-factory-supplier.git /data/ucov/repro/commons-cli/Clients/fagnercandido/pocquinha-strategy-factory-supplier
git clone --depth 1 https://github.com/apigee/usergrid-benchmark.git /data/ucov/repro/commons-cli/Clients/apigee/usergrid-benchmark
git clone --depth 1 https://github.com/Jesperoka/AISTRE-labs.git /data/ucov/repro/commons-cli/Clients/Jesperoka/AISTRE-labs
git clone --depth 1 https://github.com/flink-extended/flink-remote-shuffle.git /data/ucov/repro/commons-cli/Clients/flink-extended/flink-remote-shuffle
git clone --depth 1 https://github.com/BrotherCao/MYDB.git /data/ucov/repro/commons-cli/Clients/BrotherCao/MYDB
git clone --depth 1 https://github.com/MilanPodunavac/IZ-Projekat.git /data/ucov/repro/commons-cli/Clients/MilanPodunavac/IZ-Projekat
git clone --depth 1 https://github.com/FelixDes/SimpleServletContainer.git /data/ucov/repro/commons-cli/Clients/FelixDes/SimpleServletContainer
git clone --depth 1 https://github.com/smakesoska1/Application_for_Kindergarden.git /data/ucov/repro/commons-cli/Clients/smakesoska1/Application_for_Kindergarden
git clone --depth 1 https://github.com/chandnigit/Demo202022.git /data/ucov/repro/commons-cli/Clients/chandnigit/Demo202022
git clone --depth 1 https://github.com/UIC-InDeXLab/CoverageICDE.git /data/ucov/repro/commons-cli/Clients/UIC-InDeXLab/CoverageICDE
git clone --depth 1 https://github.com/Reshape-skew-handle/reshape-on-flink.git /data/ucov/repro/commons-cli/Clients/Reshape-skew-handle/reshape-on-flink
git clone --depth 1 https://github.com/senzhu/fNet.git /data/ucov/repro/commons-cli/Clients/senzhu/fNet
git clone --depth 1 https://github.com/15Ibans/MinecraftLogSearcher.git /data/ucov/repro/commons-cli/Clients/15Ibans/MinecraftLogSearcher
git clone --depth 1 https://github.com/chakaiduany/gcptraining.git /data/ucov/repro/commons-cli/Clients/chakaiduany/gcptraining
git clone --depth 1 https://github.com/mathieu-dossantos/TD-Sudoku.git /data/ucov/repro/commons-cli/Clients/mathieu-dossantos/TD-Sudoku
git clone --depth 1 https://github.com/wrote-code/my-utils.git /data/ucov/repro/commons-cli/Clients/wrote-code/my-utils
git clone --depth 1 https://github.com/glycoinfo/GlycanFormatConverter-cli.git /data/ucov/repro/commons-cli/Clients/glycoinfo/GlycanFormatConverter-cli
git clone --depth 1 https://github.com/VietAnh1508/boost-up-program-hands-on-lab.git /data/ucov/repro/commons-cli/Clients/VietAnh1508/boost-up-program-hands-on-lab
git clone --depth 1 https://github.com/LuKasMitK/OpenTripPlanner.git /data/ucov/repro/commons-cli/Clients/LuKasMitK/OpenTripPlanner
git clone --depth 1 https://github.com/rohankumardubey/nitmproxy.git /data/ucov/repro/commons-cli/Clients/rohankumardubey/nitmproxy
git clone --depth 1 https://github.com/hehuiyuan/pravegatest.git /data/ucov/repro/commons-cli/Clients/hehuiyuan/pravegatest
git clone --depth 1 https://github.com/smurf667/qrio.git /data/ucov/repro/commons-cli/Clients/smurf667/qrio
git clone --depth 1 https://github.com/ttqs5/alibabacloud-hologres-connectors.git /data/ucov/repro/commons-cli/Clients/ttqs5/alibabacloud-hologres-connectors
git clone --depth 1 https://github.com/gearsofcode-tech/andromda.git /data/ucov/repro/commons-cli/Clients/gearsofcode-tech/andromda
git clone --depth 1 https://github.com/JamesAreuming/PosManager.git /data/ucov/repro/commons-cli/Clients/JamesAreuming/PosManager
git clone --depth 1 https://github.com/chlustanec/trial.git /data/ucov/repro/commons-cli/Clients/chlustanec/trial
git clone --depth 1 https://github.com/janothan/invalid-url-check.git /data/ucov/repro/commons-cli/Clients/janothan/invalid-url-check
git clone --depth 1 https://github.com/eschult2001/wso2-synapse.git /data/ucov/repro/commons-cli/Clients/eschult2001/wso2-synapse
git clone --depth 1 https://github.com/ShadiaBaroud/sh.git /data/ucov/repro/commons-cli/Clients/ShadiaBaroud/sh
git clone --depth 1 https://github.com/Projet-annuel-3AL2/organization-app.git /data/ucov/repro/commons-cli/Clients/Projet-annuel-3AL2/organization-app
git clone --depth 1 https://github.com/kunterbunt2/song.master.git /data/ucov/repro/commons-cli/Clients/kunterbunt2/song.master
git clone --depth 1 https://github.com/ghas-results/imhotep-builder-jira.git /data/ucov/repro/commons-cli/Clients/ghas-results/imhotep-builder-jira
git clone --depth 1 https://github.com/afarago/SLCEE-2023-PC.git /data/ucov/repro/commons-cli/Clients/afarago/SLCEE-2023-PC
git clone --depth 1 https://github.com/gaetronik/openapi-generator.git /data/ucov/repro/commons-cli/Clients/gaetronik/openapi-generator
git clone --depth 1 https://github.com/thosakwe/calclang_old.git /data/ucov/repro/commons-cli/Clients/thosakwe/calclang_old
git clone --depth 1 https://github.com/BeeInIT/smartstadium.git /data/ucov/repro/commons-cli/Clients/BeeInIT/smartstadium
git clone --depth 1 https://github.com/tbee/xml2xxx.git /data/ucov/repro/commons-cli/Clients/tbee/xml2xxx
git clone --depth 1 https://github.com/CharafeddineMechalikh/recap.git /data/ucov/repro/commons-cli/Clients/CharafeddineMechalikh/recap
git clone --depth 1 https://github.com/mohit9494/kafka-spark-streaming.git /data/ucov/repro/commons-cli/Clients/mohit9494/kafka-spark-streaming
git clone --depth 1 https://github.com/GiorgosMandi/ER-Algorithms.git /data/ucov/repro/commons-cli/Clients/GiorgosMandi/ER-Algorithms
git clone --depth 1 https://github.com/sunchengxuanivy/flink-gcs.git /data/ucov/repro/commons-cli/Clients/sunchengxuanivy/flink-gcs
git clone --depth 1 https://github.com/lgc523/infra-java.git /data/ucov/repro/commons-cli/Clients/lgc523/infra-java
git clone --depth 1 https://github.com/hsbugreports/zookeeper_test.git /data/ucov/repro/commons-cli/Clients/hsbugreports/zookeeper_test
git clone --depth 1 https://github.com/phaqueue/nfview2.git /data/ucov/repro/commons-cli/Clients/phaqueue/nfview2
git clone --depth 1 https://github.com/xuechun-fan/SpringFramework.git /data/ucov/repro/commons-cli/Clients/xuechun-fan/SpringFramework
git clone --depth 1 https://github.com/prabhagaranks/pinot-0.12.0.git /data/ucov/repro/commons-cli/Clients/prabhagaranks/pinot-0.12.0
git clone --depth 1 https://github.com/ZP315/flink-1.14.4-source-analysis.git /data/ucov/repro/commons-cli/Clients/ZP315/flink-1.14.4-source-analysis
git clone --depth 1 https://github.com/roothorp/sdktest.git /data/ucov/repro/commons-cli/Clients/roothorp/sdktest
git clone --depth 1 https://github.com/leberzy/rocketmq-sub.git /data/ucov/repro/commons-cli/Clients/leberzy/rocketmq-sub
git clone --depth 1 https://github.com/fanyi-zhao/COLA.git /data/ucov/repro/commons-cli/Clients/fanyi-zhao/COLA
git clone --depth 1 https://github.com/cnxtech/amazon-neptune-gremlin-java-sigv4.git /data/ucov/repro/commons-cli/Clients/cnxtech/amazon-neptune-gremlin-java-sigv4
git clone --depth 1 https://github.com/shrumit/timetable-scraper-java.git /data/ucov/repro/commons-cli/Clients/shrumit/timetable-scraper-java
git clone --depth 1 https://github.com/stgztsw/datax.git /data/ucov/repro/commons-cli/Clients/stgztsw/datax
git clone --depth 1 https://github.com/letterkey/spark.git /data/ucov/repro/commons-cli/Clients/letterkey/spark
git clone --depth 1 https://github.com/ic-xu/octopus-parent.git /data/ucov/repro/commons-cli/Clients/ic-xu/octopus-parent
git clone --depth 1 https://github.com/GuilhermeMunizReis/ADS_GuilhermeMuniz.git /data/ucov/repro/commons-cli/Clients/GuilhermeMunizReis/ADS_GuilhermeMuniz
git clone --depth 1 https://github.com/gus-gu/sample-project.git /data/ucov/repro/commons-cli/Clients/gus-gu/sample-project
git clone --depth 1 https://github.com/teddywing/pdf-form-replace-font2.git /data/ucov/repro/commons-cli/Clients/teddywing/pdf-form-replace-font2
git clone --depth 1 https://github.com/badlocale/HashSnail-Server.git /data/ucov/repro/commons-cli/Clients/badlocale/HashSnail-Server
git clone --depth 1 https://github.com/crotwell/recFunc.git /data/ucov/repro/commons-cli/Clients/crotwell/recFunc
git clone --depth 1 https://github.com/mohamednizar/zookeeper.git /data/ucov/repro/commons-cli/Clients/mohamednizar/zookeeper
git clone --depth 1 https://github.com/Andriivyn/ParrallelProgrammingMPI.git /data/ucov/repro/commons-cli/Clients/Andriivyn/ParrallelProgrammingMPI
git clone --depth 1 https://github.com/Krishna168/urban-disco.git /data/ucov/repro/commons-cli/Clients/Krishna168/urban-disco
git clone --depth 1 https://github.com/SebLuca/SI_TEST_changbranch.git /data/ucov/repro/commons-cli/Clients/SebLuca/SI_TEST_changbranch
git clone --depth 1 https://github.com/SangJin23/HTML-CSS-.git /data/ucov/repro/commons-cli/Clients/SangJin23/HTML-CSS-
git clone --depth 1 https://github.com/hass123uk/TermIndexer.git /data/ucov/repro/commons-cli/Clients/hass123uk/TermIndexer
git clone --depth 1 https://github.com/chovy-3012/hdp-hive-release.git /data/ucov/repro/commons-cli/Clients/chovy-3012/hdp-hive-release
git clone --depth 1 https://github.com/MAG1412/maven1.git /data/ucov/repro/commons-cli/Clients/MAG1412/maven1
git clone --depth 1 https://github.com/LabsRS-Ref/MSEC.git /data/ucov/repro/commons-cli/Clients/LabsRS-Ref/MSEC
git clone --depth 1 https://github.com/sodacan-net/sodacan-cli.git /data/ucov/repro/commons-cli/Clients/sodacan-net/sodacan-cli
git clone --depth 1 https://github.com/jainsourabh2/googlecloudplatform.git /data/ucov/repro/commons-cli/Clients/jainsourabh2/googlecloudplatform
git clone --depth 1 https://github.com/boost-entropy-gcp/jarvis.git /data/ucov/repro/commons-cli/Clients/boost-entropy-gcp/jarvis
git clone --depth 1 https://github.com/tudelft-cda-lab/SymLoop.git /data/ucov/repro/commons-cli/Clients/tudelft-cda-lab/SymLoop
git clone --depth 1 https://github.com/TOSIT-IO/hadoop-old.git /data/ucov/repro/commons-cli/Clients/TOSIT-IO/hadoop-old
git clone --depth 1 https://github.com/sudoviz/openrasp.git /data/ucov/repro/commons-cli/Clients/sudoviz/openrasp
git clone --depth 1 https://github.com/ace-lectures/2aa4-polymorphism-mesh.git /data/ucov/repro/commons-cli/Clients/ace-lectures/2aa4-polymorphism-mesh
git clone --depth 1 https://github.com/psekowsk/SeleniumWebDriverJAVA.git /data/ucov/repro/commons-cli/Clients/psekowsk/SeleniumWebDriverJAVA
git clone --depth 1 https://github.com/atmSuper/vue.git /data/ucov/repro/commons-cli/Clients/atmSuper/vue
git clone --depth 1 https://github.com/RoyFly/ppfly-module-demo.git /data/ucov/repro/commons-cli/Clients/RoyFly/ppfly-module-demo
git clone --depth 1 https://github.com/ep-infosec/33_apache_incubator-streampark.git /data/ucov/repro/commons-cli/Clients/ep-infosec/33_apache_incubator-streampark
git clone --depth 1 https://github.com/AgrShashank/SSPPractiseCodes.git /data/ucov/repro/commons-cli/Clients/AgrShashank/SSPPractiseCodes
git clone --depth 1 https://github.com/dcmsy/eyecool-mirco-service-web.git /data/ucov/repro/commons-cli/Clients/dcmsy/eyecool-mirco-service-web
git clone --depth 1 https://github.com/amith123456/am1.git /data/ucov/repro/commons-cli/Clients/amith123456/am1
git clone --depth 1 https://github.com/gooddata/GoodData-CL.git /data/ucov/repro/commons-cli/Clients/gooddata/GoodData-CL
git clone --depth 1 https://github.com/Rajiv-Edulapuram/tutorials.git /data/ucov/repro/commons-cli/Clients/Rajiv-Edulapuram/tutorials
git clone --depth 1 https://github.com/ZacWolf/com.zacwolf.commons.crypto.git /data/ucov/repro/commons-cli/Clients/ZacWolf/com.zacwolf.commons.crypto
git clone --depth 1 https://github.com/mirkobaffo/progetto2_bookkeeper_test.git /data/ucov/repro/commons-cli/Clients/mirkobaffo/progetto2_bookkeeper_test
git clone --depth 1 https://github.com/ducanh170920/test-nifi.git /data/ucov/repro/commons-cli/Clients/ducanh170920/test-nifi
git clone --depth 1 https://github.com/tedwon/rhq.git /data/ucov/repro/commons-cli/Clients/tedwon/rhq
git clone --depth 1 https://github.com/danmarsua1/Acme-Courses-D04.git /data/ucov/repro/commons-cli/Clients/danmarsua1/Acme-Courses-D04
git clone --depth 1 https://github.com/lujunfa/nacos_review.git /data/ucov/repro/commons-cli/Clients/lujunfa/nacos_review
git clone --depth 1 https://github.com/DiegoHorrilloDuran/Acme-Work-Plans-D03.git /data/ucov/repro/commons-cli/Clients/DiegoHorrilloDuran/Acme-Work-Plans-D03
git clone --depth 1 https://github.com/friskluft/benchmarks.git /data/ucov/repro/commons-cli/Clients/friskluft/benchmarks
git clone --depth 1 https://github.com/cvlucian/threadfix.git /data/ucov/repro/commons-cli/Clients/cvlucian/threadfix
git clone --depth 1 https://github.com/don-the-data-guy/DataAssetStream.git /data/ucov/repro/commons-cli/Clients/don-the-data-guy/DataAssetStream
git clone --depth 1 https://github.com/sjoerdboerhout/Prova.git /data/ucov/repro/commons-cli/Clients/sjoerdboerhout/Prova
git clone --depth 1 https://github.com/Sonja-Parabucki/biblioteka.git /data/ucov/repro/commons-cli/Clients/Sonja-Parabucki/biblioteka
git clone --depth 1 https://github.com/sjtu-sail/ops-hadoop.git /data/ucov/repro/commons-cli/Clients/sjtu-sail/ops-hadoop
git clone --depth 1 https://github.com/sohailzahid/web-log-parser.git /data/ucov/repro/commons-cli/Clients/sohailzahid/web-log-parser
git clone --depth 1 https://github.com/apache/incubator-uniffle.git /data/ucov/repro/commons-cli/Clients/apache/incubator-uniffle
git clone --depth 1 https://github.com/mitchamador/volksroutenrechner-journal.git /data/ucov/repro/commons-cli/Clients/mitchamador/volksroutenrechner-journal
git clone --depth 1 https://github.com/SuJingyu111/flink_simplified_cached.git /data/ucov/repro/commons-cli/Clients/SuJingyu111/flink_simplified_cached
git clone --depth 1 https://github.com/Blooof/Mks2MqttReporter.git /data/ucov/repro/commons-cli/Clients/Blooof/Mks2MqttReporter
git clone --depth 1 https://github.com/joshlong-attic/podcast-production-pipeline-shell.git /data/ucov/repro/commons-cli/Clients/joshlong-attic/podcast-production-pipeline-shell
git clone --depth 1 https://github.com/AMARJOLLET/Myfirstsoaptest.git /data/ucov/repro/commons-cli/Clients/AMARJOLLET/Myfirstsoaptest
git clone --depth 1 https://github.com/nicobritos/uni-ss-tp1-2021q1.git /data/ucov/repro/commons-cli/Clients/nicobritos/uni-ss-tp1-2021q1
git clone --depth 1 https://github.com/numberly/avro.git /data/ucov/repro/commons-cli/Clients/numberly/avro
git clone --depth 1 https://github.com/Dimonium-239/ElevatorSystem.git /data/ucov/repro/commons-cli/Clients/Dimonium-239/ElevatorSystem
git clone --depth 1 https://github.com/ValeriaFasciana/ingsw2022-AM02.git /data/ucov/repro/commons-cli/Clients/ValeriaFasciana/ingsw2022-AM02
git clone --depth 1 https://github.com/venugrk/shared.git /data/ucov/repro/commons-cli/Clients/venugrk/shared
git clone --depth 1 https://github.com/winnedatsch/wu-bachelor-thesis.git /data/ucov/repro/commons-cli/Clients/winnedatsch/wu-bachelor-thesis
git clone --depth 1 https://github.com/ASSERT-KTH/collector-sahab-experiments.git /data/ucov/repro/commons-cli/Clients/ASSERT-KTH/collector-sahab-experiments
git clone --depth 1 https://github.com/AanshKot/IslandandCityGenerator.git /data/ucov/repro/commons-cli/Clients/AanshKot/IslandandCityGenerator
git clone --depth 1 https://github.com/mahmutovichana/Hotel-Reservations-App.git /data/ucov/repro/commons-cli/Clients/mahmutovichana/Hotel-Reservations-App
git clone --depth 1 https://github.com/sskmscss/um-service.git /data/ucov/repro/commons-cli/Clients/sskmscss/um-service
git clone --depth 1 https://github.com/wujiangchao/open-mq.git /data/ucov/repro/commons-cli/Clients/wujiangchao/open-mq
git clone --depth 1 https://github.com/gitgoose/core-spring-demos.git /data/ucov/repro/commons-cli/Clients/gitgoose/core-spring-demos
git clone --depth 1 https://github.com/cytest2021/IDEA_maven_test.git /data/ucov/repro/commons-cli/Clients/cytest2021/IDEA_maven_test
git clone --depth 1 https://github.com/norrishuang/Hades-Z-V3.git /data/ucov/repro/commons-cli/Clients/norrishuang/Hades-Z-V3
git clone --depth 1 https://github.com/vaibhav-wagaskar/Java_VSW.git /data/ucov/repro/commons-cli/Clients/vaibhav-wagaskar/Java_VSW
git clone --depth 1 https://github.com/azerotla2/thumbtack_online_school.git /data/ucov/repro/commons-cli/Clients/azerotla2/thumbtack_online_school
git clone --depth 1 https://github.com/SamKenX-Hub-Community/SAMkenxGraphScope.git /data/ucov/repro/commons-cli/Clients/SamKenX-Hub-Community/SAMkenxGraphScope
git clone --depth 1 https://github.com/TheNinjask/Project-Euler.git /data/ucov/repro/commons-cli/Clients/TheNinjask/Project-Euler
git clone --depth 1 https://github.com/maxiplux/tutorials.git /data/ucov/repro/commons-cli/Clients/maxiplux/tutorials
git clone --depth 1 https://github.com/IEEE-TritonsRCSC/robocup-2023.git /data/ucov/repro/commons-cli/Clients/IEEE-TritonsRCSC/robocup-2023
git clone --depth 1 https://github.com/JaesangPark/test.git /data/ucov/repro/commons-cli/Clients/JaesangPark/test
git clone --depth 1 https://github.com/fengjx/java-hot-reload-agent.git /data/ucov/repro/commons-cli/Clients/fengjx/java-hot-reload-agent
git clone --depth 1 https://github.com/edgallojr/igti-edc-mod2.git /data/ucov/repro/commons-cli/Clients/edgallojr/igti-edc-mod2
git clone --depth 1 https://github.com/nhnacademy-1st-gj/network-programming.git /data/ucov/repro/commons-cli/Clients/nhnacademy-1st-gj/network-programming
git clone --depth 1 https://github.com/artnaseef/opennms-poc-hs1384.git /data/ucov/repro/commons-cli/Clients/artnaseef/opennms-poc-hs1384
git clone --depth 1 https://github.com/RoyAl-Vitamin/Lab6.git /data/ucov/repro/commons-cli/Clients/RoyAl-Vitamin/Lab6
git clone --depth 1 https://github.com/maeda6uiui/BD1ToOBJ.git /data/ucov/repro/commons-cli/Clients/maeda6uiui/BD1ToOBJ
git clone --depth 1 https://github.com/danielgraf/javaemvreader.git /data/ucov/repro/commons-cli/Clients/danielgraf/javaemvreader
git clone --depth 1 https://github.com/dreamcloudapp/esa-wiki.git /data/ucov/repro/commons-cli/Clients/dreamcloudapp/esa-wiki
git clone --depth 1 https://github.com/xiaonuobase/Snowy-Cloud.git /data/ucov/repro/commons-cli/Clients/xiaonuobase/Snowy-Cloud
git clone --depth 1 https://github.com/dantefung/Sauron-Codebase.git /data/ucov/repro/commons-cli/Clients/dantefung/Sauron-Codebase
git clone --depth 1 https://github.com/salesforce-misc/perfGenie.git /data/ucov/repro/commons-cli/Clients/salesforce-misc/perfGenie
git clone --depth 1 https://github.com/juriel/jdbc-sql-console.git /data/ucov/repro/commons-cli/Clients/juriel/jdbc-sql-console
git clone --depth 1 https://github.com/i2shouxihu/webmagic-develop.git /data/ucov/repro/commons-cli/Clients/i2shouxihu/webmagic-develop
git clone --depth 1 https://github.com/jfontestad/deid_a.git /data/ucov/repro/commons-cli/Clients/jfontestad/deid_a
git clone --depth 1 https://github.com/sincere0104/flink-1.12.0.git /data/ucov/repro/commons-cli/Clients/sincere0104/flink-1.12.0
git clone --depth 1 https://github.com/marendtz/Heritrix3_crawler.git /data/ucov/repro/commons-cli/Clients/marendtz/Heritrix3_crawler
git clone --depth 1 https://github.com/vithyatith/SonicCellFX.git /data/ucov/repro/commons-cli/Clients/vithyatith/SonicCellFX
git clone --depth 1 https://github.com/p506/gapic-generator.git /data/ucov/repro/commons-cli/Clients/p506/gapic-generator
git clone --depth 1 https://github.com/acorbin3/P3achB0t.git /data/ucov/repro/commons-cli/Clients/acorbin3/P3achB0t
git clone --depth 1 https://github.com/mayinrain/linkis-temp.git /data/ucov/repro/commons-cli/Clients/mayinrain/linkis-temp
git clone --depth 1 https://github.com/dragonken/yajhfc-gnu-hylafax.git /data/ucov/repro/commons-cli/Clients/dragonken/yajhfc-gnu-hylafax
git clone --depth 1 https://github.com/OpenGovDataMirror/D_cityofnewyork_DSpace.git /data/ucov/repro/commons-cli/Clients/OpenGovDataMirror/D_cityofnewyork_DSpace
git clone --depth 1 https://github.com/alinesno-infrastructure/alinesno-infra-base-fileshow.git /data/ucov/repro/commons-cli/Clients/alinesno-infrastructure/alinesno-infra-base-fileshow
git clone --depth 1 https://github.com/MrHKing/mmqtt.git /data/ucov/repro/commons-cli/Clients/MrHKing/mmqtt
git clone --depth 1 https://github.com/NighterCoder/flink-sql-platform.git /data/ucov/repro/commons-cli/Clients/NighterCoder/flink-sql-platform
git clone --depth 1 https://github.com/Liyajun595/mini-flink.git /data/ucov/repro/commons-cli/Clients/Liyajun595/mini-flink
git clone --depth 1 https://github.com/Liujinan001/hive-3.1.1.git /data/ucov/repro/commons-cli/Clients/Liujinan001/hive-3.1.1
git clone --depth 1 https://github.com/Sheldonsix/spring-geomesa.git /data/ucov/repro/commons-cli/Clients/Sheldonsix/spring-geomesa
git clone --depth 1 https://github.com/xwzl/shardingsphere.git /data/ucov/repro/commons-cli/Clients/xwzl/shardingsphere
git clone --depth 1 https://github.com/zazuko/spatial-indexer.git /data/ucov/repro/commons-cli/Clients/zazuko/spatial-indexer
git clone --depth 1 https://github.com/idrisstouil/TPsudoku.git /data/ucov/repro/commons-cli/Clients/idrisstouil/TPsudoku
git clone --depth 1 https://github.com/IamXGW/MyDB.git /data/ucov/repro/commons-cli/Clients/IamXGW/MyDB
git clone --depth 1 https://github.com/strategist922/JmxClient.git /data/ucov/repro/commons-cli/Clients/strategist922/JmxClient
git clone --depth 1 https://github.com/seanpm2001/SimZonns.git /data/ucov/repro/commons-cli/Clients/seanpm2001/SimZonns
git clone --depth 1 https://github.com/Hanseltu/blog.git /data/ucov/repro/commons-cli/Clients/Hanseltu/blog
git clone --depth 1 https://github.com/Nicolas-Francisco/Massive_Data_Processing.git /data/ucov/repro/commons-cli/Clients/Nicolas-Francisco/Massive_Data_Processing
git clone --depth 1 https://github.com/project-ncl/sbomer.git /data/ucov/repro/commons-cli/Clients/project-ncl/sbomer
git clone --depth 1 https://github.com/Force-oneself/force-rocketmq.git /data/ucov/repro/commons-cli/Clients/Force-oneself/force-rocketmq
git clone --depth 1 https://github.com/Orange-OpenSource/documentare-simdoc.git /data/ucov/repro/commons-cli/Clients/Orange-OpenSource/documentare-simdoc
git clone --depth 1 https://github.com/OlgaBou/MyFirstSoapProject.git /data/ucov/repro/commons-cli/Clients/OlgaBou/MyFirstSoapProject
git clone --depth 1 https://github.com/mhtocs/search-guard.git /data/ucov/repro/commons-cli/Clients/mhtocs/search-guard
git clone --depth 1 https://github.com/OfItinere/ambari-2.7.3.0-139-kylin-v10-Tercel.git /data/ucov/repro/commons-cli/Clients/OfItinere/ambari-2.7.3.0-139-kylin-v10-Tercel
git clone --depth 1 https://github.com/solojin/flowable-6.7.2-annotated.git /data/ucov/repro/commons-cli/Clients/solojin/flowable-6.7.2-annotated
git clone --depth 1 https://github.com/finbourne/lusid-features-java.git /data/ucov/repro/commons-cli/Clients/finbourne/lusid-features-java
git clone --depth 1 https://github.com/karim7262/hadoop3.git /data/ucov/repro/commons-cli/Clients/karim7262/hadoop3
git clone --depth 1 https://github.com/pavanipravallika/newps.git /data/ucov/repro/commons-cli/Clients/pavanipravallika/newps
git clone --depth 1 https://github.com/fengyue-95/nacos-1.1.3-SourceCode.git /data/ucov/repro/commons-cli/Clients/fengyue-95/nacos-1.1.3-SourceCode
git clone --depth 1 https://github.com/yeyhuan/my_datax.git /data/ucov/repro/commons-cli/Clients/yeyhuan/my_datax
git clone --depth 1 https://github.com/DarioMolinaValdes/hugoyaitor.git /data/ucov/repro/commons-cli/Clients/DarioMolinaValdes/hugoyaitor
git clone --depth 1 https://github.com/tylerwest/bingo-simulator.git /data/ucov/repro/commons-cli/Clients/tylerwest/bingo-simulator
git clone --depth 1 https://github.com/colin88/Next_Insurance_Claim_MS.git /data/ucov/repro/commons-cli/Clients/colin88/Next_Insurance_Claim_MS
git clone --depth 1 https://github.com/lucystevens/server-lib.git /data/ucov/repro/commons-cli/Clients/lucystevens/server-lib
git clone --depth 1 https://github.com/JanssenProject/jans.git /data/ucov/repro/commons-cli/Clients/JanssenProject/jans
git clone --depth 1 https://github.com/galuramanboy/cs5260-hw2.git /data/ucov/repro/commons-cli/Clients/galuramanboy/cs5260-hw2
git clone --depth 1 https://github.com/xebialabs-community/xlr-db-copy-tool.git /data/ucov/repro/commons-cli/Clients/xebialabs-community/xlr-db-copy-tool
git clone --depth 1 https://github.com/davalex2003/kpo.git /data/ucov/repro/commons-cli/Clients/davalex2003/kpo
git clone --depth 1 https://github.com/fooblahblah/Hazelblast.git /data/ucov/repro/commons-cli/Clients/fooblahblah/Hazelblast
git clone --depth 1 https://github.com/ghas-results/htl-tck.git /data/ucov/repro/commons-cli/Clients/ghas-results/htl-tck
git clone --depth 1 https://github.com/erngutcon/Acme-Courses-D01.git /data/ucov/repro/commons-cli/Clients/erngutcon/Acme-Courses-D01
git clone --depth 1 https://github.com/alebrixel/CLITool.git /data/ucov/repro/commons-cli/Clients/alebrixel/CLITool
git clone --depth 1 https://github.com/dgfug/incubator-doris.git /data/ucov/repro/commons-cli/Clients/dgfug/incubator-doris
git clone --depth 1 https://github.com/cdk/cdk.git /data/ucov/repro/commons-cli/Clients/cdk/cdk
git clone --depth 1 https://github.com/Daedalus02/eis_project.git /data/ucov/repro/commons-cli/Clients/Daedalus02/eis_project
git clone --depth 1 https://github.com/NoraDing/syringa.git /data/ucov/repro/commons-cli/Clients/NoraDing/syringa
git clone --depth 1 https://github.com/xiaoming12306/doris.git /data/ucov/repro/commons-cli/Clients/xiaoming12306/doris
git clone --depth 1 https://github.com/wangxiutingdychy/AliwareMQj.git /data/ucov/repro/commons-cli/Clients/wangxiutingdychy/AliwareMQj
git clone --depth 1 https://github.com/nigels-com/open-gpstracker.code.git /data/ucov/repro/commons-cli/Clients/nigels-com/open-gpstracker.code
git clone --depth 1 https://github.com/dbbyn/arrow.git /data/ucov/repro/commons-cli/Clients/dbbyn/arrow
git clone --depth 1 https://github.com/automatioexpert/SeleniumDec0320221.git /data/ucov/repro/commons-cli/Clients/automatioexpert/SeleniumDec0320221
git clone --depth 1 https://github.com/xiaoliangliang123/minicloud-tenant.git /data/ucov/repro/commons-cli/Clients/xiaoliangliang123/minicloud-tenant
git clone --depth 1 https://github.com/zzzteph/sheye.git /data/ucov/repro/commons-cli/Clients/zzzteph/sheye
git clone --depth 1 https://github.com/smart-KG/smartKG.git /data/ucov/repro/commons-cli/Clients/smart-KG/smartKG
git clone --depth 1 https://github.com/6si/druid.git /data/ucov/repro/commons-cli/Clients/6si/druid
git clone --depth 1 https://github.com/AaronNGray/storm-crawler-new.git /data/ucov/repro/commons-cli/Clients/AaronNGray/storm-crawler-new
git clone --depth 1 https://github.com/wuchubuzai2018/nacos-multidatasource.git /data/ucov/repro/commons-cli/Clients/wuchubuzai2018/nacos-multidatasource
git clone --depth 1 https://github.com/princeton-nlp/MultilingualAnalysis.git /data/ucov/repro/commons-cli/Clients/princeton-nlp/MultilingualAnalysis
git clone --depth 1 https://github.com/IgorDevR/Terminal_For_Position.git /data/ucov/repro/commons-cli/Clients/IgorDevR/Terminal_For_Position
git clone --depth 1 https://github.com/isaccanedo/java-kafka-streams.git /data/ucov/repro/commons-cli/Clients/isaccanedo/java-kafka-streams
git clone --depth 1 https://github.com/CarrCodes/CPSC531.git /data/ucov/repro/commons-cli/Clients/CarrCodes/CPSC531
git clone --depth 1 https://github.com/juanramonuvus/Acme-Work-Plans.git /data/ucov/repro/commons-cli/Clients/juanramonuvus/Acme-Work-Plans
git clone --depth 1 https://github.com/rohankumardubey/camus.git /data/ucov/repro/commons-cli/Clients/rohankumardubey/camus
git clone --depth 1 https://github.com/mpohler1/amazon-link-checker.git /data/ucov/repro/commons-cli/Clients/mpohler1/amazon-link-checker
git clone --depth 1 https://github.com/Blaquez-home/nuxeo.git /data/ucov/repro/commons-cli/Clients/Blaquez-home/nuxeo
git clone --depth 1 https://github.com/ghas-results/flink.git /data/ucov/repro/commons-cli/Clients/ghas-results/flink
git clone --depth 1 https://github.com/jm624461806/DistributedSystemSkiResort.git /data/ucov/repro/commons-cli/Clients/jm624461806/DistributedSystemSkiResort
git clone --depth 1 https://github.com/subugoe/ocr-tools.git /data/ucov/repro/commons-cli/Clients/subugoe/ocr-tools
git clone --depth 1 https://github.com/gfoster1/chess.git /data/ucov/repro/commons-cli/Clients/gfoster1/chess
git clone --depth 1 https://github.com/ryanardo/gcp-java-docs-samples.git /data/ucov/repro/commons-cli/Clients/ryanardo/gcp-java-docs-samples
git clone --depth 1 https://github.com/robjbutler77/Volo_API.git /data/ucov/repro/commons-cli/Clients/robjbutler77/Volo_API
git clone --depth 1 https://github.com/ep-infosec/33_apache_tuscany-sca-2.x.git /data/ucov/repro/commons-cli/Clients/ep-infosec/33_apache_tuscany-sca-2.x
git clone --depth 1 https://github.com/Caojunqi/DJL-RL.git /data/ucov/repro/commons-cli/Clients/Caojunqi/DJL-RL
git clone --depth 1 https://github.com/pjfanning/incubator-linkis.git /data/ucov/repro/commons-cli/Clients/pjfanning/incubator-linkis
git clone --depth 1 https://github.com/cc-archive/search3.git /data/ucov/repro/commons-cli/Clients/cc-archive/search3
git clone --depth 1 https://github.com/DBCDK/rawrepo.git /data/ucov/repro/commons-cli/Clients/DBCDK/rawrepo
git clone --depth 1 https://github.com/P79N6A/rocketmq-2.git /data/ucov/repro/commons-cli/Clients/P79N6A/rocketmq-2
git clone --depth 1 https://github.com/sarvex/checkstyle.git /data/ucov/repro/commons-cli/Clients/sarvex/checkstyle
git clone --depth 1 https://github.com/BaseMC/javgent.git /data/ucov/repro/commons-cli/Clients/BaseMC/javgent
git clone --depth 1 https://github.com/syhleo/rocketmq-all-5.1.0.git /data/ucov/repro/commons-cli/Clients/syhleo/rocketmq-all-5.1.0
git clone --depth 1 https://github.com/mairooni/Flink-TornadoVM-Artifact.git /data/ucov/repro/commons-cli/Clients/mairooni/Flink-TornadoVM-Artifact
git clone --depth 1 https://github.com/shengminw/rocketmq-note.git /data/ucov/repro/commons-cli/Clients/shengminw/rocketmq-note
git clone --depth 1 https://github.com/Super-Special-Pookies/PhraseExtract.git /data/ucov/repro/commons-cli/Clients/Super-Special-Pookies/PhraseExtract
git clone --depth 1 https://github.com/Arquisoft/participationSystem1a.git /data/ucov/repro/commons-cli/Clients/Arquisoft/participationSystem1a
git clone --depth 1 https://github.com/jiao1997/amie.git /data/ucov/repro/commons-cli/Clients/jiao1997/amie
git clone --depth 1 https://github.com/zahori-io/zahori-framework.git /data/ucov/repro/commons-cli/Clients/zahori-io/zahori-framework
git clone --depth 1 https://github.com/gkthiruvathukal/ChatGPT-Java-CS1-CS2-ACM.git /data/ucov/repro/commons-cli/Clients/gkthiruvathukal/ChatGPT-Java-CS1-CS2-ACM
git clone --depth 1 https://github.com/HowardQin/hadoop-2.6.0-cdh5.4.1.git /data/ucov/repro/commons-cli/Clients/HowardQin/hadoop-2.6.0-cdh5.4.1
git clone --depth 1 https://github.com/cqdxwjd/apache-hive-2.3.9-src.git /data/ucov/repro/commons-cli/Clients/cqdxwjd/apache-hive-2.3.9-src
git clone --depth 1 https://github.com/searchEngineer2022/main.git /data/ucov/repro/commons-cli/Clients/searchEngineer2022/main
git clone --depth 1 https://github.com/kevin10030/Reverb.git /data/ucov/repro/commons-cli/Clients/kevin10030/Reverb
git clone --depth 1 https://github.com/wwwwwfp/rockmq-master.git /data/ucov/repro/commons-cli/Clients/wwwwwfp/rockmq-master
git clone --depth 1 https://github.com/yeewang/lantern.git /data/ucov/repro/commons-cli/Clients/yeewang/lantern
git clone --depth 1 https://github.com/Noura-alh/DecisionTreeClassifier.git /data/ucov/repro/commons-cli/Clients/Noura-alh/DecisionTreeClassifier
git clone --depth 1 https://github.com/Jorgehadad/2ndBlockSolvdSergey.git /data/ucov/repro/commons-cli/Clients/Jorgehadad/2ndBlockSolvdSergey
git clone --depth 1 https://github.com/devildp243/sonar-report.git /data/ucov/repro/commons-cli/Clients/devildp243/sonar-report
git clone --depth 1 https://github.com/koczadly/nano-pow-benchmark.git /data/ucov/repro/commons-cli/Clients/koczadly/nano-pow-benchmark
git clone --depth 1 https://github.com/miguelvelezmj25/ConfigCrusher.git /data/ucov/repro/commons-cli/Clients/miguelvelezmj25/ConfigCrusher
git clone --depth 1 https://github.com/sudeepika/jAlbum.git /data/ucov/repro/commons-cli/Clients/sudeepika/jAlbum
git clone --depth 1 https://github.com/songxiaosheng/dubbo-samples.git /data/ucov/repro/commons-cli/Clients/songxiaosheng/dubbo-samples
git clone --depth 1 https://github.com/LeonardoEzio/nacos-2.0.4.git /data/ucov/repro/commons-cli/Clients/LeonardoEzio/nacos-2.0.4
git clone --depth 1 https://github.com/Mighty0r0n/fastaAnalyzer.git /data/ucov/repro/commons-cli/Clients/Mighty0r0n/fastaAnalyzer
git clone --depth 1 https://github.com/String10/HadoopTemplate.git /data/ucov/repro/commons-cli/Clients/String10/HadoopTemplate
git clone --depth 1 https://github.com/crukci-bioinformatics/ampliconseq.git /data/ucov/repro/commons-cli/Clients/crukci-bioinformatics/ampliconseq
git clone --depth 1 https://github.com/zw201913/echo.git /data/ucov/repro/commons-cli/Clients/zw201913/echo
git clone --depth 1 https://github.com/enmabybella/googleads-shopping-samples.git /data/ucov/repro/commons-cli/Clients/enmabybella/googleads-shopping-samples
git clone --depth 1 https://github.com/alibaba/SREWorks.git /data/ucov/repro/commons-cli/Clients/alibaba/SREWorks
git clone --depth 1 https://github.com/hsu-aut/mtp2skill.git /data/ucov/repro/commons-cli/Clients/hsu-aut/mtp2skill
git clone --depth 1 https://github.com/sarvex/SpringIOPlatformFoudation.git /data/ucov/repro/commons-cli/Clients/sarvex/SpringIOPlatformFoudation
git clone --depth 1 https://github.com/vdaburon/JUnitReportKpiJMeterReportCsv.git /data/ucov/repro/commons-cli/Clients/vdaburon/JUnitReportKpiJMeterReportCsv
git clone --depth 1 https://github.com/narala558/Apache_Flink_Kafka_to_s3.git /data/ucov/repro/commons-cli/Clients/narala558/Apache_Flink_Kafka_to_s3
git clone --depth 1 https://github.com/QuiltMC/quilt-loader-sat4j.git /data/ucov/repro/commons-cli/Clients/QuiltMC/quilt-loader-sat4j
git clone --depth 1 https://github.com/ekmixon/mallet.git /data/ucov/repro/commons-cli/Clients/ekmixon/mallet
git clone --depth 1 https://github.com/FranAnillo/Acme-Jobs.git /data/ucov/repro/commons-cli/Clients/FranAnillo/Acme-Jobs
git clone --depth 1 https://github.com/dleyanlin/cobra.git /data/ucov/repro/commons-cli/Clients/dleyanlin/cobra
git clone --depth 1 https://github.com/intoolswetrust/jsignpdf.git /data/ucov/repro/commons-cli/Clients/intoolswetrust/jsignpdf
git clone --depth 1 https://github.com/lluviasnow/lobster.git /data/ucov/repro/commons-cli/Clients/lluviasnow/lobster
git clone --depth 1 https://github.com/vishal210893/Java-Reactive.git /data/ucov/repro/commons-cli/Clients/vishal210893/Java-Reactive
git clone --depth 1 https://github.com/dancasnar1/Acme-One.git /data/ucov/repro/commons-cli/Clients/dancasnar1/Acme-One
git clone --depth 1 https://github.com/DiegoRuizGil/ACME-ONE-Repository.git /data/ucov/repro/commons-cli/Clients/DiegoRuizGil/ACME-ONE-Repository
git clone --depth 1 https://github.com/sinri/Silhouette.git /data/ucov/repro/commons-cli/Clients/sinri/Silhouette
git clone --depth 1 https://github.com/nicobritos/uni-hazelcast-app.git /data/ucov/repro/commons-cli/Clients/nicobritos/uni-hazelcast-app
git clone --depth 1 https://github.com/momo-tong/zookeeper-3.5.4-beta.git /data/ucov/repro/commons-cli/Clients/momo-tong/zookeeper-3.5.4-beta
git clone --depth 1 https://github.com/cloudwebsoft/TFlow.git /data/ucov/repro/commons-cli/Clients/cloudwebsoft/TFlow
git clone --depth 1 https://github.com/surenganne/metadata.git /data/ucov/repro/commons-cli/Clients/surenganne/metadata
git clone --depth 1 https://github.com/CR400AF2001/NJUSE-SEC1-JVVM.git /data/ucov/repro/commons-cli/Clients/CR400AF2001/NJUSE-SEC1-JVVM
git clone --depth 1 https://github.com/JanJanda/otava.git /data/ucov/repro/commons-cli/Clients/JanJanda/otava
git clone --depth 1 https://github.com/celdorwow/diceware.git /data/ucov/repro/commons-cli/Clients/celdorwow/diceware
git clone --depth 1 https://github.com/hoanghun/memory-analyzer.git /data/ucov/repro/commons-cli/Clients/hoanghun/memory-analyzer
git clone --depth 1 https://github.com/openaire/broker-cmdline-client.git /data/ucov/repro/commons-cli/Clients/openaire/broker-cmdline-client
git clone --depth 1 https://github.com/CyberFlameGO/shiro.git /data/ucov/repro/commons-cli/Clients/CyberFlameGO/shiro
git clone --depth 1 https://github.com/h4lo343/P2P-Downloader.git /data/ucov/repro/commons-cli/Clients/h4lo343/P2P-Downloader
git clone --depth 1 https://github.com/tedwon/flume-1.git /data/ucov/repro/commons-cli/Clients/tedwon/flume-1
git clone --depth 1 https://github.com/jiaxukang/P2PFileTransfer.git /data/ucov/repro/commons-cli/Clients/jiaxukang/P2PFileTransfer
git clone --depth 1 https://github.com/git-gloomy/Tankstellenpreise_PoC.git /data/ucov/repro/commons-cli/Clients/git-gloomy/Tankstellenpreise_PoC
git clone --depth 1 https://github.com/wix-incubator/JarInjector.git /data/ucov/repro/commons-cli/Clients/wix-incubator/JarInjector
git clone --depth 1 https://github.com/rummykhan/jre-knowledge-console.git /data/ucov/repro/commons-cli/Clients/rummykhan/jre-knowledge-console
git clone --depth 1 https://github.com/vermutr/to.git /data/ucov/repro/commons-cli/Clients/vermutr/to
git clone --depth 1 https://github.com/swap-10/flink-shallow-clone.git /data/ucov/repro/commons-cli/Clients/swap-10/flink-shallow-clone
git clone --depth 1 https://github.com/gomcarter/rocketmq-all-t.git /data/ucov/repro/commons-cli/Clients/gomcarter/rocketmq-all-t
git clone --depth 1 https://github.com/Ovhek/JAXB_XML.git /data/ucov/repro/commons-cli/Clients/Ovhek/JAXB_XML
git clone --depth 1 https://github.com/jsteyn/JMC.git /data/ucov/repro/commons-cli/Clients/jsteyn/JMC
git clone --depth 1 https://github.com/Ste29/manga-scraper.git /data/ucov/repro/commons-cli/Clients/Ste29/manga-scraper
git clone --depth 1 https://github.com/Joker-5/rocketmq-source-debug.git /data/ucov/repro/commons-cli/Clients/Joker-5/rocketmq-source-debug
git clone --depth 1 https://github.com/goluckywizard/CFT-JINT-2023.git /data/ucov/repro/commons-cli/Clients/goluckywizard/CFT-JINT-2023
git clone --depth 1 https://github.com/swag-bi/swag.git /data/ucov/repro/commons-cli/Clients/swag-bi/swag
git clone --depth 1 https://github.com/ghas-results/common-parent-pom.git /data/ucov/repro/commons-cli/Clients/ghas-results/common-parent-pom
git clone --depth 1 https://github.com/rainweb521/zookeeper_chinese.git /data/ucov/repro/commons-cli/Clients/rainweb521/zookeeper_chinese
git clone --depth 1 https://github.com/srslol/BasicFolderMonitoring.git /data/ucov/repro/commons-cli/Clients/srslol/BasicFolderMonitoring
git clone --depth 1 https://github.com/hakmesyo/OJL.git /data/ucov/repro/commons-cli/Clients/hakmesyo/OJL
git clone --depth 1 https://github.com/PhuongNguyen2612/Calculator.git /data/ucov/repro/commons-cli/Clients/PhuongNguyen2612/Calculator
git clone --depth 1 https://github.com/ali-ghanbari/objsim.git /data/ucov/repro/commons-cli/Clients/ali-ghanbari/objsim
git clone --depth 1 https://github.com/jtfromus/CompArchProj.git /data/ucov/repro/commons-cli/Clients/jtfromus/CompArchProj
git clone --depth 1 https://github.com/Feysh-Group/FlowDroid.git /data/ucov/repro/commons-cli/Clients/Feysh-Group/FlowDroid
git clone --depth 1 https://github.com/Tryweirder/atlas.git /data/ucov/repro/commons-cli/Clients/Tryweirder/atlas
git clone --depth 1 https://github.com/kinde-oss/kinde-react-native-generator-0-6x.git /data/ucov/repro/commons-cli/Clients/kinde-oss/kinde-react-native-generator-0-6x
git clone --depth 1 https://github.com/ogoerens/master.git /data/ucov/repro/commons-cli/Clients/ogoerens/master
git clone --depth 1 https://github.com/huang-feiyu/NanoDB.git /data/ucov/repro/commons-cli/Clients/huang-feiyu/NanoDB
git clone --depth 1 https://github.com/Kirill112002/Software.git /data/ucov/repro/commons-cli/Clients/Kirill112002/Software
git clone --depth 1 https://github.com/rohankumardubey/datawave.git /data/ucov/repro/commons-cli/Clients/rohankumardubey/datawave
git clone --depth 1 https://github.com/surya-hebbar/impala.git /data/ucov/repro/commons-cli/Clients/surya-hebbar/impala
