git clone --depth 1 https://github.com/harishm1016/Java-project.git /data/ucov/repro/spark/Clients/harishm1016/Java-project
git clone --depth 1 https://github.com/nidianwo/cs.git /data/ucov/repro/spark/Clients/nidianwo/cs
git clone --depth 1 https://github.com/pbarot10/Java-Course.git /data/ucov/repro/spark/Clients/pbarot10/Java-Course
git clone --depth 1 https://github.com/EdikKing/sprov-ui.git /data/ucov/repro/spark/Clients/EdikKing/sprov-ui
git clone --depth 1 https://github.com/marco-spallone/JavaTestKleecks.git /data/ucov/repro/spark/Clients/marco-spallone/JavaTestKleecks
git clone --depth 1 https://github.com/rauulriveroo/ScrappingtoApi.git /data/ucov/repro/spark/Clients/rauulriveroo/ScrappingtoApi
git clone --depth 1 https://github.com/sushanku/jenkins-mvn-ansible.git /data/ucov/repro/spark/Clients/sushanku/jenkins-mvn-ansible
git clone --depth 1 https://github.com/cs0320-s2022/async-typescript-lab-lmb2lmb.git /data/ucov/repro/spark/Clients/cs0320-s2022/async-typescript-lab-lmb2lmb
git clone --depth 1 https://github.com/jpacio89/unn-inputter.git /data/ucov/repro/spark/Clients/jpacio89/unn-inputter
git clone --depth 1 https://github.com/DGemmell/spark_notes.git /data/ucov/repro/spark/Clients/DGemmell/spark_notes
git clone --depth 1 https://github.com/cs0320-f2021/lab-apis-5EEkQRS3c9h4MzDH.git /data/ucov/repro/spark/Clients/cs0320-f2021/lab-apis-5EEkQRS3c9h4MzDH
git clone --depth 1 https://github.com/Nikolai9906/AREP-SPARK_WEB_APP.git /data/ucov/repro/spark/Clients/Nikolai9906/AREP-SPARK_WEB_APP
git clone --depth 1 https://github.com/vkalev/covcal.git /data/ucov/repro/spark/Clients/vkalev/covcal
git clone --depth 1 https://github.com/rezaabedi1365/awsome-compose.git /data/ucov/repro/spark/Clients/rezaabedi1365/awsome-compose
git clone --depth 1 https://github.com/Augustzzn/java_cs61b.git /data/ucov/repro/spark/Clients/Augustzzn/java_cs61b
git clone --depth 1 https://github.com/felipecordente/spark-example-felipecordente.git /data/ucov/repro/spark/Clients/felipecordente/spark-example-felipecordente
git clone --depth 1 https://github.com/Azurexuan/cs61b.git /data/ucov/repro/spark/Clients/Azurexuan/cs61b
git clone --depth 1 https://github.com/SergioRibera/srserver-java-dip.git /data/ucov/repro/spark/Clients/SergioRibera/srserver-java-dip
git clone --depth 1 https://github.com/BuggedPotato/java_serverside.git /data/ucov/repro/spark/Clients/BuggedPotato/java_serverside
git clone --depth 1 https://github.com/cecibou/TI-2_Diary.git /data/ucov/repro/spark/Clients/cecibou/TI-2_Diary
git clone --depth 1 https://github.com/luke7oaks/tamtam-bot-api.git /data/ucov/repro/spark/Clients/luke7oaks/tamtam-bot-api
git clone --depth 1 https://github.com/hexagonkt/tfb.git /data/ucov/repro/spark/Clients/hexagonkt/tfb
git clone --depth 1 https://github.com/id4ajeet/my_projects.git /data/ucov/repro/spark/Clients/id4ajeet/my_projects
git clone --depth 1 https://github.com/MUTHAKABRIAN/The_Classic_Cut.git /data/ucov/repro/spark/Clients/MUTHAKABRIAN/The_Classic_Cut
git clone --depth 1 https://github.com/khoa102/khoa-spark-rest-api.git /data/ucov/repro/spark/Clients/khoa102/khoa-spark-rest-api
git clone --depth 1 https://github.com/cs0320-f2021/project-1-2idcvzbrosljikn6-e87piez9jqf3bzksrob3-lznuscrfbj123shine4we5.git /data/ucov/repro/spark/Clients/cs0320-f2021/project-1-2idcvzbrosljikn6-e87piez9jqf3bzksrob3-lznuscrfbj123shine4we5
git clone --depth 1 https://github.com/cs0320-f2021/project-2-afjkagjak24jsgjg-fdakjg2jfdkaj-adjfajdfvdkjkfj2.git /data/ucov/repro/spark/Clients/cs0320-f2021/project-2-afjkagjak24jsgjg-fdakjg2jfdkaj-adjfajdfvdkjkfj2
git clone --depth 1 https://github.com/k-appears/java_backend-xing.git /data/ucov/repro/spark/Clients/k-appears/java_backend-xing
git clone --depth 1 https://github.com/DiegoGuida/ConsultoreaMe.git /data/ucov/repro/spark/Clients/DiegoGuida/ConsultoreaMe
git clone --depth 1 https://github.com/sbesh91/TestKotlinMicroService.git /data/ucov/repro/spark/Clients/sbesh91/TestKotlinMicroService
git clone --depth 1 https://github.com/Oksird/BlockChainLabs.git /data/ucov/repro/spark/Clients/Oksird/BlockChainLabs
git clone --depth 1 https://github.com/Kyriezxc/Search_Engine.git /data/ucov/repro/spark/Clients/Kyriezxc/Search_Engine
git clone --depth 1 https://github.com/kqi-dev/BattleSnake2021.git /data/ucov/repro/spark/Clients/kqi-dev/BattleSnake2021
git clone --depth 1 https://github.com/kierajost4/Tic-Tac-Toe.git /data/ucov/repro/spark/Clients/kierajost4/Tic-Tac-Toe
git clone --depth 1 https://github.com/DeveloperOwala/heroSquard.git /data/ucov/repro/spark/Clients/DeveloperOwala/heroSquard
git clone --depth 1 https://github.com/thgoexpt/Java-distributed-tracing-implementation.git /data/ucov/repro/spark/Clients/thgoexpt/Java-distributed-tracing-implementation
git clone --depth 1 https://github.com/tungphongdo89/tinhocthatladongian.git /data/ucov/repro/spark/Clients/tungphongdo89/tinhocthatladongian
git clone --depth 1 https://github.com/YohannaToro/security-ssl.git /data/ucov/repro/spark/Clients/YohannaToro/security-ssl
git clone --depth 1 https://github.com/DevOps2021-gb/devops2021.git /data/ucov/repro/spark/Clients/DevOps2021-gb/devops2021
git clone --depth 1 https://github.com/SantiagoBayona/AREP-Lab-06-Service.git /data/ucov/repro/spark/Clients/SantiagoBayona/AREP-Lab-06-Service
git clone --depth 1 https://github.com/alan-hash/Arquitectura-orientada-a-servicios.git /data/ucov/repro/spark/Clients/alan-hash/Arquitectura-orientada-a-servicios
git clone --depth 1 https://github.com/dataspread/Sherlock.git /data/ucov/repro/spark/Clients/dataspread/Sherlock
git clone --depth 1 https://github.com/shahebaaz1shaikh/HelloWorld.git /data/ucov/repro/spark/Clients/shahebaaz1shaikh/HelloWorld
git clone --depth 1 https://github.com/idk-12/CS61B.git /data/ucov/repro/spark/Clients/idk-12/CS61B
git clone --depth 1 https://github.com/NatesHonor/FakenetworkCore.git /data/ucov/repro/spark/Clients/NatesHonor/FakenetworkCore
git clone --depth 1 https://github.com/Daniel19902/IETI-TALLER-HEROKU.git /data/ucov/repro/spark/Clients/Daniel19902/IETI-TALLER-HEROKU
git clone --depth 1 https://github.com/sebasporras14/lab-07AREP.git /data/ucov/repro/spark/Clients/sebasporras14/lab-07AREP
git clone --depth 1 https://github.com/ian-mamen/LifeTracker.git /data/ucov/repro/spark/Clients/ian-mamen/LifeTracker
git clone --depth 1 https://github.com/FernandoKovaleski/CursoJavaTT.git /data/ucov/repro/spark/Clients/FernandoKovaleski/CursoJavaTT
git clone --depth 1 https://github.com/MartinGongora/huella-de-carbono-DDS.git /data/ucov/repro/spark/Clients/MartinGongora/huella-de-carbono-DDS
git clone --depth 1 https://github.com/ppablomedina/Developing-a-datalake.git /data/ucov/repro/spark/Clients/ppablomedina/Developing-a-datalake
git clone --depth 1 https://github.com/flindback/trumplator.git /data/ucov/repro/spark/Clients/flindback/trumplator
git clone --depth 1 https://github.com/dorukerenaktas/cep-intelligent-assistant.git /data/ucov/repro/spark/Clients/dorukerenaktas/cep-intelligent-assistant
git clone --depth 1 https://github.com/ayolicias/cartoonNetwork_siyafunda_app.git /data/ucov/repro/spark/Clients/ayolicias/cartoonNetwork_siyafunda_app
git clone --depth 1 https://github.com/alexchomiak/FinancialSentimentAnalysis.git /data/ucov/repro/spark/Clients/alexchomiak/FinancialSentimentAnalysis
git clone --depth 1 https://github.com/kaijack/reactjsc.git /data/ucov/repro/spark/Clients/kaijack/reactjsc
git clone --depth 1 https://github.com/stripe-samples/starter.git /data/ucov/repro/spark/Clients/stripe-samples/starter
git clone --depth 1 https://github.com/raul-fernando-mendoza/accept-a-card-payment.git /data/ucov/repro/spark/Clients/raul-fernando-mendoza/accept-a-card-payment
git clone --depth 1 https://github.com/juanmora98/AREP-PARCIAL1.git /data/ucov/repro/spark/Clients/juanmora98/AREP-PARCIAL1
git clone --depth 1 https://github.com/xuanliu2021/sp18-Alex.git /data/ucov/repro/spark/Clients/xuanliu2021/sp18-Alex
git clone --depth 1 https://github.com/Daligz/GreenWaste.git /data/ucov/repro/spark/Clients/Daligz/GreenWaste
git clone --depth 1 https://github.com/mario86123/cs61b-2018.git /data/ucov/repro/spark/Clients/mario86123/cs61b-2018
git clone --depth 1 https://github.com/terragraph/tgnms.git /data/ucov/repro/spark/Clients/terragraph/tgnms
git clone --depth 1 https://github.com/dlambrechts/robot-shop.git /data/ucov/repro/spark/Clients/dlambrechts/robot-shop
git clone --depth 1 https://github.com/JoePacman/spark-java-poc.git /data/ucov/repro/spark/Clients/JoePacman/spark-java-poc
git clone --depth 1 https://github.com/agujuarez97/calculator.git /data/ucov/repro/spark/Clients/agujuarez97/calculator
git clone --depth 1 https://github.com/kfinger85/415Clone.git /data/ucov/repro/spark/Clients/kfinger85/415Clone
git clone --depth 1 https://github.com/cs0320-f2021/lab-react-sfeucht.git /data/ucov/repro/spark/Clients/cs0320-f2021/lab-react-sfeucht
git clone --depth 1 https://github.com/Dayasingh22/BDA-Project-Activity-1.git /data/ucov/repro/spark/Clients/Dayasingh22/BDA-Project-Activity-1
git clone --depth 1 https://github.com/Jethuestad/DAT250-expass4-code.git /data/ucov/repro/spark/Clients/Jethuestad/DAT250-expass4-code
git clone --depth 1 https://github.com/My-TRAC/data-model-Pilot1.git /data/ucov/repro/spark/Clients/My-TRAC/data-model-Pilot1
git clone --depth 1 https://github.com/danielrincon-m/AREP_PARCIAL1.git /data/ucov/repro/spark/Clients/danielrincon-m/AREP_PARCIAL1
git clone --depth 1 https://github.com/AlduinLeung/cs61b-sp-18.git /data/ucov/repro/spark/Clients/AlduinLeung/cs61b-sp-18
git clone --depth 1 https://github.com/dutalmahesh/webtest.git /data/ucov/repro/spark/Clients/dutalmahesh/webtest
git clone --depth 1 https://github.com/aj921132/dockercompose.git /data/ucov/repro/spark/Clients/aj921132/dockercompose
git clone --depth 1 https://github.com/tjgwebservices/sparkweb.git /data/ucov/repro/spark/Clients/tjgwebservices/sparkweb
git clone --depth 1 https://github.com/acxg/cs61b.git /data/ucov/repro/spark/Clients/acxg/cs61b
git clone --depth 1 https://github.com/leocao91/web-java-demo.git /data/ucov/repro/spark/Clients/leocao91/web-java-demo
git clone --depth 1 https://github.com/malyshgit/vk-bot.git /data/ucov/repro/spark/Clients/malyshgit/vk-bot
git clone --depth 1 https://github.com/egorkos/minesweeper-restlient-library.git /data/ucov/repro/spark/Clients/egorkos/minesweeper-restlient-library
git clone --depth 1 https://github.com/2022-SEMII-DESIV-G2/moreno-alex.git /data/ucov/repro/spark/Clients/2022-SEMII-DESIV-G2/moreno-alex
git clone --depth 1 https://github.com/cargneluttiLucas/java-clase.git /data/ucov/repro/spark/Clients/cargneluttiLucas/java-clase
git clone --depth 1 https://github.com/vkasturia/semantic-layers.git /data/ucov/repro/spark/Clients/vkasturia/semantic-layers
git clone --depth 1 https://github.com/sebastianNietoMolina/AREP-lab5.git /data/ucov/repro/spark/Clients/sebastianNietoMolina/AREP-lab5
git clone --depth 1 https://github.com/cooperece366s21/CoopedIn.git /data/ucov/repro/spark/Clients/cooperece366s21/CoopedIn
git clone --depth 1 https://github.com/AP2021Fall/Project-team-09.git /data/ucov/repro/spark/Clients/AP2021Fall/Project-team-09
git clone --depth 1 https://github.com/timothybaraka/herosquad.git /data/ucov/repro/spark/Clients/timothybaraka/herosquad
git clone --depth 1 https://github.com/JCPosso/AREP-Lab06.git /data/ucov/repro/spark/Clients/JCPosso/AREP-Lab06
git clone --depth 1 https://github.com/javanotes/actiongraph.git /data/ucov/repro/spark/Clients/javanotes/actiongraph
git clone --depth 1 https://github.com/cheatmac/maven.git /data/ucov/repro/spark/Clients/cheatmac/maven
git clone --depth 1 https://github.com/67shafar/MedicationOnFHIR.git /data/ucov/repro/spark/Clients/67shafar/MedicationOnFHIR
git clone --depth 1 https://github.com/GoupilJeremy/karma-server.git /data/ucov/repro/spark/Clients/GoupilJeremy/karma-server
git clone --depth 1 https://github.com/CarlosOrduz777/AREP-SecureApp.git /data/ucov/repro/spark/Clients/CarlosOrduz777/AREP-SecureApp
git clone --depth 1 https://github.com/KingWNTK/ChatApp.git /data/ucov/repro/spark/Clients/KingWNTK/ChatApp
git clone --depth 1 https://github.com/bigxiongs/my-cs61b.git /data/ucov/repro/spark/Clients/bigxiongs/my-cs61b
git clone --depth 1 https://github.com/abnerjoy/cs61b.git /data/ucov/repro/spark/Clients/abnerjoy/cs61b
git clone --depth 1 https://github.com/tevin-otieno/wild-animal-tracker.git /data/ucov/repro/spark/Clients/tevin-otieno/wild-animal-tracker
git clone --depth 1 https://github.com/Parodix007/spark-java-demo.git /data/ucov/repro/spark/Clients/Parodix007/spark-java-demo
git clone --depth 1 https://github.com/LawlessLawless/GLO2004_Devoir1.git /data/ucov/repro/spark/Clients/LawlessLawless/GLO2004_Devoir1
git clone --depth 1 https://github.com/kkadouh/stripetest.git /data/ucov/repro/spark/Clients/kkadouh/stripetest
git clone --depth 1 https://github.com/nickfun/TwilioDemo.git /data/ucov/repro/spark/Clients/nickfun/TwilioDemo
git clone --depth 1 https://github.com/Jscorpio1611/web-elements-sepa-debit-payment.git /data/ucov/repro/spark/Clients/Jscorpio1611/web-elements-sepa-debit-payment
git clone --depth 1 https://github.com/Sergyo97/Lambda_And_Gateway_Services.git /data/ucov/repro/spark/Clients/Sergyo97/Lambda_And_Gateway_Services
git clone --depth 1 https://github.com/nr23730/fhirspark.git /data/ucov/repro/spark/Clients/nr23730/fhirspark
git clone --depth 1 https://github.com/cs0320-f2021/lab-canvas-haridandapani.git /data/ucov/repro/spark/Clients/cs0320-f2021/lab-canvas-haridandapani
git clone --depth 1 https://github.com/Camilomora117/Parcial2Arep.git /data/ucov/repro/spark/Clients/Camilomora117/Parcial2Arep
git clone --depth 1 https://github.com/Larfg/arep-parcial2.git /data/ucov/repro/spark/Clients/Larfg/arep-parcial2
git clone --depth 1 https://github.com/hsintzuli/cs61b.git /data/ucov/repro/spark/Clients/hsintzuli/cs61b
git clone --depth 1 https://github.com/ipiranhaauxxoj/CcbGuangzhouDevelopera.git /data/ucov/repro/spark/Clients/ipiranhaauxxoj/CcbGuangzhouDevelopera
git clone --depth 1 https://github.com/Luis7km/Semestral-LuisMilla.git /data/ucov/repro/spark/Clients/Luis7km/Semestral-LuisMilla
git clone --depth 1 https://github.com/Freda32/cs61b_sy.git /data/ucov/repro/spark/Clients/Freda32/cs61b_sy
git clone --depth 1 https://github.com/dd-test5/FrameworkBenchmarks.git /data/ucov/repro/spark/Clients/dd-test5/FrameworkBenchmarks
git clone --depth 1 https://github.com/kenjoel/virtualTracker.git /data/ucov/repro/spark/Clients/kenjoel/virtualTracker
git clone --depth 1 https://github.com/srigit009/java.git /data/ucov/repro/spark/Clients/srigit009/java
git clone --depth 1 https://github.com/hmy824/CS61B.git /data/ucov/repro/spark/Clients/hmy824/CS61B
git clone --depth 1 https://github.com/JiajiaLi04/CS61B-Data-Structure.git /data/ucov/repro/spark/Clients/JiajiaLi04/CS61B-Data-Structure
git clone --depth 1 https://github.com/adireddy735/maven-war.git /data/ucov/repro/spark/Clients/adireddy735/maven-war
git clone --depth 1 https://github.com/gabriela-castro-s/AREP-TALLER-5.git /data/ucov/repro/spark/Clients/gabriela-castro-s/AREP-TALLER-5
git clone --depth 1 https://github.com/ehtiramabdullayev/simple-bank-transfer-api.git /data/ucov/repro/spark/Clients/ehtiramabdullayev/simple-bank-transfer-api
git clone --depth 1 https://github.com/rwema3/platform-samples.git /data/ucov/repro/spark/Clients/rwema3/platform-samples
git clone --depth 1 https://github.com/ElPentagono/BookQueryEngine.git /data/ucov/repro/spark/Clients/ElPentagono/BookQueryEngine
git clone --depth 1 https://github.com/jmarusak/apisec.git /data/ucov/repro/spark/Clients/jmarusak/apisec
git clone --depth 1 https://github.com/ribeir099/PUC-Minas.git /data/ucov/repro/spark/Clients/ribeir099/PUC-Minas
git clone --depth 1 https://github.com/weinijuan/cs.git /data/ucov/repro/spark/Clients/weinijuan/cs
git clone --depth 1 https://github.com/Tammaoui/dat250-expass4-code.git /data/ucov/repro/spark/Clients/Tammaoui/dat250-expass4-code
git clone --depth 1 https://github.com/preminstrel/cs61b.git /data/ucov/repro/spark/Clients/preminstrel/cs61b
git clone --depth 1 https://github.com/naveengithubfiles/hello-world.git /data/ucov/repro/spark/Clients/naveengithubfiles/hello-world
git clone --depth 1 https://github.com/shankar0457/sparkjava-test.git /data/ucov/repro/spark/Clients/shankar0457/sparkjava-test
git clone --depth 1 https://github.com/elttam/sparkdemo.git /data/ucov/repro/spark/Clients/elttam/sparkdemo
git clone --depth 1 https://github.com/brianmuigai96/wildlife-tracker.git /data/ucov/repro/spark/Clients/brianmuigai96/wildlife-tracker
git clone --depth 1 https://github.com/afieldi/cloudcompute-1.git /data/ucov/repro/spark/Clients/afieldi/cloudcompute-1
git clone --depth 1 https://github.com/ahmetkaygisiz/quotes-rest-app.git /data/ucov/repro/spark/Clients/ahmetkaygisiz/quotes-rest-app
git clone --depth 1 https://github.com/cristiangiann/mtds-project-rest.git /data/ucov/repro/spark/Clients/cristiangiann/mtds-project-rest
git clone --depth 1 https://github.com/TI02-Simplinsino/simplinsino.git /data/ucov/repro/spark/Clients/TI02-Simplinsino/simplinsino
git clone --depth 1 https://github.com/wolfcito/neoflix-app.git /data/ucov/repro/spark/Clients/wolfcito/neoflix-app
git clone --depth 1 https://github.com/Xiaohongdian119/CS61B.git /data/ucov/repro/spark/Clients/Xiaohongdian119/CS61B
git clone --depth 1 https://github.com/rhuang1564/CampusMaps.git /data/ucov/repro/spark/Clients/rhuang1564/CampusMaps
git clone --depth 1 https://github.com/k8s-docs/knative-docs.git /data/ucov/repro/spark/Clients/k8s-docs/knative-docs
git clone --depth 1 https://github.com/oyjoh/DAT250-expass4.git /data/ucov/repro/spark/Clients/oyjoh/DAT250-expass4
git clone --depth 1 https://github.com/oliveiramarcio/githubparser.git /data/ucov/repro/spark/Clients/oliveiramarcio/githubparser
git clone --depth 1 https://github.com/being12345/cs61b18.git /data/ucov/repro/spark/Clients/being12345/cs61b18
git clone --depth 1 https://github.com/jkL970910/CS61b.git /data/ucov/repro/spark/Clients/jkL970910/CS61b
git clone --depth 1 https://github.com/jmi-axelor/todo-app.git /data/ucov/repro/spark/Clients/jmi-axelor/todo-app
git clone --depth 1 https://github.com/imyzt/learning-technology-code.git /data/ucov/repro/spark/Clients/imyzt/learning-technology-code
git clone --depth 1 https://github.com/hanxu12/cs61b.git /data/ucov/repro/spark/Clients/hanxu12/cs61b
git clone --depth 1 https://github.com/thabok/mycartime.git /data/ucov/repro/spark/Clients/thabok/mycartime
git clone --depth 1 https://github.com/Jcro15/Arep-Parcial1.git /data/ucov/repro/spark/Clients/Jcro15/Arep-Parcial1
git clone --depth 1 https://github.com/weijchen/berkeley-cs61b.git /data/ucov/repro/spark/Clients/weijchen/berkeley-cs61b
git clone --depth 1 https://github.com/RAVI-2016HW86314/sparkjava-war-example.git /data/ucov/repro/spark/Clients/RAVI-2016HW86314/sparkjava-war-example
git clone --depth 1 https://github.com/Victoooooor/ECE-465-Cloud-Computing.git /data/ucov/repro/spark/Clients/Victoooooor/ECE-465-Cloud-Computing
git clone --depth 1 https://github.com/phamduybk/lockex1987.github.io.git /data/ucov/repro/spark/Clients/phamduybk/lockex1987.github.io
git clone --depth 1 https://github.com/cs0320-f2021/project-2-5eekqrs3c9h4mzdh-cs32-student-xkj5cb3ynj9hmfl.git /data/ucov/repro/spark/Clients/cs0320-f2021/project-2-5eekqrs3c9h4mzdh-cs32-student-xkj5cb3ynj9hmfl
git clone --depth 1 https://github.com/OsuTourneyBot/Bancho-Bot.git /data/ucov/repro/spark/Clients/OsuTourneyBot/Bancho-Bot
git clone --depth 1 https://github.com/cravenbrave/DataStructure_couse_2021.git /data/ucov/repro/spark/Clients/cravenbrave/DataStructure_couse_2021
git clone --depth 1 https://github.com/harol-lml/Proyecto21Blackjack.git /data/ucov/repro/spark/Clients/harol-lml/Proyecto21Blackjack
git clone --depth 1 https://github.com/JohannCepeda16/AREP-Lab5.git /data/ucov/repro/spark/Clients/JohannCepeda16/AREP-Lab5
git clone --depth 1 https://github.com/bryanbill/tracker.git /data/ucov/repro/spark/Clients/bryanbill/tracker
git clone --depth 1 https://github.com/maxduu/Web-Search-Engine.git /data/ucov/repro/spark/Clients/maxduu/Web-Search-Engine
git clone --depth 1 https://github.com/Erika2006y/Yoatzi.git /data/ucov/repro/spark/Clients/Erika2006y/Yoatzi
git clone --depth 1 https://github.com/lennartlott/recurly-integration-examples.git /data/ucov/repro/spark/Clients/lennartlott/recurly-integration-examples
git clone --depth 1 https://github.com/scalikejdbc/scalikejdbc4j.git /data/ucov/repro/spark/Clients/scalikejdbc/scalikejdbc4j
git clone --depth 1 https://github.com/VinnieIT/hero-app.git /data/ucov/repro/spark/Clients/VinnieIT/hero-app
git clone --depth 1 https://github.com/y505340035/cs61b-18sp.git /data/ucov/repro/spark/Clients/y505340035/cs61b-18sp
git clone --depth 1 https://github.com/JohannPaez/AREP-SecureSparkWebApp.git /data/ucov/repro/spark/Clients/JohannPaez/AREP-SecureSparkWebApp
git clone --depth 1 https://github.com/pradeep9030/sparkjava.git /data/ucov/repro/spark/Clients/pradeep9030/sparkjava
git clone --depth 1 https://github.com/juankohler/meli-ite-java-api-users.git /data/ucov/repro/spark/Clients/juankohler/meli-ite-java-api-users
git clone --depth 1 https://github.com/jackgrant31/LEDHub.git /data/ucov/repro/spark/Clients/jackgrant31/LEDHub
git clone --depth 1 https://github.com/Adri4nG/MovieRental_Group7.git /data/ucov/repro/spark/Clients/Adri4nG/MovieRental_Group7
git clone --depth 1 https://github.com/eshalakhotia/Shreddify.git /data/ucov/repro/spark/Clients/eshalakhotia/Shreddify
git clone --depth 1 https://github.com/itisrost/RvHome.git /data/ucov/repro/spark/Clients/itisrost/RvHome
git clone --depth 1 https://github.com/George-Okumu/Wildlife-Tracker.git /data/ucov/repro/spark/Clients/George-Okumu/Wildlife-Tracker
git clone --depth 1 https://github.com/Davidgrcdz/Scraper-Project.git /data/ucov/repro/spark/Clients/Davidgrcdz/Scraper-Project
git clone --depth 1 https://github.com/zehaowang/cs61b-sp18.git /data/ucov/repro/spark/Clients/zehaowang/cs61b-sp18
git clone --depth 1 https://github.com/martinnyakimov/MyHomeAssistant.git /data/ucov/repro/spark/Clients/martinnyakimov/MyHomeAssistant
git clone --depth 1 https://github.com/jonathanjma/Megamaze.git /data/ucov/repro/spark/Clients/jonathanjma/Megamaze
git clone --depth 1 https://github.com/winterhy/stars-project.git /data/ucov/repro/spark/Clients/winterhy/stars-project
git clone --depth 1 https://github.com/towc/wordsnake-vue-java.git /data/ucov/repro/spark/Clients/towc/wordsnake-vue-java
git clone --depth 1 https://github.com/jayanthiutharadu/docker.git /data/ucov/repro/spark/Clients/jayanthiutharadu/docker
git clone --depth 1 https://github.com/nguyenvivian/OhWhale.git /data/ucov/repro/spark/Clients/nguyenvivian/OhWhale
git clone --depth 1 https://github.com/juanbaezl/tareaDockerAWS.git /data/ucov/repro/spark/Clients/juanbaezl/tareaDockerAWS
git clone --depth 1 https://github.com/stg1205/CS61B.git /data/ucov/repro/spark/Clients/stg1205/CS61B
git clone --depth 1 https://github.com/aasheesh03/book-my-ticket.git /data/ucov/repro/spark/Clients/aasheesh03/book-my-ticket
git clone --depth 1 https://github.com/cs0320-f2021/lab-front-end-ofrmnwcsi5m5yxbo.git /data/ucov/repro/spark/Clients/cs0320-f2021/lab-front-end-ofrmnwcsi5m5yxbo
git clone --depth 1 https://github.com/angiedanielar/LAB5_AREP.git /data/ucov/repro/spark/Clients/angiedanielar/LAB5_AREP
git clone --depth 1 https://github.com/eric900115/CS61b.git /data/ucov/repro/spark/Clients/eric900115/CS61b
git clone --depth 1 https://github.com/TorjusFS/dat250.git /data/ucov/repro/spark/Clients/TorjusFS/dat250
git clone --depth 1 https://github.com/Rincon10/AREP-LAB02.git /data/ucov/repro/spark/Clients/Rincon10/AREP-LAB02
git clone --depth 1 https://github.com/shoyui/cs61b-sp18.git /data/ucov/repro/spark/Clients/shoyui/cs61b-sp18
git clone --depth 1 https://github.com/yiming421/mine_cs61b.git /data/ucov/repro/spark/Clients/yiming421/mine_cs61b
git clone --depth 1 https://github.com/cs0320-f2021/lab-front-end-8mzln8.git /data/ucov/repro/spark/Clients/cs0320-f2021/lab-front-end-8mzln8
git clone --depth 1 https://github.com/nla/jwebrenderer.git /data/ucov/repro/spark/Clients/nla/jwebrenderer
git clone --depth 1 https://github.com/l0stmyself/da650samplecode.git /data/ucov/repro/spark/Clients/l0stmyself/da650samplecode
git clone --depth 1 https://github.com/cs0320-f2021/project-1-dy7cypw9wkaddvsp-fouw4ytpien6np1-rh7cycrnldgcxees.git /data/ucov/repro/spark/Clients/cs0320-f2021/project-1-dy7cypw9wkaddvsp-fouw4ytpien6np1-rh7cycrnldgcxees
git clone --depth 1 https://github.com/zhoupan/jooq-android.git /data/ucov/repro/spark/Clients/zhoupan/jooq-android
git clone --depth 1 https://github.com/BJM19/AREP-LAB01-NTRODUCCION-MVN-GIT-Y-HEROKU.git /data/ucov/repro/spark/Clients/BJM19/AREP-LAB01-NTRODUCCION-MVN-GIT-Y-HEROKU
git clone --depth 1 https://github.com/SumaVarshitha/assessmentdocker.git /data/ucov/repro/spark/Clients/SumaVarshitha/assessmentdocker
git clone --depth 1 https://github.com/floptadeu/Integracao-Spark.git /data/ucov/repro/spark/Clients/floptadeu/Integracao-Spark
git clone --depth 1 https://github.com/JMDev2/WildLife-Tracker.git /data/ucov/repro/spark/Clients/JMDev2/WildLife-Tracker
git clone --depth 1 https://github.com/waqarhmad242/checkout.git /data/ucov/repro/spark/Clients/waqarhmad242/checkout
git clone --depth 1 https://github.com/rajat965ng/ApiSecurity.git /data/ucov/repro/spark/Clients/rajat965ng/ApiSecurity
git clone --depth 1 https://github.com/jjk1492/WebCheckers.git /data/ucov/repro/spark/Clients/jjk1492/WebCheckers
git clone --depth 1 https://github.com/BulgakViktoriya14/webServices.git /data/ucov/repro/spark/Clients/BulgakViktoriya14/webServices
git clone --depth 1 https://github.com/Angelica-Alfaro/AREP_TALLER4.git /data/ucov/repro/spark/Clients/Angelica-Alfaro/AREP_TALLER4
git clone --depth 1 https://github.com/sharonoloo/hero-squad.git /data/ucov/repro/spark/Clients/sharonoloo/hero-squad
git clone --depth 1 https://github.com/blakestickland/spark-java-api-demo-baeldung.git /data/ucov/repro/spark/Clients/blakestickland/spark-java-api-demo-baeldung
git clone --depth 1 https://github.com/SJ47/fooDee_ialc_version.git /data/ucov/repro/spark/Clients/SJ47/fooDee_ialc_version
git clone --depth 1 https://github.com/kevinbas12/test.git /data/ucov/repro/spark/Clients/kevinbas12/test
git clone --depth 1 https://github.com/AlenaLosk/Homework6.git /data/ucov/repro/spark/Clients/AlenaLosk/Homework6
git clone --depth 1 https://github.com/caterpillar1219/spring18-cp.git /data/ucov/repro/spark/Clients/caterpillar1219/spring18-cp
git clone --depth 1 https://github.com/ethanwong987/BearMaps.git /data/ucov/repro/spark/Clients/ethanwong987/BearMaps
git clone --depth 1 https://github.com/press0/jib.git /data/ucov/repro/spark/Clients/press0/jib
git clone --depth 1 https://github.com/nrakshaynr/jjjava.git /data/ucov/repro/spark/Clients/nrakshaynr/jjjava
git clone --depth 1 https://github.com/jojoavila/stedi-private-main.git /data/ucov/repro/spark/Clients/jojoavila/stedi-private-main
git clone --depth 1 https://github.com/QianTan214/CS61B.git /data/ucov/repro/spark/Clients/QianTan214/CS61B
git clone --depth 1 https://github.com/DamGaFlo/RoundRobin.git /data/ucov/repro/spark/Clients/DamGaFlo/RoundRobin
git clone --depth 1 https://github.com/kirbyydoge/Maven-Demo-App.git /data/ucov/repro/spark/Clients/kirbyydoge/Maven-Demo-App
git clone --depth 1 https://github.com/dhanu123456/silent.git /data/ucov/repro/spark/Clients/dhanu123456/silent
git clone --depth 1 https://github.com/integration-app/react-java-integration-examples.git /data/ucov/repro/spark/Clients/integration-app/react-java-integration-examples
git clone --depth 1 https://github.com/Arabprogrammer/Graphql.git /data/ucov/repro/spark/Clients/Arabprogrammer/Graphql
git clone --depth 1 https://github.com/mombe090/devscom-conf.universal-money.git /data/ucov/repro/spark/Clients/mombe090/devscom-conf.universal-money
git clone --depth 1 https://github.com/senpay/login-form.git /data/ucov/repro/spark/Clients/senpay/login-form
git clone --depth 1 https://github.com/cs0320-s2022/react-lab-dylanilewis.git /data/ucov/repro/spark/Clients/cs0320-s2022/react-lab-dylanilewis
git clone --depth 1 https://github.com/kuldeepsinghsekhon/laravel-custom-member-plans-permission.git /data/ucov/repro/spark/Clients/kuldeepsinghsekhon/laravel-custom-member-plans-permission
git clone --depth 1 https://github.com/cs0320-s2022/async-typescript-lab-ashley-cai.git /data/ucov/repro/spark/Clients/cs0320-s2022/async-typescript-lab-ashley-cai
git clone --depth 1 https://github.com/Nicholas-Kimutai/Wildlife-Tracking.git /data/ucov/repro/spark/Clients/Nicholas-Kimutai/Wildlife-Tracking
git clone --depth 1 https://github.com/AndyZhang1999/java-self-learning.git /data/ucov/repro/spark/Clients/AndyZhang1999/java-self-learning
git clone --depth 1 https://github.com/lucaazalim/java-wordle-game.git /data/ucov/repro/spark/Clients/lucaazalim/java-wordle-game
git clone --depth 1 https://github.com/pedroarlves/ti2.git /data/ucov/repro/spark/Clients/pedroarlves/ti2
git clone --depth 1 https://github.com/Solabaev-developer/serialRestService.git /data/ucov/repro/spark/Clients/Solabaev-developer/serialRestService
git clone --depth 1 https://github.com/JulianP-24/AREP.git /data/ucov/repro/spark/Clients/JulianP-24/AREP
git clone --depth 1 https://github.com/cs0320-s2022/react-lab-eatthepear.git /data/ucov/repro/spark/Clients/cs0320-s2022/react-lab-eatthepear
git clone --depth 1 https://github.com/PrimePlugin/PrimePlugins-BungeeAPI.git /data/ucov/repro/spark/Clients/PrimePlugin/PrimePlugins-BungeeAPI
git clone --depth 1 https://github.com/pointerless/vdmj-remote.git /data/ucov/repro/spark/Clients/pointerless/vdmj-remote
git clone --depth 1 https://github.com/knative/docs.git /data/ucov/repro/spark/Clients/knative/docs
git clone --depth 1 https://github.com/MichalSzewczyk/cse-commands-processor.git /data/ucov/repro/spark/Clients/MichalSzewczyk/cse-commands-processor
git clone --depth 1 https://github.com/comejia/utn-dds-mi-impacto-ambiental.git /data/ucov/repro/spark/Clients/comejia/utn-dds-mi-impacto-ambiental
git clone --depth 1 https://github.com/jsoref/languagetool.git /data/ucov/repro/spark/Clients/jsoref/languagetool
git clone --depth 1 https://github.com/cs0320-s2022/async-typescript-lab-sroberts0403.git /data/ucov/repro/spark/Clients/cs0320-s2022/async-typescript-lab-sroberts0403
git clone --depth 1 https://github.com/WinkyHu/BearMaps.git /data/ucov/repro/spark/Clients/WinkyHu/BearMaps
git clone --depth 1 https://github.com/castroneves/metro-bank-export-freeagent.git /data/ucov/repro/spark/Clients/castroneves/metro-bank-export-freeagent
git clone --depth 1 https://github.com/Everneth/EverMap.git /data/ucov/repro/spark/Clients/Everneth/EverMap
git clone --depth 1 https://github.com/GuadalupeJimenezCab/Sistemas-web.git /data/ucov/repro/spark/Clients/GuadalupeJimenezCab/Sistemas-web
git clone --depth 1 https://github.com/cs0320-s2022/react-lab-BrianEdmund.git /data/ucov/repro/spark/Clients/cs0320-s2022/react-lab-BrianEdmund
git clone --depth 1 https://github.com/malinkaphann/multi-module-maven-app.git /data/ucov/repro/spark/Clients/malinkaphann/multi-module-maven-app
git clone --depth 1 https://github.com/rohankumardubey/reair.git /data/ucov/repro/spark/Clients/rohankumardubey/reair
git clone --depth 1 https://github.com/jiangjiangtian/cs61b1.git /data/ucov/repro/spark/Clients/jiangjiangtian/cs61b1
git clone --depth 1 https://github.com/DeliciousDark/cs61b.git /data/ucov/repro/spark/Clients/DeliciousDark/cs61b
git clone --depth 1 https://github.com/Okellothomas/NewsPortal.git /data/ucov/repro/spark/Clients/Okellothomas/NewsPortal
git clone --depth 1 https://github.com/picknchew/coinbase-commerce-java.git /data/ucov/repro/spark/Clients/picknchew/coinbase-commerce-java
git clone --depth 1 https://github.com/acimack/schedlr.git /data/ucov/repro/spark/Clients/acimack/schedlr
git clone --depth 1 https://github.com/AtomCats/gamexapplication.git /data/ucov/repro/spark/Clients/AtomCats/gamexapplication
git clone --depth 1 https://github.com/cs0320-f2021/lab-async-js-ba5py46xjvsdxbuh.git /data/ucov/repro/spark/Clients/cs0320-f2021/lab-async-js-ba5py46xjvsdxbuh
git clone --depth 1 https://github.com/kovacshuni/koauth-samples.git /data/ucov/repro/spark/Clients/kovacshuni/koauth-samples
git clone --depth 1 https://github.com/mrroin/Mrroin_Base_Backend_Java.git /data/ucov/repro/spark/Clients/mrroin/Mrroin_Base_Backend_Java
git clone --depth 1 https://github.com/JamesSanderslawnmasters/placing-a-hold.git /data/ucov/repro/spark/Clients/JamesSanderslawnmasters/placing-a-hold
git clone --depth 1 https://github.com/Phandung1312/PBL4.git /data/ucov/repro/spark/Clients/Phandung1312/PBL4
git clone --depth 1 https://github.com/newrol/hopper.git /data/ucov/repro/spark/Clients/newrol/hopper
git clone --depth 1 https://github.com/cynthiaqntna/aemet.git /data/ucov/repro/spark/Clients/cynthiaqntna/aemet
git clone --depth 1 https://github.com/ShupeiLi/CS61B.git /data/ucov/repro/spark/Clients/ShupeiLi/CS61B
git clone --depth 1 https://github.com/antonismaitis/java-spark.git /data/ucov/repro/spark/Clients/antonismaitis/java-spark
git clone --depth 1 https://github.com/spiderChow/Pacman.git /data/ucov/repro/spark/Clients/spiderChow/Pacman
git clone --depth 1 https://github.com/gustavo-silvestr/tibd2.git /data/ucov/repro/spark/Clients/gustavo-silvestr/tibd2
git clone --depth 1 https://github.com/emaphis/JavaModules.git /data/ucov/repro/spark/Clients/emaphis/JavaModules
git clone --depth 1 https://github.com/VladuTzZ-sudo/DB_homework.git /data/ucov/repro/spark/Clients/VladuTzZ-sudo/DB_homework
git clone --depth 1 https://github.com/mlee212/rabbit.git /data/ucov/repro/spark/Clients/mlee212/rabbit
git clone --depth 1 https://github.com/SValentyn/Payment-Management-System.git /data/ucov/repro/spark/Clients/SValentyn/Payment-Management-System
git clone --depth 1 https://github.com/tomasanchez/paw-rescue.git /data/ucov/repro/spark/Clients/tomasanchez/paw-rescue
git clone --depth 1 https://github.com/manh26x/spark-kotlin.git /data/ucov/repro/spark/Clients/manh26x/spark-kotlin
git clone --depth 1 https://github.com/Juanda171217/docker.git /data/ucov/repro/spark/Clients/Juanda171217/docker
git clone --depth 1 https://github.com/cihar29/insight.git /data/ucov/repro/spark/Clients/cihar29/insight
git clone --depth 1 https://github.com/Burak-37/abgabe12.git /data/ucov/repro/spark/Clients/Burak-37/abgabe12
git clone --depth 1 https://github.com/singhbipinb/Movie-Recommendation.git /data/ucov/repro/spark/Clients/singhbipinb/Movie-Recommendation
git clone --depth 1 https://github.com/anika-ahluwalia/mapdash.git /data/ucov/repro/spark/Clients/anika-ahluwalia/mapdash
git clone --depth 1 https://github.com/coke2021/cs61b.git /data/ucov/repro/spark/Clients/coke2021/cs61b
git clone --depth 1 https://github.com/AbdulRahman7862/Java-Email-SMS-Sender.git /data/ucov/repro/spark/Clients/AbdulRahman7862/Java-Email-SMS-Sender
git clone --depth 1 https://github.com/csh2830/guessing-game.git /data/ucov/repro/spark/Clients/csh2830/guessing-game
git clone --depth 1 https://github.com/jiejie08/Java.git /data/ucov/repro/spark/Clients/jiejie08/Java
git clone --depth 1 https://github.com/rkcho317/proj531.git /data/ucov/repro/spark/Clients/rkcho317/proj531
git clone --depth 1 https://github.com/Demongo2009/PROZ_Communicator.git /data/ucov/repro/spark/Clients/Demongo2009/PROZ_Communicator
git clone --depth 1 https://github.com/samuelkhong/OpenStreetMaps.git /data/ucov/repro/spark/Clients/samuelkhong/OpenStreetMaps
git clone --depth 1 https://github.com/fernando-b15/SparkWebApp.git /data/ucov/repro/spark/Clients/fernando-b15/SparkWebApp
git clone --depth 1 https://github.com/Itera/avdelingstur_okt2019.git /data/ucov/repro/spark/Clients/Itera/avdelingstur_okt2019
git clone --depth 1 https://github.com/cs0320-f2021/project-1-5pzjmlr1eimp0jjw-arsatpwutcfuasdw-qmccfdvbvse5abfe.git /data/ucov/repro/spark/Clients/cs0320-f2021/project-1-5pzjmlr1eimp0jjw-arsatpwutcfuasdw-qmccfdvbvse5abfe
git clone --depth 1 https://github.com/githiomi/Hero_Squad.git /data/ucov/repro/spark/Clients/githiomi/Hero_Squad
git clone --depth 1 https://github.com/pdlai/duck.git /data/ucov/repro/spark/Clients/pdlai/duck
git clone --depth 1 https://github.com/BennettMoore/Webcheckers-School-Project.git /data/ucov/repro/spark/Clients/BennettMoore/Webcheckers-School-Project
git clone --depth 1 https://github.com/siqiye/cs61b.git /data/ucov/repro/spark/Clients/siqiye/cs61b
git clone --depth 1 https://github.com/germanAOQ/AREP-Parcial2-EC2.git /data/ucov/repro/spark/Clients/germanAOQ/AREP-Parcial2-EC2
git clone --depth 1 https://github.com/CharafeddineMechalikh/recap.git /data/ucov/repro/spark/Clients/CharafeddineMechalikh/recap
git clone --depth 1 https://github.com/bobbinnej/Rangers-Tracker-for-Wildlife.git /data/ucov/repro/spark/Clients/bobbinnej/Rangers-Tracker-for-Wildlife
git clone --depth 1 https://github.com/CeliaJSLau/elasticsearch-demo.git /data/ucov/repro/spark/Clients/CeliaJSLau/elasticsearch-demo
git clone --depth 1 https://github.com/Ezdies/Quote_Generator.git /data/ucov/repro/spark/Clients/Ezdies/Quote_Generator
git clone --depth 1 https://github.com/yongqiangG/CS61B-Datastructur.git /data/ucov/repro/spark/Clients/yongqiangG/CS61B-Datastructur
git clone --depth 1 https://github.com/madinahmadzai2016/PaymentWeb.git /data/ucov/repro/spark/Clients/madinahmadzai2016/PaymentWeb
git clone --depth 1 https://github.com/prakashin/sparkjava-war-example.git /data/ucov/repro/spark/Clients/prakashin/sparkjava-war-example
git clone --depth 1 https://github.com/yaminijarabana/GitMavenTest.git /data/ucov/repro/spark/Clients/yaminijarabana/GitMavenTest
git clone --depth 1 https://github.com/GinAren92/ServletBlog.git /data/ucov/repro/spark/Clients/GinAren92/ServletBlog
git clone --depth 1 https://github.com/Givo-Givo/API-Rest.git /data/ucov/repro/spark/Clients/Givo-Givo/API-Rest
git clone --depth 1 https://github.com/bcs4313/WebCheckers-Project-Archived.git /data/ucov/repro/spark/Clients/bcs4313/WebCheckers-Project-Archived
git clone --depth 1 https://github.com/Gufdoor/get2play.git /data/ucov/repro/spark/Clients/Gufdoor/get2play
git clone --depth 1 https://github.com/maxrun11/CS61B-Tutorial.git /data/ucov/repro/spark/Clients/maxrun11/CS61B-Tutorial
git clone --depth 1 https://github.com/BielosX/AWS-architect.git /data/ucov/repro/spark/Clients/BielosX/AWS-architect
git clone --depth 1 https://github.com/lauraval19/AREP-AWSDOCKERintro.git /data/ucov/repro/spark/Clients/lauraval19/AREP-AWSDOCKERintro
git clone --depth 1 https://github.com/masterford/XPathCrawler.git /data/ucov/repro/spark/Clients/masterford/XPathCrawler
git clone --depth 1 https://github.com/gtm7712/team-project-d-2191-swen-261-11-d.git /data/ucov/repro/spark/Clients/gtm7712/team-project-d-2191-swen-261-11-d
git clone --depth 1 https://github.com/benjagm/simple-spark-api-playground.git /data/ucov/repro/spark/Clients/benjagm/simple-spark-api-playground
git clone --depth 1 https://github.com/emrah44/searchcode-server.git /data/ucov/repro/spark/Clients/emrah44/searchcode-server
git clone --depth 1 https://github.com/jrangu/twitter.git /data/ucov/repro/spark/Clients/jrangu/twitter
git clone --depth 1 https://github.com/stefania5964/taller5.git /data/ucov/repro/spark/Clients/stefania5964/taller5
git clone --depth 1 https://github.com/vmalik800/https-github.com-vmalik800-sparkjava-war-example.git /data/ucov/repro/spark/Clients/vmalik800/https-github.com-vmalik800-sparkjava-war-example
git clone --depth 1 https://github.com/jbromero/PruebaRestfulJavaScript.git /data/ucov/repro/spark/Clients/jbromero/PruebaRestfulJavaScript
git clone --depth 1 https://github.com/liangli16/CS61B.git /data/ucov/repro/spark/Clients/liangli16/CS61B
git clone --depth 1 https://github.com/yimumengke/CS61B-Tutorial.git /data/ucov/repro/spark/Clients/yimumengke/CS61B-Tutorial
git clone --depth 1 https://github.com/tiagohpf/thesis-2018-2019.git /data/ucov/repro/spark/Clients/tiagohpf/thesis-2018-2019
git clone --depth 1 https://github.com/cs0320-s2022/async-typescript-lab-willguo0.git /data/ucov/repro/spark/Clients/cs0320-s2022/async-typescript-lab-willguo0
git clone --depth 1 https://github.com/onlythenaive/javaschool-ittunes.git /data/ucov/repro/spark/Clients/onlythenaive/javaschool-ittunes
git clone --depth 1 https://github.com/sebChevre/ADSB-Project.git /data/ucov/repro/spark/Clients/sebChevre/ADSB-Project
git clone --depth 1 https://github.com/jpmeireles08/TI2.git /data/ucov/repro/spark/Clients/jpmeireles08/TI2
git clone --depth 1 https://github.com/Carol110905/SistemasWeb.git /data/ucov/repro/spark/Clients/Carol110905/SistemasWeb
git clone --depth 1 https://github.com/ceshiren/HogwartsJava4.git /data/ucov/repro/spark/Clients/ceshiren/HogwartsJava4
git clone --depth 1 https://github.com/CesarRawr/Todos.git /data/ucov/repro/spark/Clients/CesarRawr/Todos
git clone --depth 1 https://github.com/MatosJM/Calculadora-web-socket.git /data/ucov/repro/spark/Clients/MatosJM/Calculadora-web-socket
git clone --depth 1 https://github.com/newrelic-experimental/newrelic-webhook-to-snmp-trap-java.git /data/ucov/repro/spark/Clients/newrelic-experimental/newrelic-webhook-to-snmp-trap-java
git clone --depth 1 https://github.com/cs0320-s2022/async-typescript-lab-yuqinan.git /data/ucov/repro/spark/Clients/cs0320-s2022/async-typescript-lab-yuqinan
git clone --depth 1 https://github.com/dsKarthick/spark-java-hello-world.git /data/ucov/repro/spark/Clients/dsKarthick/spark-java-hello-world
git clone --depth 1 https://github.com/mlalma/CFTA.git /data/ucov/repro/spark/Clients/mlalma/CFTA
git clone --depth 1 https://github.com/2022-SEMII-DESIV-G1/espino-isaias.git /data/ucov/repro/spark/Clients/2022-SEMII-DESIV-G1/espino-isaias
git clone --depth 1 https://github.com/Maada/projet_java.git /data/ucov/repro/spark/Clients/Maada/projet_java
git clone --depth 1 https://github.com/nietus/spark_crud.git /data/ucov/repro/spark/Clients/nietus/spark_crud
git clone --depth 1 https://github.com/y3h7rv/cs61b.git /data/ucov/repro/spark/Clients/y3h7rv/cs61b
git clone --depth 1 https://github.com/Killersys/AREP-Parcial1T.git /data/ucov/repro/spark/Clients/Killersys/AREP-Parcial1T
git clone --depth 1 https://github.com/SantiagoECHM/80640.git /data/ucov/repro/spark/Clients/SantiagoECHM/80640
git clone --depth 1 https://github.com/FarhanAxiq/Tour-Website-App.git /data/ucov/repro/spark/Clients/FarhanAxiq/Tour-Website-App
git clone --depth 1 https://github.com/ampyjoe/TuneTypes.git /data/ucov/repro/spark/Clients/ampyjoe/TuneTypes
git clone --depth 1 https://github.com/BMaxi6/gesoc.git /data/ucov/repro/spark/Clients/BMaxi6/gesoc
git clone --depth 1 https://github.com/SergioRt1/INTRODUCTION-TO-COMPLEX-SYSTEMS.git /data/ucov/repro/spark/Clients/SergioRt1/INTRODUCTION-TO-COMPLEX-SYSTEMS
git clone --depth 1 https://github.com/blur-blue/SparkMavenProject-1-Error-Include.git /data/ucov/repro/spark/Clients/blur-blue/SparkMavenProject-1-Error-Include
git clone --depth 1 https://github.com/DevOpsSpti/AssetManagement.git /data/ucov/repro/spark/Clients/DevOpsSpti/AssetManagement
git clone --depth 1 https://github.com/cs0320-f2021/lab-front-end-9VsCfZ5sPjUMRp.git /data/ucov/repro/spark/Clients/cs0320-f2021/lab-front-end-9VsCfZ5sPjUMRp
git clone --depth 1 https://github.com/normalek/money-transfers.git /data/ucov/repro/spark/Clients/normalek/money-transfers
git clone --depth 1 https://github.com/jie567/cs61b.git /data/ucov/repro/spark/Clients/jie567/cs61b
git clone --depth 1 https://github.com/hermanpt/QA_Programming.git /data/ucov/repro/spark/Clients/hermanpt/QA_Programming
git clone --depth 1 https://github.com/Justin-Ng-SF/tic-tac-toe.git /data/ucov/repro/spark/Clients/Justin-Ng-SF/tic-tac-toe
git clone --depth 1 https://github.com/doublEeVil/SimpleDev.git /data/ucov/repro/spark/Clients/doublEeVil/SimpleDev
git clone --depth 1 https://github.com/ChuleHou/PacMan.git /data/ucov/repro/spark/Clients/ChuleHou/PacMan
git clone --depth 1 https://github.com/saschpe/jib.git /data/ucov/repro/spark/Clients/saschpe/jib
git clone --depth 1 https://github.com/vichhaiyserey/docker-compose-nginx-jfrog.git /data/ucov/repro/spark/Clients/vichhaiyserey/docker-compose-nginx-jfrog
git clone --depth 1 https://github.com/TimSquire/TechConference.git /data/ucov/repro/spark/Clients/TimSquire/TechConference
git clone --depth 1 https://github.com/Daniel9842/ParcialArep2Corte.git /data/ucov/repro/spark/Clients/Daniel9842/ParcialArep2Corte
git clone --depth 1 https://github.com/rahulkanuparthi/rahul-testing.git /data/ucov/repro/spark/Clients/rahulkanuparthi/rahul-testing
git clone --depth 1 https://github.com/cs0320-s2022/async-typescript-lab-ann2002g.git /data/ucov/repro/spark/Clients/cs0320-s2022/async-typescript-lab-ann2002g
git clone --depth 1 https://github.com/latte-french/transactionservice.git /data/ucov/repro/spark/Clients/latte-french/transactionservice
git clone --depth 1 https://github.com/OnHenriGolera/Astro.git /data/ucov/repro/spark/Clients/OnHenriGolera/Astro
git clone --depth 1 https://github.com/kurokawa5/subscription-use-cases.git /data/ucov/repro/spark/Clients/kurokawa5/subscription-use-cases
git clone --depth 1 https://github.com/11manu96/comp504-H7.git /data/ucov/repro/spark/Clients/11manu96/comp504-H7
git clone --depth 1 https://github.com/mariahv9/SecureAppAREP.git /data/ucov/repro/spark/Clients/mariahv9/SecureAppAREP
git clone --depth 1 https://github.com/Kishore-08/ase1.git /data/ucov/repro/spark/Clients/Kishore-08/ase1
git clone --depth 1 https://github.com/italia/daf-cacher.git /data/ucov/repro/spark/Clients/italia/daf-cacher
git clone --depth 1 https://github.com/jorecat/csci-366-fall2021-private.git /data/ucov/repro/spark/Clients/jorecat/csci-366-fall2021-private
git clone --depth 1 https://github.com/cs0320-f2021/lab-apis-h2323547425.git /data/ucov/repro/spark/Clients/cs0320-f2021/lab-apis-h2323547425
git clone --depth 1 https://github.com/PedroMathieu/ES-LETI-1Sem-2022-Grupo-11.git /data/ucov/repro/spark/Clients/PedroMathieu/ES-LETI-1Sem-2022-Grupo-11
git clone --depth 1 https://github.com/alpescraft/functional-core-session.git /data/ucov/repro/spark/Clients/alpescraft/functional-core-session
git clone --depth 1 https://github.com/YashasRajuN/BYZCUIT_FORK.git /data/ucov/repro/spark/Clients/YashasRajuN/BYZCUIT_FORK
git clone --depth 1 https://github.com/yuanl22/CS61B.git /data/ucov/repro/spark/Clients/yuanl22/CS61B
git clone --depth 1 https://github.com/marceloivob/VRPL.git /data/ucov/repro/spark/Clients/marceloivob/VRPL
git clone --depth 1 https://github.com/anushakvinay/testing.git /data/ucov/repro/spark/Clients/anushakvinay/testing
git clone --depth 1 https://github.com/violethaze74/awesome-compose.git /data/ucov/repro/spark/Clients/violethaze74/awesome-compose
git clone --depth 1 https://github.com/paolosecci/springBootMVC.git /data/ucov/repro/spark/Clients/paolosecci/springBootMVC
git clone --depth 1 https://github.com/Okellothomas/hero-squad.git /data/ucov/repro/spark/Clients/Okellothomas/hero-squad
git clone --depth 1 https://github.com/dds-utn/unisocial-spark.git /data/ucov/repro/spark/Clients/dds-utn/unisocial-spark
git clone --depth 1 https://github.com/roquebajosexto/DOTT.git /data/ucov/repro/spark/Clients/roquebajosexto/DOTT
git clone --depth 1 https://github.com/yyudji/ex-spark-crud.git /data/ucov/repro/spark/Clients/yyudji/ex-spark-crud
git clone --depth 1 https://github.com/emarcosgv/Tp-Disenio-2020-Gesoc.git /data/ucov/repro/spark/Clients/emarcosgv/Tp-Disenio-2020-Gesoc
