./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Tiefkuehlpizze/OABXDecrypt" > /data/ucov/repro/commons-cli/ClientInfos/Tiefkuehlpizze______OABXDecrypt.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/weihsin2002/IBQuantTrade" > /data/ucov/repro/commons-cli/ClientInfos/weihsin2002______IBQuantTrade.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/tnapat2000/ZorkArtOnline" > /data/ucov/repro/commons-cli/ClientInfos/tnapat2000______ZorkArtOnline.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/safrant/robot" > /data/ucov/repro/commons-cli/ClientInfos/safrant______robot.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/renjieliu/raspberrypi" > /data/ucov/repro/commons-cli/ClientInfos/renjieliu______raspberrypi.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/flpfraga/Solid-UseCase-DesbravandoSolid" > /data/ucov/repro/commons-cli/ClientInfos/flpfraga______Solid-UseCase-DesbravandoSolid.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/caoluobin/rocketmq-4.8" > /data/ucov/repro/commons-cli/ClientInfos/caoluobin______rocketmq-4.8.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/orbisgis/framework" > /data/ucov/repro/commons-cli/ClientInfos/orbisgis______framework.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/marrodoso/Acme-Jobs" > /data/ucov/repro/commons-cli/ClientInfos/marrodoso______Acme-Jobs.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/orgTestCodacy11KRepos110MB/repo-9310-metron" > /data/ucov/repro/commons-cli/ClientInfos/orgTestCodacy11KRepos110MB______repo-9310-metron.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/SimonHofmeister1992/HSP-Project-AlphaZero-Reversi" > /data/ucov/repro/commons-cli/ClientInfos/SimonHofmeister1992______HSP-Project-AlphaZero-Reversi.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/paul-huber1999/Paul_thesis2022" > /data/ucov/repro/commons-cli/ClientInfos/paul-huber1999______Paul_thesis2022.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/archangelproject/JDreamsKit" > /data/ucov/repro/commons-cli/ClientInfos/archangelproject______JDreamsKit.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/carol233/SDKUpdateMining" > /data/ucov/repro/commons-cli/ClientInfos/carol233______SDKUpdateMining.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/LionelBK/libreplanSoapui" > /data/ucov/repro/commons-cli/ClientInfos/LionelBK______libreplanSoapui.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/lukoou3/flink-1.12-source" > /data/ucov/repro/commons-cli/ClientInfos/lukoou3______flink-1.12-source.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Shoulaxiao/zookeeper-" > /data/ucov/repro/commons-cli/ClientInfos/Shoulaxiao______zookeeper-.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/jexxa-projects/JexxaTutorials" > /data/ucov/repro/commons-cli/ClientInfos/jexxa-projects______JexxaTutorials.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/bsamarnath/testamar1" > /data/ucov/repro/commons-cli/ClientInfos/bsamarnath______testamar1.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/sa-group-yzz/SQLAnalysis" > /data/ucov/repro/commons-cli/ClientInfos/sa-group-yzz______SQLAnalysis.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/gn20018/GradesUTP" > /data/ucov/repro/commons-cli/ClientInfos/gn20018______GradesUTP.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/maribelrb22/Acme-One" > /data/ucov/repro/commons-cli/ClientInfos/maribelrb22______Acme-One.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/shannah/jdeploy" > /data/ucov/repro/commons-cli/ClientInfos/shannah______jdeploy.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/WinterSilence/swagger-codegen" > /data/ucov/repro/commons-cli/ClientInfos/WinterSilence______swagger-codegen.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/CyberFlameGO/OpenTripPlanner" > /data/ucov/repro/commons-cli/ClientInfos/CyberFlameGO______OpenTripPlanner.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/fasten-project/incremental-maven-crawler" > /data/ucov/repro/commons-cli/ClientInfos/fasten-project______incremental-maven-crawler.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/samq-ghdemo/hadoop" > /data/ucov/repro/commons-cli/ClientInfos/samq-ghdemo______hadoop.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/alibenmessaoud/JSF-Application-that-uses-managed-bean-and-ejb" > /data/ucov/repro/commons-cli/ClientInfos/alibenmessaoud______JSF-Application-that-uses-managed-bean-and-ejb.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ekmixon/nifi" > /data/ucov/repro/commons-cli/ClientInfos/ekmixon______nifi.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/dd-test5/ripme" > /data/ucov/repro/commons-cli/ClientInfos/dd-test5______ripme.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/FDSInfoMontp-HAI916I-GLIA/TP1" > /data/ucov/repro/commons-cli/ClientInfos/FDSInfoMontp-HAI916I-GLIA______TP1.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/google/infra-structured-map" > /data/ucov/repro/commons-cli/ClientInfos/google______infra-structured-map.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Rindadevi/apachetomcat" > /data/ucov/repro/commons-cli/ClientInfos/Rindadevi______apachetomcat.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/todd-fritz/ldap_in_memory" > /data/ucov/repro/commons-cli/ClientInfos/todd-fritz______ldap_in_memory.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/zhining-lu/netty-quic-proxy" > /data/ucov/repro/commons-cli/ClientInfos/zhining-lu______netty-quic-proxy.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/SeppPenner/openapi-generator" > /data/ucov/repro/commons-cli/ClientInfos/SeppPenner______openapi-generator.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ruofanxing/webmagic" > /data/ucov/repro/commons-cli/ClientInfos/ruofanxing______webmagic.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/qitianfeng/rocketmq-new" > /data/ucov/repro/commons-cli/ClientInfos/qitianfeng______rocketmq-new.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/hata6502/verilog-format" > /data/ucov/repro/commons-cli/ClientInfos/hata6502______verilog-format.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/isaaceindhoven/swagger-docgen" > /data/ucov/repro/commons-cli/ClientInfos/isaaceindhoven______swagger-docgen.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/harshaputtaswamy/aai-common" > /data/ucov/repro/commons-cli/ClientInfos/harshaputtaswamy______aai-common.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/tkcmada/athena-kdb3" > /data/ucov/repro/commons-cli/ClientInfos/tkcmada______athena-kdb3.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/FedorBelyakoff/CabdiagFormatter" > /data/ucov/repro/commons-cli/ClientInfos/FedorBelyakoff______CabdiagFormatter.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/xwzl/nacos" > /data/ucov/repro/commons-cli/ClientInfos/xwzl______nacos.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Indhumathi397/Bills2U_TestNG_Updated" > /data/ucov/repro/commons-cli/ClientInfos/Indhumathi397______Bills2U_TestNG_Updated.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/2lambda123/odc" > /data/ucov/repro/commons-cli/ClientInfos/2lambda123______odc.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/adfwer233/ThssDB" > /data/ucov/repro/commons-cli/ClientInfos/adfwer233______ThssDB.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ep-infosec/33_apache_druid" > /data/ucov/repro/commons-cli/ClientInfos/ep-infosec______33_apache_druid.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/avineshwar/tutorials" > /data/ucov/repro/commons-cli/ClientInfos/avineshwar______tutorials.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/vaginessa/uber-apk-signer" > /data/ucov/repro/commons-cli/ClientInfos/vaginessa______uber-apk-signer.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/miven/nlp4" > /data/ucov/repro/commons-cli/ClientInfos/miven______nlp4.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/bbrk364/ha-nva" > /data/ucov/repro/commons-cli/ClientInfos/bbrk364______ha-nva.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/dwu/schema-compatibility" > /data/ucov/repro/commons-cli/ClientInfos/dwu______schema-compatibility.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/changjinjin/woven-dsp" > /data/ucov/repro/commons-cli/ClientInfos/changjinjin______woven-dsp.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Techatonic/Sudoku" > /data/ucov/repro/commons-cli/ClientInfos/Techatonic______Sudoku.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/malomarrec/openapi-generator" > /data/ucov/repro/commons-cli/ClientInfos/malomarrec______openapi-generator.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/hellokwmin/apollo" > /data/ucov/repro/commons-cli/ClientInfos/hellokwmin______apollo.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/kamaux0r/athenz" > /data/ucov/repro/commons-cli/ClientInfos/kamaux0r______athenz.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/qbox/spark-1" > /data/ucov/repro/commons-cli/ClientInfos/qbox______spark-1.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/yolee20/fabric-sdk-java" > /data/ucov/repro/commons-cli/ClientInfos/yolee20______fabric-sdk-java.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/pl89/bootstrap-simulation" > /data/ucov/repro/commons-cli/ClientInfos/pl89______bootstrap-simulation.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/AngeloFerrando/3-valuedSL" > /data/ucov/repro/commons-cli/ClientInfos/AngeloFerrando______3-valuedSL.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/aerogear/ups-mock-data-loader" > /data/ucov/repro/commons-cli/ClientInfos/aerogear______ups-mock-data-loader.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/jeromgonch/job_test_task_telnet_server" > /data/ucov/repro/commons-cli/ClientInfos/jeromgonch______job_test_task_telnet_server.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/JoKrus/j-chess-server" > /data/ucov/repro/commons-cli/ClientInfos/JoKrus______j-chess-server.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/dicastro/financemanager" > /data/ucov/repro/commons-cli/ClientInfos/dicastro______financemanager.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/banxue-dev/bxmall-backend" > /data/ucov/repro/commons-cli/ClientInfos/banxue-dev______bxmall-backend.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/fagnercandido/pocquinha-strategy-factory-supplier" > /data/ucov/repro/commons-cli/ClientInfos/fagnercandido______pocquinha-strategy-factory-supplier.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/apigee/usergrid-benchmark" > /data/ucov/repro/commons-cli/ClientInfos/apigee______usergrid-benchmark.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Jesperoka/AISTRE-labs" > /data/ucov/repro/commons-cli/ClientInfos/Jesperoka______AISTRE-labs.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/flink-extended/flink-remote-shuffle" > /data/ucov/repro/commons-cli/ClientInfos/flink-extended______flink-remote-shuffle.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/BrotherCao/MYDB" > /data/ucov/repro/commons-cli/ClientInfos/BrotherCao______MYDB.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/MilanPodunavac/IZ-Projekat" > /data/ucov/repro/commons-cli/ClientInfos/MilanPodunavac______IZ-Projekat.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/FelixDes/SimpleServletContainer" > /data/ucov/repro/commons-cli/ClientInfos/FelixDes______SimpleServletContainer.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/smakesoska1/Application_for_Kindergarden" > /data/ucov/repro/commons-cli/ClientInfos/smakesoska1______Application_for_Kindergarden.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/chandnigit/Demo202022" > /data/ucov/repro/commons-cli/ClientInfos/chandnigit______Demo202022.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/UIC-InDeXLab/CoverageICDE" > /data/ucov/repro/commons-cli/ClientInfos/UIC-InDeXLab______CoverageICDE.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Reshape-skew-handle/reshape-on-flink" > /data/ucov/repro/commons-cli/ClientInfos/Reshape-skew-handle______reshape-on-flink.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/senzhu/fNet" > /data/ucov/repro/commons-cli/ClientInfos/senzhu______fNet.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/15Ibans/MinecraftLogSearcher" > /data/ucov/repro/commons-cli/ClientInfos/15Ibans______MinecraftLogSearcher.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/chakaiduany/gcptraining" > /data/ucov/repro/commons-cli/ClientInfos/chakaiduany______gcptraining.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/mathieu-dossantos/TD-Sudoku" > /data/ucov/repro/commons-cli/ClientInfos/mathieu-dossantos______TD-Sudoku.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/wrote-code/my-utils" > /data/ucov/repro/commons-cli/ClientInfos/wrote-code______my-utils.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/glycoinfo/GlycanFormatConverter-cli" > /data/ucov/repro/commons-cli/ClientInfos/glycoinfo______GlycanFormatConverter-cli.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/VietAnh1508/boost-up-program-hands-on-lab" > /data/ucov/repro/commons-cli/ClientInfos/VietAnh1508______boost-up-program-hands-on-lab.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/LuKasMitK/OpenTripPlanner" > /data/ucov/repro/commons-cli/ClientInfos/LuKasMitK______OpenTripPlanner.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/rohankumardubey/nitmproxy" > /data/ucov/repro/commons-cli/ClientInfos/rohankumardubey______nitmproxy.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/hehuiyuan/pravegatest" > /data/ucov/repro/commons-cli/ClientInfos/hehuiyuan______pravegatest.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/smurf667/qrio" > /data/ucov/repro/commons-cli/ClientInfos/smurf667______qrio.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ttqs5/alibabacloud-hologres-connectors" > /data/ucov/repro/commons-cli/ClientInfos/ttqs5______alibabacloud-hologres-connectors.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/gearsofcode-tech/andromda" > /data/ucov/repro/commons-cli/ClientInfos/gearsofcode-tech______andromda.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/JamesAreuming/PosManager" > /data/ucov/repro/commons-cli/ClientInfos/JamesAreuming______PosManager.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/chlustanec/trial" > /data/ucov/repro/commons-cli/ClientInfos/chlustanec______trial.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/janothan/invalid-url-check" > /data/ucov/repro/commons-cli/ClientInfos/janothan______invalid-url-check.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/eschult2001/wso2-synapse" > /data/ucov/repro/commons-cli/ClientInfos/eschult2001______wso2-synapse.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ShadiaBaroud/sh" > /data/ucov/repro/commons-cli/ClientInfos/ShadiaBaroud______sh.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Projet-annuel-3AL2/organization-app" > /data/ucov/repro/commons-cli/ClientInfos/Projet-annuel-3AL2______organization-app.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/kunterbunt2/song.master" > /data/ucov/repro/commons-cli/ClientInfos/kunterbunt2______song.master.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ghas-results/imhotep-builder-jira" > /data/ucov/repro/commons-cli/ClientInfos/ghas-results______imhotep-builder-jira.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/afarago/SLCEE-2023-PC" > /data/ucov/repro/commons-cli/ClientInfos/afarago______SLCEE-2023-PC.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/gaetronik/openapi-generator" > /data/ucov/repro/commons-cli/ClientInfos/gaetronik______openapi-generator.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/thosakwe/calclang_old" > /data/ucov/repro/commons-cli/ClientInfos/thosakwe______calclang_old.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/BeeInIT/smartstadium" > /data/ucov/repro/commons-cli/ClientInfos/BeeInIT______smartstadium.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/tbee/xml2xxx" > /data/ucov/repro/commons-cli/ClientInfos/tbee______xml2xxx.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/CharafeddineMechalikh/recap" > /data/ucov/repro/commons-cli/ClientInfos/CharafeddineMechalikh______recap.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/mohit9494/kafka-spark-streaming" > /data/ucov/repro/commons-cli/ClientInfos/mohit9494______kafka-spark-streaming.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/GiorgosMandi/ER-Algorithms" > /data/ucov/repro/commons-cli/ClientInfos/GiorgosMandi______ER-Algorithms.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/sunchengxuanivy/flink-gcs" > /data/ucov/repro/commons-cli/ClientInfos/sunchengxuanivy______flink-gcs.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/lgc523/infra-java" > /data/ucov/repro/commons-cli/ClientInfos/lgc523______infra-java.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/hsbugreports/zookeeper_test" > /data/ucov/repro/commons-cli/ClientInfos/hsbugreports______zookeeper_test.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/phaqueue/nfview2" > /data/ucov/repro/commons-cli/ClientInfos/phaqueue______nfview2.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/xuechun-fan/SpringFramework" > /data/ucov/repro/commons-cli/ClientInfos/xuechun-fan______SpringFramework.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/prabhagaranks/pinot-0.12.0" > /data/ucov/repro/commons-cli/ClientInfos/prabhagaranks______pinot-0.12.0.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ZP315/flink-1.14.4-source-analysis" > /data/ucov/repro/commons-cli/ClientInfos/ZP315______flink-1.14.4-source-analysis.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/roothorp/sdktest" > /data/ucov/repro/commons-cli/ClientInfos/roothorp______sdktest.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/leberzy/rocketmq-sub" > /data/ucov/repro/commons-cli/ClientInfos/leberzy______rocketmq-sub.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/fanyi-zhao/COLA" > /data/ucov/repro/commons-cli/ClientInfos/fanyi-zhao______COLA.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/cnxtech/amazon-neptune-gremlin-java-sigv4" > /data/ucov/repro/commons-cli/ClientInfos/cnxtech______amazon-neptune-gremlin-java-sigv4.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/shrumit/timetable-scraper-java" > /data/ucov/repro/commons-cli/ClientInfos/shrumit______timetable-scraper-java.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/stgztsw/datax" > /data/ucov/repro/commons-cli/ClientInfos/stgztsw______datax.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/letterkey/spark" > /data/ucov/repro/commons-cli/ClientInfos/letterkey______spark.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ic-xu/octopus-parent" > /data/ucov/repro/commons-cli/ClientInfos/ic-xu______octopus-parent.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/GuilhermeMunizReis/ADS_GuilhermeMuniz" > /data/ucov/repro/commons-cli/ClientInfos/GuilhermeMunizReis______ADS_GuilhermeMuniz.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/gus-gu/sample-project" > /data/ucov/repro/commons-cli/ClientInfos/gus-gu______sample-project.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/teddywing/pdf-form-replace-font2" > /data/ucov/repro/commons-cli/ClientInfos/teddywing______pdf-form-replace-font2.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/badlocale/HashSnail-Server" > /data/ucov/repro/commons-cli/ClientInfos/badlocale______HashSnail-Server.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/crotwell/recFunc" > /data/ucov/repro/commons-cli/ClientInfos/crotwell______recFunc.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/mohamednizar/zookeeper" > /data/ucov/repro/commons-cli/ClientInfos/mohamednizar______zookeeper.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Andriivyn/ParrallelProgrammingMPI" > /data/ucov/repro/commons-cli/ClientInfos/Andriivyn______ParrallelProgrammingMPI.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Krishna168/urban-disco" > /data/ucov/repro/commons-cli/ClientInfos/Krishna168______urban-disco.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/SebLuca/SI_TEST_changbranch" > /data/ucov/repro/commons-cli/ClientInfos/SebLuca______SI_TEST_changbranch.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/SangJin23/HTML-CSS-" > /data/ucov/repro/commons-cli/ClientInfos/SangJin23______HTML-CSS-.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/hass123uk/TermIndexer" > /data/ucov/repro/commons-cli/ClientInfos/hass123uk______TermIndexer.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/chovy-3012/hdp-hive-release" > /data/ucov/repro/commons-cli/ClientInfos/chovy-3012______hdp-hive-release.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/MAG1412/maven1" > /data/ucov/repro/commons-cli/ClientInfos/MAG1412______maven1.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/LabsRS-Ref/MSEC" > /data/ucov/repro/commons-cli/ClientInfos/LabsRS-Ref______MSEC.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/sodacan-net/sodacan-cli" > /data/ucov/repro/commons-cli/ClientInfos/sodacan-net______sodacan-cli.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/jainsourabh2/googlecloudplatform" > /data/ucov/repro/commons-cli/ClientInfos/jainsourabh2______googlecloudplatform.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/boost-entropy-gcp/jarvis" > /data/ucov/repro/commons-cli/ClientInfos/boost-entropy-gcp______jarvis.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/tudelft-cda-lab/SymLoop" > /data/ucov/repro/commons-cli/ClientInfos/tudelft-cda-lab______SymLoop.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/TOSIT-IO/hadoop-old" > /data/ucov/repro/commons-cli/ClientInfos/TOSIT-IO______hadoop-old.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/sudoviz/openrasp" > /data/ucov/repro/commons-cli/ClientInfos/sudoviz______openrasp.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ace-lectures/2aa4-polymorphism-mesh" > /data/ucov/repro/commons-cli/ClientInfos/ace-lectures______2aa4-polymorphism-mesh.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/psekowsk/SeleniumWebDriverJAVA" > /data/ucov/repro/commons-cli/ClientInfos/psekowsk______SeleniumWebDriverJAVA.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/atmSuper/vue" > /data/ucov/repro/commons-cli/ClientInfos/atmSuper______vue.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/RoyFly/ppfly-module-demo" > /data/ucov/repro/commons-cli/ClientInfos/RoyFly______ppfly-module-demo.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ep-infosec/33_apache_incubator-streampark" > /data/ucov/repro/commons-cli/ClientInfos/ep-infosec______33_apache_incubator-streampark.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/AgrShashank/SSPPractiseCodes" > /data/ucov/repro/commons-cli/ClientInfos/AgrShashank______SSPPractiseCodes.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/dcmsy/eyecool-mirco-service-web" > /data/ucov/repro/commons-cli/ClientInfos/dcmsy______eyecool-mirco-service-web.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/amith123456/am1" > /data/ucov/repro/commons-cli/ClientInfos/amith123456______am1.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/gooddata/GoodData-CL" > /data/ucov/repro/commons-cli/ClientInfos/gooddata______GoodData-CL.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Rajiv-Edulapuram/tutorials" > /data/ucov/repro/commons-cli/ClientInfos/Rajiv-Edulapuram______tutorials.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ZacWolf/com.zacwolf.commons.crypto" > /data/ucov/repro/commons-cli/ClientInfos/ZacWolf______com.zacwolf.commons.crypto.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/mirkobaffo/progetto2_bookkeeper_test" > /data/ucov/repro/commons-cli/ClientInfos/mirkobaffo______progetto2_bookkeeper_test.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ducanh170920/test-nifi" > /data/ucov/repro/commons-cli/ClientInfos/ducanh170920______test-nifi.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/tedwon/rhq" > /data/ucov/repro/commons-cli/ClientInfos/tedwon______rhq.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/danmarsua1/Acme-Courses-D04" > /data/ucov/repro/commons-cli/ClientInfos/danmarsua1______Acme-Courses-D04.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/lujunfa/nacos_review" > /data/ucov/repro/commons-cli/ClientInfos/lujunfa______nacos_review.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/DiegoHorrilloDuran/Acme-Work-Plans-D03" > /data/ucov/repro/commons-cli/ClientInfos/DiegoHorrilloDuran______Acme-Work-Plans-D03.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/friskluft/benchmarks" > /data/ucov/repro/commons-cli/ClientInfos/friskluft______benchmarks.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/cvlucian/threadfix" > /data/ucov/repro/commons-cli/ClientInfos/cvlucian______threadfix.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/don-the-data-guy/DataAssetStream" > /data/ucov/repro/commons-cli/ClientInfos/don-the-data-guy______DataAssetStream.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/sjoerdboerhout/Prova" > /data/ucov/repro/commons-cli/ClientInfos/sjoerdboerhout______Prova.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Sonja-Parabucki/biblioteka" > /data/ucov/repro/commons-cli/ClientInfos/Sonja-Parabucki______biblioteka.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/sjtu-sail/ops-hadoop" > /data/ucov/repro/commons-cli/ClientInfos/sjtu-sail______ops-hadoop.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/sohailzahid/web-log-parser" > /data/ucov/repro/commons-cli/ClientInfos/sohailzahid______web-log-parser.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/apache/incubator-uniffle" > /data/ucov/repro/commons-cli/ClientInfos/apache______incubator-uniffle.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/mitchamador/volksroutenrechner-journal" > /data/ucov/repro/commons-cli/ClientInfos/mitchamador______volksroutenrechner-journal.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/SuJingyu111/flink_simplified_cached" > /data/ucov/repro/commons-cli/ClientInfos/SuJingyu111______flink_simplified_cached.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Blooof/Mks2MqttReporter" > /data/ucov/repro/commons-cli/ClientInfos/Blooof______Mks2MqttReporter.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/joshlong-attic/podcast-production-pipeline-shell" > /data/ucov/repro/commons-cli/ClientInfos/joshlong-attic______podcast-production-pipeline-shell.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/AMARJOLLET/Myfirstsoaptest" > /data/ucov/repro/commons-cli/ClientInfos/AMARJOLLET______Myfirstsoaptest.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/nicobritos/uni-ss-tp1-2021q1" > /data/ucov/repro/commons-cli/ClientInfos/nicobritos______uni-ss-tp1-2021q1.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/numberly/avro" > /data/ucov/repro/commons-cli/ClientInfos/numberly______avro.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Dimonium-239/ElevatorSystem" > /data/ucov/repro/commons-cli/ClientInfos/Dimonium-239______ElevatorSystem.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ValeriaFasciana/ingsw2022-AM02" > /data/ucov/repro/commons-cli/ClientInfos/ValeriaFasciana______ingsw2022-AM02.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/venugrk/shared" > /data/ucov/repro/commons-cli/ClientInfos/venugrk______shared.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/winnedatsch/wu-bachelor-thesis" > /data/ucov/repro/commons-cli/ClientInfos/winnedatsch______wu-bachelor-thesis.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ASSERT-KTH/collector-sahab-experiments" > /data/ucov/repro/commons-cli/ClientInfos/ASSERT-KTH______collector-sahab-experiments.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/AanshKot/IslandandCityGenerator" > /data/ucov/repro/commons-cli/ClientInfos/AanshKot______IslandandCityGenerator.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/mahmutovichana/Hotel-Reservations-App" > /data/ucov/repro/commons-cli/ClientInfos/mahmutovichana______Hotel-Reservations-App.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/sskmscss/um-service" > /data/ucov/repro/commons-cli/ClientInfos/sskmscss______um-service.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/wujiangchao/open-mq" > /data/ucov/repro/commons-cli/ClientInfos/wujiangchao______open-mq.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/gitgoose/core-spring-demos" > /data/ucov/repro/commons-cli/ClientInfos/gitgoose______core-spring-demos.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/cytest2021/IDEA_maven_test" > /data/ucov/repro/commons-cli/ClientInfos/cytest2021______IDEA_maven_test.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/norrishuang/Hades-Z-V3" > /data/ucov/repro/commons-cli/ClientInfos/norrishuang______Hades-Z-V3.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/vaibhav-wagaskar/Java_VSW" > /data/ucov/repro/commons-cli/ClientInfos/vaibhav-wagaskar______Java_VSW.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/azerotla2/thumbtack_online_school" > /data/ucov/repro/commons-cli/ClientInfos/azerotla2______thumbtack_online_school.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/SamKenX-Hub-Community/SAMkenxGraphScope" > /data/ucov/repro/commons-cli/ClientInfos/SamKenX-Hub-Community______SAMkenxGraphScope.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/TheNinjask/Project-Euler" > /data/ucov/repro/commons-cli/ClientInfos/TheNinjask______Project-Euler.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/maxiplux/tutorials" > /data/ucov/repro/commons-cli/ClientInfos/maxiplux______tutorials.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/IEEE-TritonsRCSC/robocup-2023" > /data/ucov/repro/commons-cli/ClientInfos/IEEE-TritonsRCSC______robocup-2023.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/JaesangPark/test" > /data/ucov/repro/commons-cli/ClientInfos/JaesangPark______test.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/fengjx/java-hot-reload-agent" > /data/ucov/repro/commons-cli/ClientInfos/fengjx______java-hot-reload-agent.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/edgallojr/igti-edc-mod2" > /data/ucov/repro/commons-cli/ClientInfos/edgallojr______igti-edc-mod2.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/nhnacademy-1st-gj/network-programming" > /data/ucov/repro/commons-cli/ClientInfos/nhnacademy-1st-gj______network-programming.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/artnaseef/opennms-poc-hs1384" > /data/ucov/repro/commons-cli/ClientInfos/artnaseef______opennms-poc-hs1384.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/RoyAl-Vitamin/Lab6" > /data/ucov/repro/commons-cli/ClientInfos/RoyAl-Vitamin______Lab6.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/maeda6uiui/BD1ToOBJ" > /data/ucov/repro/commons-cli/ClientInfos/maeda6uiui______BD1ToOBJ.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/danielgraf/javaemvreader" > /data/ucov/repro/commons-cli/ClientInfos/danielgraf______javaemvreader.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/dreamcloudapp/esa-wiki" > /data/ucov/repro/commons-cli/ClientInfos/dreamcloudapp______esa-wiki.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/xiaonuobase/Snowy-Cloud" > /data/ucov/repro/commons-cli/ClientInfos/xiaonuobase______Snowy-Cloud.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/dantefung/Sauron-Codebase" > /data/ucov/repro/commons-cli/ClientInfos/dantefung______Sauron-Codebase.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/salesforce-misc/perfGenie" > /data/ucov/repro/commons-cli/ClientInfos/salesforce-misc______perfGenie.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/juriel/jdbc-sql-console" > /data/ucov/repro/commons-cli/ClientInfos/juriel______jdbc-sql-console.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/i2shouxihu/webmagic-develop" > /data/ucov/repro/commons-cli/ClientInfos/i2shouxihu______webmagic-develop.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/jfontestad/deid_a" > /data/ucov/repro/commons-cli/ClientInfos/jfontestad______deid_a.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/sincere0104/flink-1.12.0" > /data/ucov/repro/commons-cli/ClientInfos/sincere0104______flink-1.12.0.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/marendtz/Heritrix3_crawler" > /data/ucov/repro/commons-cli/ClientInfos/marendtz______Heritrix3_crawler.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/vithyatith/SonicCellFX" > /data/ucov/repro/commons-cli/ClientInfos/vithyatith______SonicCellFX.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/p506/gapic-generator" > /data/ucov/repro/commons-cli/ClientInfos/p506______gapic-generator.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/acorbin3/P3achB0t" > /data/ucov/repro/commons-cli/ClientInfos/acorbin3______P3achB0t.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/mayinrain/linkis-temp" > /data/ucov/repro/commons-cli/ClientInfos/mayinrain______linkis-temp.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/dragonken/yajhfc-gnu-hylafax" > /data/ucov/repro/commons-cli/ClientInfos/dragonken______yajhfc-gnu-hylafax.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/OpenGovDataMirror/D_cityofnewyork_DSpace" > /data/ucov/repro/commons-cli/ClientInfos/OpenGovDataMirror______D_cityofnewyork_DSpace.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/alinesno-infrastructure/alinesno-infra-base-fileshow" > /data/ucov/repro/commons-cli/ClientInfos/alinesno-infrastructure______alinesno-infra-base-fileshow.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/MrHKing/mmqtt" > /data/ucov/repro/commons-cli/ClientInfos/MrHKing______mmqtt.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/NighterCoder/flink-sql-platform" > /data/ucov/repro/commons-cli/ClientInfos/NighterCoder______flink-sql-platform.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Liyajun595/mini-flink" > /data/ucov/repro/commons-cli/ClientInfos/Liyajun595______mini-flink.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Liujinan001/hive-3.1.1" > /data/ucov/repro/commons-cli/ClientInfos/Liujinan001______hive-3.1.1.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Sheldonsix/spring-geomesa" > /data/ucov/repro/commons-cli/ClientInfos/Sheldonsix______spring-geomesa.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/xwzl/shardingsphere" > /data/ucov/repro/commons-cli/ClientInfos/xwzl______shardingsphere.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/zazuko/spatial-indexer" > /data/ucov/repro/commons-cli/ClientInfos/zazuko______spatial-indexer.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/idrisstouil/TPsudoku" > /data/ucov/repro/commons-cli/ClientInfos/idrisstouil______TPsudoku.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/IamXGW/MyDB" > /data/ucov/repro/commons-cli/ClientInfos/IamXGW______MyDB.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/strategist922/JmxClient" > /data/ucov/repro/commons-cli/ClientInfos/strategist922______JmxClient.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/seanpm2001/SimZonns" > /data/ucov/repro/commons-cli/ClientInfos/seanpm2001______SimZonns.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Hanseltu/blog" > /data/ucov/repro/commons-cli/ClientInfos/Hanseltu______blog.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Nicolas-Francisco/Massive_Data_Processing" > /data/ucov/repro/commons-cli/ClientInfos/Nicolas-Francisco______Massive_Data_Processing.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/project-ncl/sbomer" > /data/ucov/repro/commons-cli/ClientInfos/project-ncl______sbomer.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Force-oneself/force-rocketmq" > /data/ucov/repro/commons-cli/ClientInfos/Force-oneself______force-rocketmq.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Orange-OpenSource/documentare-simdoc" > /data/ucov/repro/commons-cli/ClientInfos/Orange-OpenSource______documentare-simdoc.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/OlgaBou/MyFirstSoapProject" > /data/ucov/repro/commons-cli/ClientInfos/OlgaBou______MyFirstSoapProject.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/mhtocs/search-guard" > /data/ucov/repro/commons-cli/ClientInfos/mhtocs______search-guard.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/OfItinere/ambari-2.7.3.0-139-kylin-v10-Tercel" > /data/ucov/repro/commons-cli/ClientInfos/OfItinere______ambari-2.7.3.0-139-kylin-v10-Tercel.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/solojin/flowable-6.7.2-annotated" > /data/ucov/repro/commons-cli/ClientInfos/solojin______flowable-6.7.2-annotated.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/finbourne/lusid-features-java" > /data/ucov/repro/commons-cli/ClientInfos/finbourne______lusid-features-java.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/karim7262/hadoop3" > /data/ucov/repro/commons-cli/ClientInfos/karim7262______hadoop3.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/pavanipravallika/newps" > /data/ucov/repro/commons-cli/ClientInfos/pavanipravallika______newps.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/fengyue-95/nacos-1.1.3-SourceCode" > /data/ucov/repro/commons-cli/ClientInfos/fengyue-95______nacos-1.1.3-SourceCode.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/yeyhuan/my_datax" > /data/ucov/repro/commons-cli/ClientInfos/yeyhuan______my_datax.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/DarioMolinaValdes/hugoyaitor" > /data/ucov/repro/commons-cli/ClientInfos/DarioMolinaValdes______hugoyaitor.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/tylerwest/bingo-simulator" > /data/ucov/repro/commons-cli/ClientInfos/tylerwest______bingo-simulator.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/colin88/Next_Insurance_Claim_MS" > /data/ucov/repro/commons-cli/ClientInfos/colin88______Next_Insurance_Claim_MS.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/lucystevens/server-lib" > /data/ucov/repro/commons-cli/ClientInfos/lucystevens______server-lib.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/JanssenProject/jans" > /data/ucov/repro/commons-cli/ClientInfos/JanssenProject______jans.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/galuramanboy/cs5260-hw2" > /data/ucov/repro/commons-cli/ClientInfos/galuramanboy______cs5260-hw2.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/xebialabs-community/xlr-db-copy-tool" > /data/ucov/repro/commons-cli/ClientInfos/xebialabs-community______xlr-db-copy-tool.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/davalex2003/kpo" > /data/ucov/repro/commons-cli/ClientInfos/davalex2003______kpo.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/fooblahblah/Hazelblast" > /data/ucov/repro/commons-cli/ClientInfos/fooblahblah______Hazelblast.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ghas-results/htl-tck" > /data/ucov/repro/commons-cli/ClientInfos/ghas-results______htl-tck.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/erngutcon/Acme-Courses-D01" > /data/ucov/repro/commons-cli/ClientInfos/erngutcon______Acme-Courses-D01.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/alebrixel/CLITool" > /data/ucov/repro/commons-cli/ClientInfos/alebrixel______CLITool.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/dgfug/incubator-doris" > /data/ucov/repro/commons-cli/ClientInfos/dgfug______incubator-doris.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/cdk/cdk" > /data/ucov/repro/commons-cli/ClientInfos/cdk______cdk.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Daedalus02/eis_project" > /data/ucov/repro/commons-cli/ClientInfos/Daedalus02______eis_project.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/NoraDing/syringa" > /data/ucov/repro/commons-cli/ClientInfos/NoraDing______syringa.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/xiaoming12306/doris" > /data/ucov/repro/commons-cli/ClientInfos/xiaoming12306______doris.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/wangxiutingdychy/AliwareMQj" > /data/ucov/repro/commons-cli/ClientInfos/wangxiutingdychy______AliwareMQj.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/nigels-com/open-gpstracker.code" > /data/ucov/repro/commons-cli/ClientInfos/nigels-com______open-gpstracker.code.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/dbbyn/arrow" > /data/ucov/repro/commons-cli/ClientInfos/dbbyn______arrow.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/automatioexpert/SeleniumDec0320221" > /data/ucov/repro/commons-cli/ClientInfos/automatioexpert______SeleniumDec0320221.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/xiaoliangliang123/minicloud-tenant" > /data/ucov/repro/commons-cli/ClientInfos/xiaoliangliang123______minicloud-tenant.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/zzzteph/sheye" > /data/ucov/repro/commons-cli/ClientInfos/zzzteph______sheye.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/smart-KG/smartKG" > /data/ucov/repro/commons-cli/ClientInfos/smart-KG______smartKG.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/6si/druid" > /data/ucov/repro/commons-cli/ClientInfos/6si______druid.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/AaronNGray/storm-crawler-new" > /data/ucov/repro/commons-cli/ClientInfos/AaronNGray______storm-crawler-new.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/wuchubuzai2018/nacos-multidatasource" > /data/ucov/repro/commons-cli/ClientInfos/wuchubuzai2018______nacos-multidatasource.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/princeton-nlp/MultilingualAnalysis" > /data/ucov/repro/commons-cli/ClientInfos/princeton-nlp______MultilingualAnalysis.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/IgorDevR/Terminal_For_Position" > /data/ucov/repro/commons-cli/ClientInfos/IgorDevR______Terminal_For_Position.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/isaccanedo/java-kafka-streams" > /data/ucov/repro/commons-cli/ClientInfos/isaccanedo______java-kafka-streams.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/CarrCodes/CPSC531" > /data/ucov/repro/commons-cli/ClientInfos/CarrCodes______CPSC531.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/juanramonuvus/Acme-Work-Plans" > /data/ucov/repro/commons-cli/ClientInfos/juanramonuvus______Acme-Work-Plans.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/rohankumardubey/camus" > /data/ucov/repro/commons-cli/ClientInfos/rohankumardubey______camus.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/mpohler1/amazon-link-checker" > /data/ucov/repro/commons-cli/ClientInfos/mpohler1______amazon-link-checker.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Blaquez-home/nuxeo" > /data/ucov/repro/commons-cli/ClientInfos/Blaquez-home______nuxeo.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ghas-results/flink" > /data/ucov/repro/commons-cli/ClientInfos/ghas-results______flink.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/jm624461806/DistributedSystemSkiResort" > /data/ucov/repro/commons-cli/ClientInfos/jm624461806______DistributedSystemSkiResort.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/subugoe/ocr-tools" > /data/ucov/repro/commons-cli/ClientInfos/subugoe______ocr-tools.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/gfoster1/chess" > /data/ucov/repro/commons-cli/ClientInfos/gfoster1______chess.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ryanardo/gcp-java-docs-samples" > /data/ucov/repro/commons-cli/ClientInfos/ryanardo______gcp-java-docs-samples.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/robjbutler77/Volo_API" > /data/ucov/repro/commons-cli/ClientInfos/robjbutler77______Volo_API.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ep-infosec/33_apache_tuscany-sca-2.x" > /data/ucov/repro/commons-cli/ClientInfos/ep-infosec______33_apache_tuscany-sca-2.x.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Caojunqi/DJL-RL" > /data/ucov/repro/commons-cli/ClientInfos/Caojunqi______DJL-RL.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/pjfanning/incubator-linkis" > /data/ucov/repro/commons-cli/ClientInfos/pjfanning______incubator-linkis.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/cc-archive/search3" > /data/ucov/repro/commons-cli/ClientInfos/cc-archive______search3.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/DBCDK/rawrepo" > /data/ucov/repro/commons-cli/ClientInfos/DBCDK______rawrepo.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/P79N6A/rocketmq-2" > /data/ucov/repro/commons-cli/ClientInfos/P79N6A______rocketmq-2.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/sarvex/checkstyle" > /data/ucov/repro/commons-cli/ClientInfos/sarvex______checkstyle.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/BaseMC/javgent" > /data/ucov/repro/commons-cli/ClientInfos/BaseMC______javgent.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/syhleo/rocketmq-all-5.1.0" > /data/ucov/repro/commons-cli/ClientInfos/syhleo______rocketmq-all-5.1.0.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/mairooni/Flink-TornadoVM-Artifact" > /data/ucov/repro/commons-cli/ClientInfos/mairooni______Flink-TornadoVM-Artifact.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/shengminw/rocketmq-note" > /data/ucov/repro/commons-cli/ClientInfos/shengminw______rocketmq-note.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Super-Special-Pookies/PhraseExtract" > /data/ucov/repro/commons-cli/ClientInfos/Super-Special-Pookies______PhraseExtract.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Arquisoft/participationSystem1a" > /data/ucov/repro/commons-cli/ClientInfos/Arquisoft______participationSystem1a.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/jiao1997/amie" > /data/ucov/repro/commons-cli/ClientInfos/jiao1997______amie.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/zahori-io/zahori-framework" > /data/ucov/repro/commons-cli/ClientInfos/zahori-io______zahori-framework.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/gkthiruvathukal/ChatGPT-Java-CS1-CS2-ACM" > /data/ucov/repro/commons-cli/ClientInfos/gkthiruvathukal______ChatGPT-Java-CS1-CS2-ACM.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/HowardQin/hadoop-2.6.0-cdh5.4.1" > /data/ucov/repro/commons-cli/ClientInfos/HowardQin______hadoop-2.6.0-cdh5.4.1.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/cqdxwjd/apache-hive-2.3.9-src" > /data/ucov/repro/commons-cli/ClientInfos/cqdxwjd______apache-hive-2.3.9-src.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/searchEngineer2022/main" > /data/ucov/repro/commons-cli/ClientInfos/searchEngineer2022______main.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/kevin10030/Reverb" > /data/ucov/repro/commons-cli/ClientInfos/kevin10030______Reverb.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/wwwwwfp/rockmq-master" > /data/ucov/repro/commons-cli/ClientInfos/wwwwwfp______rockmq-master.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/yeewang/lantern" > /data/ucov/repro/commons-cli/ClientInfos/yeewang______lantern.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Noura-alh/DecisionTreeClassifier" > /data/ucov/repro/commons-cli/ClientInfos/Noura-alh______DecisionTreeClassifier.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Jorgehadad/2ndBlockSolvdSergey" > /data/ucov/repro/commons-cli/ClientInfos/Jorgehadad______2ndBlockSolvdSergey.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/devildp243/sonar-report" > /data/ucov/repro/commons-cli/ClientInfos/devildp243______sonar-report.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/koczadly/nano-pow-benchmark" > /data/ucov/repro/commons-cli/ClientInfos/koczadly______nano-pow-benchmark.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/miguelvelezmj25/ConfigCrusher" > /data/ucov/repro/commons-cli/ClientInfos/miguelvelezmj25______ConfigCrusher.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/sudeepika/jAlbum" > /data/ucov/repro/commons-cli/ClientInfos/sudeepika______jAlbum.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/songxiaosheng/dubbo-samples" > /data/ucov/repro/commons-cli/ClientInfos/songxiaosheng______dubbo-samples.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/LeonardoEzio/nacos-2.0.4" > /data/ucov/repro/commons-cli/ClientInfos/LeonardoEzio______nacos-2.0.4.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Mighty0r0n/fastaAnalyzer" > /data/ucov/repro/commons-cli/ClientInfos/Mighty0r0n______fastaAnalyzer.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/String10/HadoopTemplate" > /data/ucov/repro/commons-cli/ClientInfos/String10______HadoopTemplate.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/crukci-bioinformatics/ampliconseq" > /data/ucov/repro/commons-cli/ClientInfos/crukci-bioinformatics______ampliconseq.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/zw201913/echo" > /data/ucov/repro/commons-cli/ClientInfos/zw201913______echo.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/enmabybella/googleads-shopping-samples" > /data/ucov/repro/commons-cli/ClientInfos/enmabybella______googleads-shopping-samples.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/alibaba/SREWorks" > /data/ucov/repro/commons-cli/ClientInfos/alibaba______SREWorks.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/hsu-aut/mtp2skill" > /data/ucov/repro/commons-cli/ClientInfos/hsu-aut______mtp2skill.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/sarvex/SpringIOPlatformFoudation" > /data/ucov/repro/commons-cli/ClientInfos/sarvex______SpringIOPlatformFoudation.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/vdaburon/JUnitReportKpiJMeterReportCsv" > /data/ucov/repro/commons-cli/ClientInfos/vdaburon______JUnitReportKpiJMeterReportCsv.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/narala558/Apache_Flink_Kafka_to_s3" > /data/ucov/repro/commons-cli/ClientInfos/narala558______Apache_Flink_Kafka_to_s3.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/QuiltMC/quilt-loader-sat4j" > /data/ucov/repro/commons-cli/ClientInfos/QuiltMC______quilt-loader-sat4j.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ekmixon/mallet" > /data/ucov/repro/commons-cli/ClientInfos/ekmixon______mallet.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/FranAnillo/Acme-Jobs" > /data/ucov/repro/commons-cli/ClientInfos/FranAnillo______Acme-Jobs.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/dleyanlin/cobra" > /data/ucov/repro/commons-cli/ClientInfos/dleyanlin______cobra.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/intoolswetrust/jsignpdf" > /data/ucov/repro/commons-cli/ClientInfos/intoolswetrust______jsignpdf.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/lluviasnow/lobster" > /data/ucov/repro/commons-cli/ClientInfos/lluviasnow______lobster.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/vishal210893/Java-Reactive" > /data/ucov/repro/commons-cli/ClientInfos/vishal210893______Java-Reactive.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/dancasnar1/Acme-One" > /data/ucov/repro/commons-cli/ClientInfos/dancasnar1______Acme-One.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/DiegoRuizGil/ACME-ONE-Repository" > /data/ucov/repro/commons-cli/ClientInfos/DiegoRuizGil______ACME-ONE-Repository.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/sinri/Silhouette" > /data/ucov/repro/commons-cli/ClientInfos/sinri______Silhouette.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/nicobritos/uni-hazelcast-app" > /data/ucov/repro/commons-cli/ClientInfos/nicobritos______uni-hazelcast-app.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/momo-tong/zookeeper-3.5.4-beta" > /data/ucov/repro/commons-cli/ClientInfos/momo-tong______zookeeper-3.5.4-beta.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/cloudwebsoft/TFlow" > /data/ucov/repro/commons-cli/ClientInfos/cloudwebsoft______TFlow.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/surenganne/metadata" > /data/ucov/repro/commons-cli/ClientInfos/surenganne______metadata.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/CR400AF2001/NJUSE-SEC1-JVVM" > /data/ucov/repro/commons-cli/ClientInfos/CR400AF2001______NJUSE-SEC1-JVVM.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/JanJanda/otava" > /data/ucov/repro/commons-cli/ClientInfos/JanJanda______otava.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/celdorwow/diceware" > /data/ucov/repro/commons-cli/ClientInfos/celdorwow______diceware.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/hoanghun/memory-analyzer" > /data/ucov/repro/commons-cli/ClientInfos/hoanghun______memory-analyzer.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/openaire/broker-cmdline-client" > /data/ucov/repro/commons-cli/ClientInfos/openaire______broker-cmdline-client.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/CyberFlameGO/shiro" > /data/ucov/repro/commons-cli/ClientInfos/CyberFlameGO______shiro.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/h4lo343/P2P-Downloader" > /data/ucov/repro/commons-cli/ClientInfos/h4lo343______P2P-Downloader.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/tedwon/flume-1" > /data/ucov/repro/commons-cli/ClientInfos/tedwon______flume-1.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/jiaxukang/P2PFileTransfer" > /data/ucov/repro/commons-cli/ClientInfos/jiaxukang______P2PFileTransfer.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/git-gloomy/Tankstellenpreise_PoC" > /data/ucov/repro/commons-cli/ClientInfos/git-gloomy______Tankstellenpreise_PoC.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/wix-incubator/JarInjector" > /data/ucov/repro/commons-cli/ClientInfos/wix-incubator______JarInjector.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/rummykhan/jre-knowledge-console" > /data/ucov/repro/commons-cli/ClientInfos/rummykhan______jre-knowledge-console.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/vermutr/to" > /data/ucov/repro/commons-cli/ClientInfos/vermutr______to.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/swap-10/flink-shallow-clone" > /data/ucov/repro/commons-cli/ClientInfos/swap-10______flink-shallow-clone.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/gomcarter/rocketmq-all-t" > /data/ucov/repro/commons-cli/ClientInfos/gomcarter______rocketmq-all-t.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Ovhek/JAXB_XML" > /data/ucov/repro/commons-cli/ClientInfos/Ovhek______JAXB_XML.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/jsteyn/JMC" > /data/ucov/repro/commons-cli/ClientInfos/jsteyn______JMC.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Ste29/manga-scraper" > /data/ucov/repro/commons-cli/ClientInfos/Ste29______manga-scraper.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Joker-5/rocketmq-source-debug" > /data/ucov/repro/commons-cli/ClientInfos/Joker-5______rocketmq-source-debug.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/goluckywizard/CFT-JINT-2023" > /data/ucov/repro/commons-cli/ClientInfos/goluckywizard______CFT-JINT-2023.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/swag-bi/swag" > /data/ucov/repro/commons-cli/ClientInfos/swag-bi______swag.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ghas-results/common-parent-pom" > /data/ucov/repro/commons-cli/ClientInfos/ghas-results______common-parent-pom.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/rainweb521/zookeeper_chinese" > /data/ucov/repro/commons-cli/ClientInfos/rainweb521______zookeeper_chinese.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/srslol/BasicFolderMonitoring" > /data/ucov/repro/commons-cli/ClientInfos/srslol______BasicFolderMonitoring.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/hakmesyo/OJL" > /data/ucov/repro/commons-cli/ClientInfos/hakmesyo______OJL.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/PhuongNguyen2612/Calculator" > /data/ucov/repro/commons-cli/ClientInfos/PhuongNguyen2612______Calculator.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ali-ghanbari/objsim" > /data/ucov/repro/commons-cli/ClientInfos/ali-ghanbari______objsim.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/jtfromus/CompArchProj" > /data/ucov/repro/commons-cli/ClientInfos/jtfromus______CompArchProj.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Feysh-Group/FlowDroid" > /data/ucov/repro/commons-cli/ClientInfos/Feysh-Group______FlowDroid.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Tryweirder/atlas" > /data/ucov/repro/commons-cli/ClientInfos/Tryweirder______atlas.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/kinde-oss/kinde-react-native-generator-0-6x" > /data/ucov/repro/commons-cli/ClientInfos/kinde-oss______kinde-react-native-generator-0-6x.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/ogoerens/master" > /data/ucov/repro/commons-cli/ClientInfos/ogoerens______master.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/huang-feiyu/NanoDB" > /data/ucov/repro/commons-cli/ClientInfos/huang-feiyu______NanoDB.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/Kirill112002/Software" > /data/ucov/repro/commons-cli/ClientInfos/Kirill112002______Software.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/rohankumardubey/datawave" > /data/ucov/repro/commons-cli/ClientInfos/rohankumardubey______datawave.txt
./fetchRepoInfo.sh "/data/ucov/repro/commons-cli/Clients/surya-hebbar/impala" > /data/ucov/repro/commons-cli/ClientInfos/surya-hebbar______impala.txt
