./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/harishm1016/Java-project" > /data/ucov/repro/spark/ClientInfos/harishm1016______Java-project.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/nidianwo/cs" > /data/ucov/repro/spark/ClientInfos/nidianwo______cs.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/pbarot10/Java-Course" > /data/ucov/repro/spark/ClientInfos/pbarot10______Java-Course.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/EdikKing/sprov-ui" > /data/ucov/repro/spark/ClientInfos/EdikKing______sprov-ui.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/marco-spallone/JavaTestKleecks" > /data/ucov/repro/spark/ClientInfos/marco-spallone______JavaTestKleecks.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/rauulriveroo/ScrappingtoApi" > /data/ucov/repro/spark/ClientInfos/rauulriveroo______ScrappingtoApi.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/sushanku/jenkins-mvn-ansible" > /data/ucov/repro/spark/ClientInfos/sushanku______jenkins-mvn-ansible.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-s2022/async-typescript-lab-lmb2lmb" > /data/ucov/repro/spark/ClientInfos/cs0320-s2022______async-typescript-lab-lmb2lmb.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jpacio89/unn-inputter" > /data/ucov/repro/spark/ClientInfos/jpacio89______unn-inputter.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/DGemmell/spark_notes" > /data/ucov/repro/spark/ClientInfos/DGemmell______spark_notes.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-f2021/lab-apis-5EEkQRS3c9h4MzDH" > /data/ucov/repro/spark/ClientInfos/cs0320-f2021______lab-apis-5EEkQRS3c9h4MzDH.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Nikolai9906/AREP-SPARK_WEB_APP" > /data/ucov/repro/spark/ClientInfos/Nikolai9906______AREP-SPARK_WEB_APP.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/vkalev/covcal" > /data/ucov/repro/spark/ClientInfos/vkalev______covcal.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/rezaabedi1365/awsome-compose" > /data/ucov/repro/spark/ClientInfos/rezaabedi1365______awsome-compose.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Augustzzn/java_cs61b" > /data/ucov/repro/spark/ClientInfos/Augustzzn______java_cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/felipecordente/spark-example-felipecordente" > /data/ucov/repro/spark/ClientInfos/felipecordente______spark-example-felipecordente.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Azurexuan/cs61b" > /data/ucov/repro/spark/ClientInfos/Azurexuan______cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/SergioRibera/srserver-java-dip" > /data/ucov/repro/spark/ClientInfos/SergioRibera______srserver-java-dip.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/BuggedPotato/java_serverside" > /data/ucov/repro/spark/ClientInfos/BuggedPotato______java_serverside.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cecibou/TI-2_Diary" > /data/ucov/repro/spark/ClientInfos/cecibou______TI-2_Diary.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/luke7oaks/tamtam-bot-api" > /data/ucov/repro/spark/ClientInfos/luke7oaks______tamtam-bot-api.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/hexagonkt/tfb" > /data/ucov/repro/spark/ClientInfos/hexagonkt______tfb.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/id4ajeet/my_projects" > /data/ucov/repro/spark/ClientInfos/id4ajeet______my_projects.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/MUTHAKABRIAN/The_Classic_Cut" > /data/ucov/repro/spark/ClientInfos/MUTHAKABRIAN______The_Classic_Cut.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/khoa102/khoa-spark-rest-api" > /data/ucov/repro/spark/ClientInfos/khoa102______khoa-spark-rest-api.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-f2021/project-1-2idcvzbrosljikn6-e87piez9jqf3bzksrob3-lznuscrfbj123shine4we5" > /data/ucov/repro/spark/ClientInfos/cs0320-f2021______project-1-2idcvzbrosljikn6-e87piez9jqf3bzksrob3-lznuscrfbj123shine4we5.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-f2021/project-2-afjkagjak24jsgjg-fdakjg2jfdkaj-adjfajdfvdkjkfj2" > /data/ucov/repro/spark/ClientInfos/cs0320-f2021______project-2-afjkagjak24jsgjg-fdakjg2jfdkaj-adjfajdfvdkjkfj2.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/k-appears/java_backend-xing" > /data/ucov/repro/spark/ClientInfos/k-appears______java_backend-xing.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/DiegoGuida/ConsultoreaMe" > /data/ucov/repro/spark/ClientInfos/DiegoGuida______ConsultoreaMe.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/sbesh91/TestKotlinMicroService" > /data/ucov/repro/spark/ClientInfos/sbesh91______TestKotlinMicroService.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Oksird/BlockChainLabs" > /data/ucov/repro/spark/ClientInfos/Oksird______BlockChainLabs.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Kyriezxc/Search_Engine" > /data/ucov/repro/spark/ClientInfos/Kyriezxc______Search_Engine.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/kqi-dev/BattleSnake2021" > /data/ucov/repro/spark/ClientInfos/kqi-dev______BattleSnake2021.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/kierajost4/Tic-Tac-Toe" > /data/ucov/repro/spark/ClientInfos/kierajost4______Tic-Tac-Toe.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/DeveloperOwala/heroSquard" > /data/ucov/repro/spark/ClientInfos/DeveloperOwala______heroSquard.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/thgoexpt/Java-distributed-tracing-implementation" > /data/ucov/repro/spark/ClientInfos/thgoexpt______Java-distributed-tracing-implementation.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/tungphongdo89/tinhocthatladongian" > /data/ucov/repro/spark/ClientInfos/tungphongdo89______tinhocthatladongian.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/YohannaToro/security-ssl" > /data/ucov/repro/spark/ClientInfos/YohannaToro______security-ssl.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/DevOps2021-gb/devops2021" > /data/ucov/repro/spark/ClientInfos/DevOps2021-gb______devops2021.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/SantiagoBayona/AREP-Lab-06-Service" > /data/ucov/repro/spark/ClientInfos/SantiagoBayona______AREP-Lab-06-Service.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/alan-hash/Arquitectura-orientada-a-servicios" > /data/ucov/repro/spark/ClientInfos/alan-hash______Arquitectura-orientada-a-servicios.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/dataspread/Sherlock" > /data/ucov/repro/spark/ClientInfos/dataspread______Sherlock.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/shahebaaz1shaikh/HelloWorld" > /data/ucov/repro/spark/ClientInfos/shahebaaz1shaikh______HelloWorld.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/idk-12/CS61B" > /data/ucov/repro/spark/ClientInfos/idk-12______CS61B.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/NatesHonor/FakenetworkCore" > /data/ucov/repro/spark/ClientInfos/NatesHonor______FakenetworkCore.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Daniel19902/IETI-TALLER-HEROKU" > /data/ucov/repro/spark/ClientInfos/Daniel19902______IETI-TALLER-HEROKU.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/sebasporras14/lab-07AREP" > /data/ucov/repro/spark/ClientInfos/sebasporras14______lab-07AREP.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/ian-mamen/LifeTracker" > /data/ucov/repro/spark/ClientInfos/ian-mamen______LifeTracker.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/FernandoKovaleski/CursoJavaTT" > /data/ucov/repro/spark/ClientInfos/FernandoKovaleski______CursoJavaTT.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/MartinGongora/huella-de-carbono-DDS" > /data/ucov/repro/spark/ClientInfos/MartinGongora______huella-de-carbono-DDS.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/ppablomedina/Developing-a-datalake" > /data/ucov/repro/spark/ClientInfos/ppablomedina______Developing-a-datalake.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/flindback/trumplator" > /data/ucov/repro/spark/ClientInfos/flindback______trumplator.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/dorukerenaktas/cep-intelligent-assistant" > /data/ucov/repro/spark/ClientInfos/dorukerenaktas______cep-intelligent-assistant.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/ayolicias/cartoonNetwork_siyafunda_app" > /data/ucov/repro/spark/ClientInfos/ayolicias______cartoonNetwork_siyafunda_app.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/alexchomiak/FinancialSentimentAnalysis" > /data/ucov/repro/spark/ClientInfos/alexchomiak______FinancialSentimentAnalysis.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/kaijack/reactjsc" > /data/ucov/repro/spark/ClientInfos/kaijack______reactjsc.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/stripe-samples/starter" > /data/ucov/repro/spark/ClientInfos/stripe-samples______starter.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/raul-fernando-mendoza/accept-a-card-payment" > /data/ucov/repro/spark/ClientInfos/raul-fernando-mendoza______accept-a-card-payment.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/juanmora98/AREP-PARCIAL1" > /data/ucov/repro/spark/ClientInfos/juanmora98______AREP-PARCIAL1.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/xuanliu2021/sp18-Alex" > /data/ucov/repro/spark/ClientInfos/xuanliu2021______sp18-Alex.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Daligz/GreenWaste" > /data/ucov/repro/spark/ClientInfos/Daligz______GreenWaste.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/mario86123/cs61b-2018" > /data/ucov/repro/spark/ClientInfos/mario86123______cs61b-2018.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/terragraph/tgnms" > /data/ucov/repro/spark/ClientInfos/terragraph______tgnms.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/dlambrechts/robot-shop" > /data/ucov/repro/spark/ClientInfos/dlambrechts______robot-shop.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/JoePacman/spark-java-poc" > /data/ucov/repro/spark/ClientInfos/JoePacman______spark-java-poc.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/agujuarez97/calculator" > /data/ucov/repro/spark/ClientInfos/agujuarez97______calculator.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/kfinger85/415Clone" > /data/ucov/repro/spark/ClientInfos/kfinger85______415Clone.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-f2021/lab-react-sfeucht" > /data/ucov/repro/spark/ClientInfos/cs0320-f2021______lab-react-sfeucht.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Dayasingh22/BDA-Project-Activity-1" > /data/ucov/repro/spark/ClientInfos/Dayasingh22______BDA-Project-Activity-1.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Jethuestad/DAT250-expass4-code" > /data/ucov/repro/spark/ClientInfos/Jethuestad______DAT250-expass4-code.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/My-TRAC/data-model-Pilot1" > /data/ucov/repro/spark/ClientInfos/My-TRAC______data-model-Pilot1.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/danielrincon-m/AREP_PARCIAL1" > /data/ucov/repro/spark/ClientInfos/danielrincon-m______AREP_PARCIAL1.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/AlduinLeung/cs61b-sp-18" > /data/ucov/repro/spark/ClientInfos/AlduinLeung______cs61b-sp-18.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/dutalmahesh/webtest" > /data/ucov/repro/spark/ClientInfos/dutalmahesh______webtest.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/aj921132/dockercompose" > /data/ucov/repro/spark/ClientInfos/aj921132______dockercompose.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/tjgwebservices/sparkweb" > /data/ucov/repro/spark/ClientInfos/tjgwebservices______sparkweb.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/acxg/cs61b" > /data/ucov/repro/spark/ClientInfos/acxg______cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/leocao91/web-java-demo" > /data/ucov/repro/spark/ClientInfos/leocao91______web-java-demo.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/malyshgit/vk-bot" > /data/ucov/repro/spark/ClientInfos/malyshgit______vk-bot.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/egorkos/minesweeper-restlient-library" > /data/ucov/repro/spark/ClientInfos/egorkos______minesweeper-restlient-library.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/2022-SEMII-DESIV-G2/moreno-alex" > /data/ucov/repro/spark/ClientInfos/2022-SEMII-DESIV-G2______moreno-alex.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cargneluttiLucas/java-clase" > /data/ucov/repro/spark/ClientInfos/cargneluttiLucas______java-clase.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/vkasturia/semantic-layers" > /data/ucov/repro/spark/ClientInfos/vkasturia______semantic-layers.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/sebastianNietoMolina/AREP-lab5" > /data/ucov/repro/spark/ClientInfos/sebastianNietoMolina______AREP-lab5.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cooperece366s21/CoopedIn" > /data/ucov/repro/spark/ClientInfos/cooperece366s21______CoopedIn.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/AP2021Fall/Project-team-09" > /data/ucov/repro/spark/ClientInfos/AP2021Fall______Project-team-09.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/timothybaraka/herosquad" > /data/ucov/repro/spark/ClientInfos/timothybaraka______herosquad.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/JCPosso/AREP-Lab06" > /data/ucov/repro/spark/ClientInfos/JCPosso______AREP-Lab06.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/javanotes/actiongraph" > /data/ucov/repro/spark/ClientInfos/javanotes______actiongraph.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cheatmac/maven" > /data/ucov/repro/spark/ClientInfos/cheatmac______maven.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/67shafar/MedicationOnFHIR" > /data/ucov/repro/spark/ClientInfos/67shafar______MedicationOnFHIR.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/GoupilJeremy/karma-server" > /data/ucov/repro/spark/ClientInfos/GoupilJeremy______karma-server.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/CarlosOrduz777/AREP-SecureApp" > /data/ucov/repro/spark/ClientInfos/CarlosOrduz777______AREP-SecureApp.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/KingWNTK/ChatApp" > /data/ucov/repro/spark/ClientInfos/KingWNTK______ChatApp.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/bigxiongs/my-cs61b" > /data/ucov/repro/spark/ClientInfos/bigxiongs______my-cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/abnerjoy/cs61b" > /data/ucov/repro/spark/ClientInfos/abnerjoy______cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/tevin-otieno/wild-animal-tracker" > /data/ucov/repro/spark/ClientInfos/tevin-otieno______wild-animal-tracker.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Parodix007/spark-java-demo" > /data/ucov/repro/spark/ClientInfos/Parodix007______spark-java-demo.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/LawlessLawless/GLO2004_Devoir1" > /data/ucov/repro/spark/ClientInfos/LawlessLawless______GLO2004_Devoir1.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/kkadouh/stripetest" > /data/ucov/repro/spark/ClientInfos/kkadouh______stripetest.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/nickfun/TwilioDemo" > /data/ucov/repro/spark/ClientInfos/nickfun______TwilioDemo.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Jscorpio1611/web-elements-sepa-debit-payment" > /data/ucov/repro/spark/ClientInfos/Jscorpio1611______web-elements-sepa-debit-payment.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Sergyo97/Lambda_And_Gateway_Services" > /data/ucov/repro/spark/ClientInfos/Sergyo97______Lambda_And_Gateway_Services.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/nr23730/fhirspark" > /data/ucov/repro/spark/ClientInfos/nr23730______fhirspark.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-f2021/lab-canvas-haridandapani" > /data/ucov/repro/spark/ClientInfos/cs0320-f2021______lab-canvas-haridandapani.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Camilomora117/Parcial2Arep" > /data/ucov/repro/spark/ClientInfos/Camilomora117______Parcial2Arep.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Larfg/arep-parcial2" > /data/ucov/repro/spark/ClientInfos/Larfg______arep-parcial2.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/hsintzuli/cs61b" > /data/ucov/repro/spark/ClientInfos/hsintzuli______cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/ipiranhaauxxoj/CcbGuangzhouDevelopera" > /data/ucov/repro/spark/ClientInfos/ipiranhaauxxoj______CcbGuangzhouDevelopera.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Luis7km/Semestral-LuisMilla" > /data/ucov/repro/spark/ClientInfos/Luis7km______Semestral-LuisMilla.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Freda32/cs61b_sy" > /data/ucov/repro/spark/ClientInfos/Freda32______cs61b_sy.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/dd-test5/FrameworkBenchmarks" > /data/ucov/repro/spark/ClientInfos/dd-test5______FrameworkBenchmarks.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/kenjoel/virtualTracker" > /data/ucov/repro/spark/ClientInfos/kenjoel______virtualTracker.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/srigit009/java" > /data/ucov/repro/spark/ClientInfos/srigit009______java.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/hmy824/CS61B" > /data/ucov/repro/spark/ClientInfos/hmy824______CS61B.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/JiajiaLi04/CS61B-Data-Structure" > /data/ucov/repro/spark/ClientInfos/JiajiaLi04______CS61B-Data-Structure.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/adireddy735/maven-war" > /data/ucov/repro/spark/ClientInfos/adireddy735______maven-war.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/gabriela-castro-s/AREP-TALLER-5" > /data/ucov/repro/spark/ClientInfos/gabriela-castro-s______AREP-TALLER-5.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/ehtiramabdullayev/simple-bank-transfer-api" > /data/ucov/repro/spark/ClientInfos/ehtiramabdullayev______simple-bank-transfer-api.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/rwema3/platform-samples" > /data/ucov/repro/spark/ClientInfos/rwema3______platform-samples.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/ElPentagono/BookQueryEngine" > /data/ucov/repro/spark/ClientInfos/ElPentagono______BookQueryEngine.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jmarusak/apisec" > /data/ucov/repro/spark/ClientInfos/jmarusak______apisec.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/ribeir099/PUC-Minas" > /data/ucov/repro/spark/ClientInfos/ribeir099______PUC-Minas.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/weinijuan/cs" > /data/ucov/repro/spark/ClientInfos/weinijuan______cs.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Tammaoui/dat250-expass4-code" > /data/ucov/repro/spark/ClientInfos/Tammaoui______dat250-expass4-code.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/preminstrel/cs61b" > /data/ucov/repro/spark/ClientInfos/preminstrel______cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/naveengithubfiles/hello-world" > /data/ucov/repro/spark/ClientInfos/naveengithubfiles______hello-world.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/shankar0457/sparkjava-test" > /data/ucov/repro/spark/ClientInfos/shankar0457______sparkjava-test.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/elttam/sparkdemo" > /data/ucov/repro/spark/ClientInfos/elttam______sparkdemo.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/brianmuigai96/wildlife-tracker" > /data/ucov/repro/spark/ClientInfos/brianmuigai96______wildlife-tracker.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/afieldi/cloudcompute-1" > /data/ucov/repro/spark/ClientInfos/afieldi______cloudcompute-1.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/ahmetkaygisiz/quotes-rest-app" > /data/ucov/repro/spark/ClientInfos/ahmetkaygisiz______quotes-rest-app.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cristiangiann/mtds-project-rest" > /data/ucov/repro/spark/ClientInfos/cristiangiann______mtds-project-rest.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/TI02-Simplinsino/simplinsino" > /data/ucov/repro/spark/ClientInfos/TI02-Simplinsino______simplinsino.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/wolfcito/neoflix-app" > /data/ucov/repro/spark/ClientInfos/wolfcito______neoflix-app.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Xiaohongdian119/CS61B" > /data/ucov/repro/spark/ClientInfos/Xiaohongdian119______CS61B.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/rhuang1564/CampusMaps" > /data/ucov/repro/spark/ClientInfos/rhuang1564______CampusMaps.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/k8s-docs/knative-docs" > /data/ucov/repro/spark/ClientInfos/k8s-docs______knative-docs.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/oyjoh/DAT250-expass4" > /data/ucov/repro/spark/ClientInfos/oyjoh______DAT250-expass4.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/oliveiramarcio/githubparser" > /data/ucov/repro/spark/ClientInfos/oliveiramarcio______githubparser.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/being12345/cs61b18" > /data/ucov/repro/spark/ClientInfos/being12345______cs61b18.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jkL970910/CS61b" > /data/ucov/repro/spark/ClientInfos/jkL970910______CS61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jmi-axelor/todo-app" > /data/ucov/repro/spark/ClientInfos/jmi-axelor______todo-app.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/imyzt/learning-technology-code" > /data/ucov/repro/spark/ClientInfos/imyzt______learning-technology-code.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/hanxu12/cs61b" > /data/ucov/repro/spark/ClientInfos/hanxu12______cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/thabok/mycartime" > /data/ucov/repro/spark/ClientInfos/thabok______mycartime.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Jcro15/Arep-Parcial1" > /data/ucov/repro/spark/ClientInfos/Jcro15______Arep-Parcial1.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/weijchen/berkeley-cs61b" > /data/ucov/repro/spark/ClientInfos/weijchen______berkeley-cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/RAVI-2016HW86314/sparkjava-war-example" > /data/ucov/repro/spark/ClientInfos/RAVI-2016HW86314______sparkjava-war-example.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Victoooooor/ECE-465-Cloud-Computing" > /data/ucov/repro/spark/ClientInfos/Victoooooor______ECE-465-Cloud-Computing.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/phamduybk/lockex1987.github.io" > /data/ucov/repro/spark/ClientInfos/phamduybk______lockex1987.github.io.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-f2021/project-2-5eekqrs3c9h4mzdh-cs32-student-xkj5cb3ynj9hmfl" > /data/ucov/repro/spark/ClientInfos/cs0320-f2021______project-2-5eekqrs3c9h4mzdh-cs32-student-xkj5cb3ynj9hmfl.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/OsuTourneyBot/Bancho-Bot" > /data/ucov/repro/spark/ClientInfos/OsuTourneyBot______Bancho-Bot.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cravenbrave/DataStructure_couse_2021" > /data/ucov/repro/spark/ClientInfos/cravenbrave______DataStructure_couse_2021.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/harol-lml/Proyecto21Blackjack" > /data/ucov/repro/spark/ClientInfos/harol-lml______Proyecto21Blackjack.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/JohannCepeda16/AREP-Lab5" > /data/ucov/repro/spark/ClientInfos/JohannCepeda16______AREP-Lab5.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/bryanbill/tracker" > /data/ucov/repro/spark/ClientInfos/bryanbill______tracker.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/maxduu/Web-Search-Engine" > /data/ucov/repro/spark/ClientInfos/maxduu______Web-Search-Engine.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Erika2006y/Yoatzi" > /data/ucov/repro/spark/ClientInfos/Erika2006y______Yoatzi.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/lennartlott/recurly-integration-examples" > /data/ucov/repro/spark/ClientInfos/lennartlott______recurly-integration-examples.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/scalikejdbc/scalikejdbc4j" > /data/ucov/repro/spark/ClientInfos/scalikejdbc______scalikejdbc4j.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/VinnieIT/hero-app" > /data/ucov/repro/spark/ClientInfos/VinnieIT______hero-app.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/y505340035/cs61b-18sp" > /data/ucov/repro/spark/ClientInfos/y505340035______cs61b-18sp.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/JohannPaez/AREP-SecureSparkWebApp" > /data/ucov/repro/spark/ClientInfos/JohannPaez______AREP-SecureSparkWebApp.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/pradeep9030/sparkjava" > /data/ucov/repro/spark/ClientInfos/pradeep9030______sparkjava.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/juankohler/meli-ite-java-api-users" > /data/ucov/repro/spark/ClientInfos/juankohler______meli-ite-java-api-users.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jackgrant31/LEDHub" > /data/ucov/repro/spark/ClientInfos/jackgrant31______LEDHub.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Adri4nG/MovieRental_Group7" > /data/ucov/repro/spark/ClientInfos/Adri4nG______MovieRental_Group7.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/eshalakhotia/Shreddify" > /data/ucov/repro/spark/ClientInfos/eshalakhotia______Shreddify.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/itisrost/RvHome" > /data/ucov/repro/spark/ClientInfos/itisrost______RvHome.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/George-Okumu/Wildlife-Tracker" > /data/ucov/repro/spark/ClientInfos/George-Okumu______Wildlife-Tracker.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Davidgrcdz/Scraper-Project" > /data/ucov/repro/spark/ClientInfos/Davidgrcdz______Scraper-Project.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/zehaowang/cs61b-sp18" > /data/ucov/repro/spark/ClientInfos/zehaowang______cs61b-sp18.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/martinnyakimov/MyHomeAssistant" > /data/ucov/repro/spark/ClientInfos/martinnyakimov______MyHomeAssistant.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jonathanjma/Megamaze" > /data/ucov/repro/spark/ClientInfos/jonathanjma______Megamaze.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/winterhy/stars-project" > /data/ucov/repro/spark/ClientInfos/winterhy______stars-project.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/towc/wordsnake-vue-java" > /data/ucov/repro/spark/ClientInfos/towc______wordsnake-vue-java.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jayanthiutharadu/docker" > /data/ucov/repro/spark/ClientInfos/jayanthiutharadu______docker.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/nguyenvivian/OhWhale" > /data/ucov/repro/spark/ClientInfos/nguyenvivian______OhWhale.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/juanbaezl/tareaDockerAWS" > /data/ucov/repro/spark/ClientInfos/juanbaezl______tareaDockerAWS.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/stg1205/CS61B" > /data/ucov/repro/spark/ClientInfos/stg1205______CS61B.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/aasheesh03/book-my-ticket" > /data/ucov/repro/spark/ClientInfos/aasheesh03______book-my-ticket.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-f2021/lab-front-end-ofrmnwcsi5m5yxbo" > /data/ucov/repro/spark/ClientInfos/cs0320-f2021______lab-front-end-ofrmnwcsi5m5yxbo.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/angiedanielar/LAB5_AREP" > /data/ucov/repro/spark/ClientInfos/angiedanielar______LAB5_AREP.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/eric900115/CS61b" > /data/ucov/repro/spark/ClientInfos/eric900115______CS61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/TorjusFS/dat250" > /data/ucov/repro/spark/ClientInfos/TorjusFS______dat250.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Rincon10/AREP-LAB02" > /data/ucov/repro/spark/ClientInfos/Rincon10______AREP-LAB02.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/shoyui/cs61b-sp18" > /data/ucov/repro/spark/ClientInfos/shoyui______cs61b-sp18.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/yiming421/mine_cs61b" > /data/ucov/repro/spark/ClientInfos/yiming421______mine_cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-f2021/lab-front-end-8mzln8" > /data/ucov/repro/spark/ClientInfos/cs0320-f2021______lab-front-end-8mzln8.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/nla/jwebrenderer" > /data/ucov/repro/spark/ClientInfos/nla______jwebrenderer.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/l0stmyself/da650samplecode" > /data/ucov/repro/spark/ClientInfos/l0stmyself______da650samplecode.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-f2021/project-1-dy7cypw9wkaddvsp-fouw4ytpien6np1-rh7cycrnldgcxees" > /data/ucov/repro/spark/ClientInfos/cs0320-f2021______project-1-dy7cypw9wkaddvsp-fouw4ytpien6np1-rh7cycrnldgcxees.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/zhoupan/jooq-android" > /data/ucov/repro/spark/ClientInfos/zhoupan______jooq-android.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/BJM19/AREP-LAB01-NTRODUCCION-MVN-GIT-Y-HEROKU" > /data/ucov/repro/spark/ClientInfos/BJM19______AREP-LAB01-NTRODUCCION-MVN-GIT-Y-HEROKU.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/SumaVarshitha/assessmentdocker" > /data/ucov/repro/spark/ClientInfos/SumaVarshitha______assessmentdocker.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/floptadeu/Integracao-Spark" > /data/ucov/repro/spark/ClientInfos/floptadeu______Integracao-Spark.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/JMDev2/WildLife-Tracker" > /data/ucov/repro/spark/ClientInfos/JMDev2______WildLife-Tracker.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/waqarhmad242/checkout" > /data/ucov/repro/spark/ClientInfos/waqarhmad242______checkout.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/rajat965ng/ApiSecurity" > /data/ucov/repro/spark/ClientInfos/rajat965ng______ApiSecurity.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jjk1492/WebCheckers" > /data/ucov/repro/spark/ClientInfos/jjk1492______WebCheckers.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/BulgakViktoriya14/webServices" > /data/ucov/repro/spark/ClientInfos/BulgakViktoriya14______webServices.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Angelica-Alfaro/AREP_TALLER4" > /data/ucov/repro/spark/ClientInfos/Angelica-Alfaro______AREP_TALLER4.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/sharonoloo/hero-squad" > /data/ucov/repro/spark/ClientInfos/sharonoloo______hero-squad.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/blakestickland/spark-java-api-demo-baeldung" > /data/ucov/repro/spark/ClientInfos/blakestickland______spark-java-api-demo-baeldung.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/SJ47/fooDee_ialc_version" > /data/ucov/repro/spark/ClientInfos/SJ47______fooDee_ialc_version.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/kevinbas12/test" > /data/ucov/repro/spark/ClientInfos/kevinbas12______test.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/AlenaLosk/Homework6" > /data/ucov/repro/spark/ClientInfos/AlenaLosk______Homework6.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/caterpillar1219/spring18-cp" > /data/ucov/repro/spark/ClientInfos/caterpillar1219______spring18-cp.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/ethanwong987/BearMaps" > /data/ucov/repro/spark/ClientInfos/ethanwong987______BearMaps.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/press0/jib" > /data/ucov/repro/spark/ClientInfos/press0______jib.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/nrakshaynr/jjjava" > /data/ucov/repro/spark/ClientInfos/nrakshaynr______jjjava.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jojoavila/stedi-private-main" > /data/ucov/repro/spark/ClientInfos/jojoavila______stedi-private-main.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/QianTan214/CS61B" > /data/ucov/repro/spark/ClientInfos/QianTan214______CS61B.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/DamGaFlo/RoundRobin" > /data/ucov/repro/spark/ClientInfos/DamGaFlo______RoundRobin.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/kirbyydoge/Maven-Demo-App" > /data/ucov/repro/spark/ClientInfos/kirbyydoge______Maven-Demo-App.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/dhanu123456/silent" > /data/ucov/repro/spark/ClientInfos/dhanu123456______silent.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/integration-app/react-java-integration-examples" > /data/ucov/repro/spark/ClientInfos/integration-app______react-java-integration-examples.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Arabprogrammer/Graphql" > /data/ucov/repro/spark/ClientInfos/Arabprogrammer______Graphql.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/mombe090/devscom-conf.universal-money" > /data/ucov/repro/spark/ClientInfos/mombe090______devscom-conf.universal-money.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/senpay/login-form" > /data/ucov/repro/spark/ClientInfos/senpay______login-form.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-s2022/react-lab-dylanilewis" > /data/ucov/repro/spark/ClientInfos/cs0320-s2022______react-lab-dylanilewis.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/kuldeepsinghsekhon/laravel-custom-member-plans-permission" > /data/ucov/repro/spark/ClientInfos/kuldeepsinghsekhon______laravel-custom-member-plans-permission.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-s2022/async-typescript-lab-ashley-cai" > /data/ucov/repro/spark/ClientInfos/cs0320-s2022______async-typescript-lab-ashley-cai.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Nicholas-Kimutai/Wildlife-Tracking" > /data/ucov/repro/spark/ClientInfos/Nicholas-Kimutai______Wildlife-Tracking.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/AndyZhang1999/java-self-learning" > /data/ucov/repro/spark/ClientInfos/AndyZhang1999______java-self-learning.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/lucaazalim/java-wordle-game" > /data/ucov/repro/spark/ClientInfos/lucaazalim______java-wordle-game.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/pedroarlves/ti2" > /data/ucov/repro/spark/ClientInfos/pedroarlves______ti2.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Solabaev-developer/serialRestService" > /data/ucov/repro/spark/ClientInfos/Solabaev-developer______serialRestService.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/JulianP-24/AREP" > /data/ucov/repro/spark/ClientInfos/JulianP-24______AREP.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-s2022/react-lab-eatthepear" > /data/ucov/repro/spark/ClientInfos/cs0320-s2022______react-lab-eatthepear.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/PrimePlugin/PrimePlugins-BungeeAPI" > /data/ucov/repro/spark/ClientInfos/PrimePlugin______PrimePlugins-BungeeAPI.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/pointerless/vdmj-remote" > /data/ucov/repro/spark/ClientInfos/pointerless______vdmj-remote.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/knative/docs" > /data/ucov/repro/spark/ClientInfos/knative______docs.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/MichalSzewczyk/cse-commands-processor" > /data/ucov/repro/spark/ClientInfos/MichalSzewczyk______cse-commands-processor.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/comejia/utn-dds-mi-impacto-ambiental" > /data/ucov/repro/spark/ClientInfos/comejia______utn-dds-mi-impacto-ambiental.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jsoref/languagetool" > /data/ucov/repro/spark/ClientInfos/jsoref______languagetool.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-s2022/async-typescript-lab-sroberts0403" > /data/ucov/repro/spark/ClientInfos/cs0320-s2022______async-typescript-lab-sroberts0403.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/WinkyHu/BearMaps" > /data/ucov/repro/spark/ClientInfos/WinkyHu______BearMaps.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/castroneves/metro-bank-export-freeagent" > /data/ucov/repro/spark/ClientInfos/castroneves______metro-bank-export-freeagent.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Everneth/EverMap" > /data/ucov/repro/spark/ClientInfos/Everneth______EverMap.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/GuadalupeJimenezCab/Sistemas-web" > /data/ucov/repro/spark/ClientInfos/GuadalupeJimenezCab______Sistemas-web.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-s2022/react-lab-BrianEdmund" > /data/ucov/repro/spark/ClientInfos/cs0320-s2022______react-lab-BrianEdmund.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/malinkaphann/multi-module-maven-app" > /data/ucov/repro/spark/ClientInfos/malinkaphann______multi-module-maven-app.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/rohankumardubey/reair" > /data/ucov/repro/spark/ClientInfos/rohankumardubey______reair.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jiangjiangtian/cs61b1" > /data/ucov/repro/spark/ClientInfos/jiangjiangtian______cs61b1.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/DeliciousDark/cs61b" > /data/ucov/repro/spark/ClientInfos/DeliciousDark______cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Okellothomas/NewsPortal" > /data/ucov/repro/spark/ClientInfos/Okellothomas______NewsPortal.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/picknchew/coinbase-commerce-java" > /data/ucov/repro/spark/ClientInfos/picknchew______coinbase-commerce-java.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/acimack/schedlr" > /data/ucov/repro/spark/ClientInfos/acimack______schedlr.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/AtomCats/gamexapplication" > /data/ucov/repro/spark/ClientInfos/AtomCats______gamexapplication.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-f2021/lab-async-js-ba5py46xjvsdxbuh" > /data/ucov/repro/spark/ClientInfos/cs0320-f2021______lab-async-js-ba5py46xjvsdxbuh.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/kovacshuni/koauth-samples" > /data/ucov/repro/spark/ClientInfos/kovacshuni______koauth-samples.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/mrroin/Mrroin_Base_Backend_Java" > /data/ucov/repro/spark/ClientInfos/mrroin______Mrroin_Base_Backend_Java.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/JamesSanderslawnmasters/placing-a-hold" > /data/ucov/repro/spark/ClientInfos/JamesSanderslawnmasters______placing-a-hold.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Phandung1312/PBL4" > /data/ucov/repro/spark/ClientInfos/Phandung1312______PBL4.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/newrol/hopper" > /data/ucov/repro/spark/ClientInfos/newrol______hopper.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cynthiaqntna/aemet" > /data/ucov/repro/spark/ClientInfos/cynthiaqntna______aemet.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/ShupeiLi/CS61B" > /data/ucov/repro/spark/ClientInfos/ShupeiLi______CS61B.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/antonismaitis/java-spark" > /data/ucov/repro/spark/ClientInfos/antonismaitis______java-spark.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/spiderChow/Pacman" > /data/ucov/repro/spark/ClientInfos/spiderChow______Pacman.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/gustavo-silvestr/tibd2" > /data/ucov/repro/spark/ClientInfos/gustavo-silvestr______tibd2.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/emaphis/JavaModules" > /data/ucov/repro/spark/ClientInfos/emaphis______JavaModules.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/VladuTzZ-sudo/DB_homework" > /data/ucov/repro/spark/ClientInfos/VladuTzZ-sudo______DB_homework.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/mlee212/rabbit" > /data/ucov/repro/spark/ClientInfos/mlee212______rabbit.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/SValentyn/Payment-Management-System" > /data/ucov/repro/spark/ClientInfos/SValentyn______Payment-Management-System.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/tomasanchez/paw-rescue" > /data/ucov/repro/spark/ClientInfos/tomasanchez______paw-rescue.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/manh26x/spark-kotlin" > /data/ucov/repro/spark/ClientInfos/manh26x______spark-kotlin.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Juanda171217/docker" > /data/ucov/repro/spark/ClientInfos/Juanda171217______docker.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cihar29/insight" > /data/ucov/repro/spark/ClientInfos/cihar29______insight.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Burak-37/abgabe12" > /data/ucov/repro/spark/ClientInfos/Burak-37______abgabe12.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/singhbipinb/Movie-Recommendation" > /data/ucov/repro/spark/ClientInfos/singhbipinb______Movie-Recommendation.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/anika-ahluwalia/mapdash" > /data/ucov/repro/spark/ClientInfos/anika-ahluwalia______mapdash.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/coke2021/cs61b" > /data/ucov/repro/spark/ClientInfos/coke2021______cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/AbdulRahman7862/Java-Email-SMS-Sender" > /data/ucov/repro/spark/ClientInfos/AbdulRahman7862______Java-Email-SMS-Sender.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/csh2830/guessing-game" > /data/ucov/repro/spark/ClientInfos/csh2830______guessing-game.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jiejie08/Java" > /data/ucov/repro/spark/ClientInfos/jiejie08______Java.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/rkcho317/proj531" > /data/ucov/repro/spark/ClientInfos/rkcho317______proj531.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Demongo2009/PROZ_Communicator" > /data/ucov/repro/spark/ClientInfos/Demongo2009______PROZ_Communicator.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/samuelkhong/OpenStreetMaps" > /data/ucov/repro/spark/ClientInfos/samuelkhong______OpenStreetMaps.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/fernando-b15/SparkWebApp" > /data/ucov/repro/spark/ClientInfos/fernando-b15______SparkWebApp.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Itera/avdelingstur_okt2019" > /data/ucov/repro/spark/ClientInfos/Itera______avdelingstur_okt2019.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-f2021/project-1-5pzjmlr1eimp0jjw-arsatpwutcfuasdw-qmccfdvbvse5abfe" > /data/ucov/repro/spark/ClientInfos/cs0320-f2021______project-1-5pzjmlr1eimp0jjw-arsatpwutcfuasdw-qmccfdvbvse5abfe.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/githiomi/Hero_Squad" > /data/ucov/repro/spark/ClientInfos/githiomi______Hero_Squad.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/pdlai/duck" > /data/ucov/repro/spark/ClientInfos/pdlai______duck.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/BennettMoore/Webcheckers-School-Project" > /data/ucov/repro/spark/ClientInfos/BennettMoore______Webcheckers-School-Project.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/siqiye/cs61b" > /data/ucov/repro/spark/ClientInfos/siqiye______cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/germanAOQ/AREP-Parcial2-EC2" > /data/ucov/repro/spark/ClientInfos/germanAOQ______AREP-Parcial2-EC2.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/CharafeddineMechalikh/recap" > /data/ucov/repro/spark/ClientInfos/CharafeddineMechalikh______recap.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/bobbinnej/Rangers-Tracker-for-Wildlife" > /data/ucov/repro/spark/ClientInfos/bobbinnej______Rangers-Tracker-for-Wildlife.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/CeliaJSLau/elasticsearch-demo" > /data/ucov/repro/spark/ClientInfos/CeliaJSLau______elasticsearch-demo.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Ezdies/Quote_Generator" > /data/ucov/repro/spark/ClientInfos/Ezdies______Quote_Generator.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/yongqiangG/CS61B-Datastructur" > /data/ucov/repro/spark/ClientInfos/yongqiangG______CS61B-Datastructur.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/madinahmadzai2016/PaymentWeb" > /data/ucov/repro/spark/ClientInfos/madinahmadzai2016______PaymentWeb.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/prakashin/sparkjava-war-example" > /data/ucov/repro/spark/ClientInfos/prakashin______sparkjava-war-example.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/yaminijarabana/GitMavenTest" > /data/ucov/repro/spark/ClientInfos/yaminijarabana______GitMavenTest.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/GinAren92/ServletBlog" > /data/ucov/repro/spark/ClientInfos/GinAren92______ServletBlog.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Givo-Givo/API-Rest" > /data/ucov/repro/spark/ClientInfos/Givo-Givo______API-Rest.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/bcs4313/WebCheckers-Project-Archived" > /data/ucov/repro/spark/ClientInfos/bcs4313______WebCheckers-Project-Archived.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Gufdoor/get2play" > /data/ucov/repro/spark/ClientInfos/Gufdoor______get2play.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/maxrun11/CS61B-Tutorial" > /data/ucov/repro/spark/ClientInfos/maxrun11______CS61B-Tutorial.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/BielosX/AWS-architect" > /data/ucov/repro/spark/ClientInfos/BielosX______AWS-architect.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/lauraval19/AREP-AWSDOCKERintro" > /data/ucov/repro/spark/ClientInfos/lauraval19______AREP-AWSDOCKERintro.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/masterford/XPathCrawler" > /data/ucov/repro/spark/ClientInfos/masterford______XPathCrawler.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/gtm7712/team-project-d-2191-swen-261-11-d" > /data/ucov/repro/spark/ClientInfos/gtm7712______team-project-d-2191-swen-261-11-d.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/benjagm/simple-spark-api-playground" > /data/ucov/repro/spark/ClientInfos/benjagm______simple-spark-api-playground.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/emrah44/searchcode-server" > /data/ucov/repro/spark/ClientInfos/emrah44______searchcode-server.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jrangu/twitter" > /data/ucov/repro/spark/ClientInfos/jrangu______twitter.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/stefania5964/taller5" > /data/ucov/repro/spark/ClientInfos/stefania5964______taller5.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/vmalik800/https-github.com-vmalik800-sparkjava-war-example" > /data/ucov/repro/spark/ClientInfos/vmalik800______https-github.com-vmalik800-sparkjava-war-example.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jbromero/PruebaRestfulJavaScript" > /data/ucov/repro/spark/ClientInfos/jbromero______PruebaRestfulJavaScript.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/liangli16/CS61B" > /data/ucov/repro/spark/ClientInfos/liangli16______CS61B.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/yimumengke/CS61B-Tutorial" > /data/ucov/repro/spark/ClientInfos/yimumengke______CS61B-Tutorial.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/tiagohpf/thesis-2018-2019" > /data/ucov/repro/spark/ClientInfos/tiagohpf______thesis-2018-2019.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-s2022/async-typescript-lab-willguo0" > /data/ucov/repro/spark/ClientInfos/cs0320-s2022______async-typescript-lab-willguo0.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/onlythenaive/javaschool-ittunes" > /data/ucov/repro/spark/ClientInfos/onlythenaive______javaschool-ittunes.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/sebChevre/ADSB-Project" > /data/ucov/repro/spark/ClientInfos/sebChevre______ADSB-Project.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jpmeireles08/TI2" > /data/ucov/repro/spark/ClientInfos/jpmeireles08______TI2.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Carol110905/SistemasWeb" > /data/ucov/repro/spark/ClientInfos/Carol110905______SistemasWeb.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/ceshiren/HogwartsJava4" > /data/ucov/repro/spark/ClientInfos/ceshiren______HogwartsJava4.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/CesarRawr/Todos" > /data/ucov/repro/spark/ClientInfos/CesarRawr______Todos.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/MatosJM/Calculadora-web-socket" > /data/ucov/repro/spark/ClientInfos/MatosJM______Calculadora-web-socket.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/newrelic-experimental/newrelic-webhook-to-snmp-trap-java" > /data/ucov/repro/spark/ClientInfos/newrelic-experimental______newrelic-webhook-to-snmp-trap-java.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-s2022/async-typescript-lab-yuqinan" > /data/ucov/repro/spark/ClientInfos/cs0320-s2022______async-typescript-lab-yuqinan.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/dsKarthick/spark-java-hello-world" > /data/ucov/repro/spark/ClientInfos/dsKarthick______spark-java-hello-world.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/mlalma/CFTA" > /data/ucov/repro/spark/ClientInfos/mlalma______CFTA.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/2022-SEMII-DESIV-G1/espino-isaias" > /data/ucov/repro/spark/ClientInfos/2022-SEMII-DESIV-G1______espino-isaias.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Maada/projet_java" > /data/ucov/repro/spark/ClientInfos/Maada______projet_java.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/nietus/spark_crud" > /data/ucov/repro/spark/ClientInfos/nietus______spark_crud.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/y3h7rv/cs61b" > /data/ucov/repro/spark/ClientInfos/y3h7rv______cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Killersys/AREP-Parcial1T" > /data/ucov/repro/spark/ClientInfos/Killersys______AREP-Parcial1T.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/SantiagoECHM/80640" > /data/ucov/repro/spark/ClientInfos/SantiagoECHM______80640.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/FarhanAxiq/Tour-Website-App" > /data/ucov/repro/spark/ClientInfos/FarhanAxiq______Tour-Website-App.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/ampyjoe/TuneTypes" > /data/ucov/repro/spark/ClientInfos/ampyjoe______TuneTypes.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/BMaxi6/gesoc" > /data/ucov/repro/spark/ClientInfos/BMaxi6______gesoc.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/SergioRt1/INTRODUCTION-TO-COMPLEX-SYSTEMS" > /data/ucov/repro/spark/ClientInfos/SergioRt1______INTRODUCTION-TO-COMPLEX-SYSTEMS.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/blur-blue/SparkMavenProject-1-Error-Include" > /data/ucov/repro/spark/ClientInfos/blur-blue______SparkMavenProject-1-Error-Include.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/DevOpsSpti/AssetManagement" > /data/ucov/repro/spark/ClientInfos/DevOpsSpti______AssetManagement.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-f2021/lab-front-end-9VsCfZ5sPjUMRp" > /data/ucov/repro/spark/ClientInfos/cs0320-f2021______lab-front-end-9VsCfZ5sPjUMRp.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/normalek/money-transfers" > /data/ucov/repro/spark/ClientInfos/normalek______money-transfers.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jie567/cs61b" > /data/ucov/repro/spark/ClientInfos/jie567______cs61b.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/hermanpt/QA_Programming" > /data/ucov/repro/spark/ClientInfos/hermanpt______QA_Programming.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Justin-Ng-SF/tic-tac-toe" > /data/ucov/repro/spark/ClientInfos/Justin-Ng-SF______tic-tac-toe.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/doublEeVil/SimpleDev" > /data/ucov/repro/spark/ClientInfos/doublEeVil______SimpleDev.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/ChuleHou/PacMan" > /data/ucov/repro/spark/ClientInfos/ChuleHou______PacMan.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/saschpe/jib" > /data/ucov/repro/spark/ClientInfos/saschpe______jib.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/vichhaiyserey/docker-compose-nginx-jfrog" > /data/ucov/repro/spark/ClientInfos/vichhaiyserey______docker-compose-nginx-jfrog.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/TimSquire/TechConference" > /data/ucov/repro/spark/ClientInfos/TimSquire______TechConference.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Daniel9842/ParcialArep2Corte" > /data/ucov/repro/spark/ClientInfos/Daniel9842______ParcialArep2Corte.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/rahulkanuparthi/rahul-testing" > /data/ucov/repro/spark/ClientInfos/rahulkanuparthi______rahul-testing.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-s2022/async-typescript-lab-ann2002g" > /data/ucov/repro/spark/ClientInfos/cs0320-s2022______async-typescript-lab-ann2002g.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/latte-french/transactionservice" > /data/ucov/repro/spark/ClientInfos/latte-french______transactionservice.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/OnHenriGolera/Astro" > /data/ucov/repro/spark/ClientInfos/OnHenriGolera______Astro.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/kurokawa5/subscription-use-cases" > /data/ucov/repro/spark/ClientInfos/kurokawa5______subscription-use-cases.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/11manu96/comp504-H7" > /data/ucov/repro/spark/ClientInfos/11manu96______comp504-H7.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/mariahv9/SecureAppAREP" > /data/ucov/repro/spark/ClientInfos/mariahv9______SecureAppAREP.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Kishore-08/ase1" > /data/ucov/repro/spark/ClientInfos/Kishore-08______ase1.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/italia/daf-cacher" > /data/ucov/repro/spark/ClientInfos/italia______daf-cacher.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/jorecat/csci-366-fall2021-private" > /data/ucov/repro/spark/ClientInfos/jorecat______csci-366-fall2021-private.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/cs0320-f2021/lab-apis-h2323547425" > /data/ucov/repro/spark/ClientInfos/cs0320-f2021______lab-apis-h2323547425.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/PedroMathieu/ES-LETI-1Sem-2022-Grupo-11" > /data/ucov/repro/spark/ClientInfos/PedroMathieu______ES-LETI-1Sem-2022-Grupo-11.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/alpescraft/functional-core-session" > /data/ucov/repro/spark/ClientInfos/alpescraft______functional-core-session.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/YashasRajuN/BYZCUIT_FORK" > /data/ucov/repro/spark/ClientInfos/YashasRajuN______BYZCUIT_FORK.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/yuanl22/CS61B" > /data/ucov/repro/spark/ClientInfos/yuanl22______CS61B.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/marceloivob/VRPL" > /data/ucov/repro/spark/ClientInfos/marceloivob______VRPL.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/anushakvinay/testing" > /data/ucov/repro/spark/ClientInfos/anushakvinay______testing.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/violethaze74/awesome-compose" > /data/ucov/repro/spark/ClientInfos/violethaze74______awesome-compose.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/paolosecci/springBootMVC" > /data/ucov/repro/spark/ClientInfos/paolosecci______springBootMVC.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/Okellothomas/hero-squad" > /data/ucov/repro/spark/ClientInfos/Okellothomas______hero-squad.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/dds-utn/unisocial-spark" > /data/ucov/repro/spark/ClientInfos/dds-utn______unisocial-spark.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/roquebajosexto/DOTT" > /data/ucov/repro/spark/ClientInfos/roquebajosexto______DOTT.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/yyudji/ex-spark-crud" > /data/ucov/repro/spark/ClientInfos/yyudji______ex-spark-crud.txt
./fetchRepoInfo.sh "/data/ucov/repro/spark/Clients/emarcosgv/Tp-Disenio-2020-Gesoc" > /data/ucov/repro/spark/ClientInfos/emarcosgv______Tp-Disenio-2020-Gesoc.txt
