./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Boti2-0/product-identifier-products" > /data/ucov/repro/jsoup/ClientInfos/Boti2-0______product-identifier-products.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Alex-HCF/drg" > /data/ucov/repro/jsoup/ClientInfos/Alex-HCF______drg.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/hoangon1z/sanbo1" > /data/ucov/repro/jsoup/ClientInfos/hoangon1z______sanbo1.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/shuanglangdeliubei/Timo" > /data/ucov/repro/jsoup/ClientInfos/shuanglangdeliubei______Timo.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/CrackerCat/YongyouNC-Unserialize-Tools" > /data/ucov/repro/jsoup/ClientInfos/CrackerCat______YongyouNC-Unserialize-Tools.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/DenisGIT1/Unic" > /data/ucov/repro/jsoup/ClientInfos/DenisGIT1______Unic.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Kirill112002/Software" > /data/ucov/repro/jsoup/ClientInfos/Kirill112002______Software.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/syllogism1123/webcrawler_XinDu" > /data/ucov/repro/jsoup/ClientInfos/syllogism1123______webcrawler_XinDu.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/yida-lxw/spider4j" > /data/ucov/repro/jsoup/ClientInfos/yida-lxw______spider4j.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/star-table/lesscode-form" > /data/ucov/repro/jsoup/ClientInfos/star-table______lesscode-form.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/felippepg/simpleCrawler" > /data/ucov/repro/jsoup/ClientInfos/felippepg______simpleCrawler.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/automationbytes/TestNG_POM_Aug_2023" > /data/ucov/repro/jsoup/ClientInfos/automationbytes______TestNG_POM_Aug_2023.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/srival1/internetBankingV2" > /data/ucov/repro/jsoup/ClientInfos/srival1______internetBankingV2.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/seomar2022/caesar" > /data/ucov/repro/jsoup/ClientInfos/seomar2022______caesar.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Callian/devsecops-gitlab-java-vulnerable-application" > /data/ucov/repro/jsoup/ClientInfos/Callian______devsecops-gitlab-java-vulnerable-application.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/AleksM86/SearchEngine" > /data/ucov/repro/jsoup/ClientInfos/AleksM86______SearchEngine.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/hxc236/SE-practical-traing" > /data/ucov/repro/jsoup/ClientInfos/hxc236______SE-practical-traing.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/sqlidan/CCLI" > /data/ucov/repro/jsoup/ClientInfos/sqlidan______CCLI.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/PastorGL/datacooker-etl" > /data/ucov/repro/jsoup/ClientInfos/PastorGL______datacooker-etl.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Super-nerd-ctrl/yusou-backend" > /data/ucov/repro/jsoup/ClientInfos/Super-nerd-ctrl______yusou-backend.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/favsarfavsar/ctech" > /data/ucov/repro/jsoup/ClientInfos/favsarfavsar______ctech.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/klintron-test-org/web-goat-3" > /data/ucov/repro/jsoup/ClientInfos/klintron-test-org______web-goat-3.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/HighlandProger/LivingWageBot" > /data/ucov/repro/jsoup/ClientInfos/HighlandProger______LivingWageBot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Datasiast/ghas-bootcamp-webgoat" > /data/ucov/repro/jsoup/ClientInfos/Datasiast______ghas-bootcamp-webgoat.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/laxmangandi369/Auth0LoginExample" > /data/ucov/repro/jsoup/ClientInfos/laxmangandi369______Auth0LoginExample.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/d4span/freemind" > /data/ucov/repro/jsoup/ClientInfos/d4span______freemind.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/rowan-tich/busybadgerscraper" > /data/ucov/repro/jsoup/ClientInfos/rowan-tich______busybadgerscraper.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/leyla1991/job4j_grabber" > /data/ucov/repro/jsoup/ClientInfos/leyla1991______job4j_grabber.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/kgobemoses/farming" > /data/ucov/repro/jsoup/ClientInfos/kgobemoses______farming.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/khurshidbek-bakhromjonov/EPAM-training" > /data/ucov/repro/jsoup/ClientInfos/khurshidbek-bakhromjonov______EPAM-training.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/BenHamoudaHichem/TnCities" > /data/ucov/repro/jsoup/ClientInfos/BenHamoudaHichem______TnCities.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/kingbaibai/myleadnews" > /data/ucov/repro/jsoup/ClientInfos/kingbaibai______myleadnews.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ircecam/module_12" > /data/ucov/repro/jsoup/ClientInfos/ircecam______module_12.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/bengmend/WebGoat" > /data/ucov/repro/jsoup/ClientInfos/bengmend______WebGoat.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/HubSpot/maven-dependency-plugin" > /data/ucov/repro/jsoup/ClientInfos/HubSpot______maven-dependency-plugin.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Alexandre-COURBOIS/NFS_LAGOSANTO_ALGORITHME" > /data/ucov/repro/jsoup/ClientInfos/Alexandre-COURBOIS______NFS_LAGOSANTO_ALGORITHME.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/monaztic/youtube-local-compare" > /data/ucov/repro/jsoup/ClientInfos/monaztic______youtube-local-compare.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/SouljaBoy-tell-em/NetCracker" > /data/ucov/repro/jsoup/ClientInfos/SouljaBoy-tell-em______NetCracker.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/chkal/junit-xml-transform-plugin" > /data/ucov/repro/jsoup/ClientInfos/chkal______junit-xml-transform-plugin.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/windseedgee/EMAN" > /data/ucov/repro/jsoup/ClientInfos/windseedgee______EMAN.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/kd-praveen/web-scrapping-springboot" > /data/ucov/repro/jsoup/ClientInfos/kd-praveen______web-scrapping-springboot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/hqgaofeng/cnceact" > /data/ucov/repro/jsoup/ClientInfos/hqgaofeng______cnceact.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/KevinGaoZF/spring-boot-demo" > /data/ucov/repro/jsoup/ClientInfos/KevinGaoZF______spring-boot-demo.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/BesyadaV/WebGoat" > /data/ucov/repro/jsoup/ClientInfos/BesyadaV______WebGoat.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/rostislavYurievich/java_labs" > /data/ucov/repro/jsoup/ClientInfos/rostislavYurievich______java_labs.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/vishnukolluri/RewardCalculator" > /data/ucov/repro/jsoup/ClientInfos/vishnukolluri______RewardCalculator.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/fawMetersphere/metersphere" > /data/ucov/repro/jsoup/ClientInfos/fawMetersphere______metersphere.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/charlielduong/charliewebapps" > /data/ucov/repro/jsoup/ClientInfos/charlielduong______charliewebapps.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Spartak101/java_basics" > /data/ucov/repro/jsoup/ClientInfos/Spartak101______java_basics.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/BussanQ/MySpringboot-KuangJia" > /data/ucov/repro/jsoup/ClientInfos/BussanQ______MySpringboot-KuangJia.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/chanhyub/Gimhae-Swim" > /data/ucov/repro/jsoup/ClientInfos/chanhyub______Gimhae-Swim.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/yujinn001/Spring" > /data/ucov/repro/jsoup/ClientInfos/yujinn001______Spring.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/HL-eng/git-demo" > /data/ucov/repro/jsoup/ClientInfos/HL-eng______git-demo.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Baeyonghyeon/NoticeBoard" > /data/ucov/repro/jsoup/ClientInfos/Baeyonghyeon______NoticeBoard.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/rajiselva05/MovieBooking" > /data/ucov/repro/jsoup/ClientInfos/rajiselva05______MovieBooking.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ZakharovNerd/metadata-extractor-java" > /data/ucov/repro/jsoup/ClientInfos/ZakharovNerd______metadata-extractor-java.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/JessySnow/zhizhuzi" > /data/ucov/repro/jsoup/ClientInfos/JessySnow______zhizhuzi.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/hanseongv/DCardGame" > /data/ucov/repro/jsoup/ClientInfos/hanseongv______DCardGame.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ppppps5/noticeForProfessional" > /data/ucov/repro/jsoup/ClientInfos/ppppps5______noticeForProfessional.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/StanislavBozhko/web-parsing-indexing-search" > /data/ucov/repro/jsoup/ClientInfos/StanislavBozhko______web-parsing-indexing-search.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/2278686667/spider-flow" > /data/ucov/repro/jsoup/ClientInfos/2278686667______spider-flow.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/lztXiaoG/12011417lab3" > /data/ucov/repro/jsoup/ClientInfos/lztXiaoG______12011417lab3.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/yexuejc/solo" > /data/ucov/repro/jsoup/ClientInfos/yexuejc______solo.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/svn131/ZaprosKakOtBrauzera" > /data/ucov/repro/jsoup/ClientInfos/svn131______ZaprosKakOtBrauzera.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/tangxiqqq/SSTL" > /data/ucov/repro/jsoup/ClientInfos/tangxiqqq______SSTL.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/tonifdemocorp1-Mend/WebGoat" > /data/ucov/repro/jsoup/ClientInfos/tonifdemocorp1-Mend______WebGoat.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ryhaldenys/Poems" > /data/ucov/repro/jsoup/ClientInfos/ryhaldenys______Poems.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/IliasBrinias/SpaceRoomApi" > /data/ucov/repro/jsoup/ClientInfos/IliasBrinias______SpaceRoomApi.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/VassBass/webparser" > /data/ucov/repro/jsoup/ClientInfos/VassBass______webparser.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/seonghuncode/CrawlingOss" > /data/ucov/repro/jsoup/ClientInfos/seonghuncode______CrawlingOss.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Nasc1mento/TrieSearchGUI" > /data/ucov/repro/jsoup/ClientInfos/Nasc1mento______TrieSearchGUI.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Mohesh-Borah/aem-core-components" > /data/ucov/repro/jsoup/ClientInfos/Mohesh-Borah______aem-core-components.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Choudhary1986/Cassandra" > /data/ucov/repro/jsoup/ClientInfos/Choudhary1986______Cassandra.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/wangy-thu/e-commerce-skynet" > /data/ucov/repro/jsoup/ClientInfos/wangy-thu______e-commerce-skynet.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/jananiorganiza/test5" > /data/ucov/repro/jsoup/ClientInfos/jananiorganiza______test5.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/OpenSundsvall/api-service-archive" > /data/ucov/repro/jsoup/ClientInfos/OpenSundsvall______api-service-archive.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/cdrommens/comicosmos" > /data/ucov/repro/jsoup/ClientInfos/cdrommens______comicosmos.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Wassermanreaction/MTG_Deck_Manager" > /data/ucov/repro/jsoup/ClientInfos/Wassermanreaction______MTG_Deck_Manager.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/YannisTzitzikas/CS561playground" > /data/ucov/repro/jsoup/ClientInfos/YannisTzitzikas______CS561playground.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/TansanMilMil/birds-eye-scraping" > /data/ucov/repro/jsoup/ClientInfos/TansanMilMil______birds-eye-scraping.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/cornetto013/spring-tutorials" > /data/ucov/repro/jsoup/ClientInfos/cornetto013______spring-tutorials.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/anhchangaotim89/WebGoat" > /data/ucov/repro/jsoup/ClientInfos/anhchangaotim89______WebGoat.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/bakero10/Programacion_Servicios_Y_Procesos" > /data/ucov/repro/jsoup/ClientInfos/bakero10______Programacion_Servicios_Y_Procesos.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/richard5zx/others" > /data/ucov/repro/jsoup/ClientInfos/richard5zx______others.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/uni-aau/cleancode-webcrawler" > /data/ucov/repro/jsoup/ClientInfos/uni-aau______cleancode-webcrawler.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/lykkeee/SpringBoredomHelperBot" > /data/ucov/repro/jsoup/ClientInfos/lykkeee______SpringBoredomHelperBot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/syc98syc/KB04_TeamProject" > /data/ucov/repro/jsoup/ClientInfos/syc98syc______KB04_TeamProject.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/coshelev/jp4v1" > /data/ucov/repro/jsoup/ClientInfos/coshelev______jp4v1.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ThakurMangesh2171/docker" > /data/ucov/repro/jsoup/ClientInfos/ThakurMangesh2171______docker.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/WuYff/flow-cve" > /data/ucov/repro/jsoup/ClientInfos/WuYff______flow-cve.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/LukaMaranic/AtlassianJava" > /data/ucov/repro/jsoup/ClientInfos/LukaMaranic______AtlassianJava.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Randyblo7/openhab-addons" > /data/ucov/repro/jsoup/ClientInfos/Randyblo7______openhab-addons.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/zhu-niubi/personal-blog" > /data/ucov/repro/jsoup/ClientInfos/zhu-niubi______personal-blog.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/johancc/software-product-sprint-2022" > /data/ucov/repro/jsoup/ClientInfos/johancc______software-product-sprint-2022.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/leedyx/wcbot" > /data/ucov/repro/jsoup/ClientInfos/leedyx______wcbot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/seonysun/HelloBoot" > /data/ucov/repro/jsoup/ClientInfos/seonysun______HelloBoot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/YeeZC/java-profiler" > /data/ucov/repro/jsoup/ClientInfos/YeeZC______java-profiler.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/2yu33/FileConverter" > /data/ucov/repro/jsoup/ClientInfos/2yu33______FileConverter.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/nkanyisom/Vulnado" > /data/ucov/repro/jsoup/ClientInfos/nkanyisom______Vulnado.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/skillbox-java/images_downloader" > /data/ucov/repro/jsoup/ClientInfos/skillbox-java______images_downloader.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/yasineryigit/Currency-Socket" > /data/ucov/repro/jsoup/ClientInfos/yasineryigit______Currency-Socket.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/franciscotis/simple-library-api" > /data/ucov/repro/jsoup/ClientInfos/franciscotis______simple-library-api.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/thek2range/OrNG" > /data/ucov/repro/jsoup/ClientInfos/thek2range______OrNG.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/kavitbang/WebGoat" > /data/ucov/repro/jsoup/ClientInfos/kavitbang______WebGoat.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Csanoo/kevic" > /data/ucov/repro/jsoup/ClientInfos/Csanoo______kevic.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/JackWang1230/knowledge-learning-summary" > /data/ucov/repro/jsoup/ClientInfos/JackWang1230______knowledge-learning-summary.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/MohammedThalha2002/training-module-system-backend" > /data/ucov/repro/jsoup/ClientInfos/MohammedThalha2002______training-module-system-backend.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/SINGALman/fang" > /data/ucov/repro/jsoup/ClientInfos/SINGALman______fang.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/milan011/flowing-project" > /data/ucov/repro/jsoup/ClientInfos/milan011______flowing-project.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/KWONSUYEO/TeamProject" > /data/ucov/repro/jsoup/ClientInfos/KWONSUYEO______TeamProject.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/carlucci71/colossium" > /data/ucov/repro/jsoup/ClientInfos/carlucci71______colossium.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/enesbahtiyar/PortfolioGameWebsite" > /data/ucov/repro/jsoup/ClientInfos/enesbahtiyar______PortfolioGameWebsite.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/pavithrahatharasinghe/Melody" > /data/ucov/repro/jsoup/ClientInfos/pavithrahatharasinghe______Melody.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/open-vertical-media/open-nav" > /data/ucov/repro/jsoup/ClientInfos/open-vertical-media______open-nav.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/klaud-speech/jsoup" > /data/ucov/repro/jsoup/ClientInfos/klaud-speech______jsoup.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/minhyeok08/springBoot" > /data/ucov/repro/jsoup/ClientInfos/minhyeok08______springBoot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/dringdwing/ManagementProject" > /data/ucov/repro/jsoup/ClientInfos/dringdwing______ManagementProject.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/yangyang1040553/testjava" > /data/ucov/repro/jsoup/ClientInfos/yangyang1040553______testjava.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/hanqiufengGit/sanri-tools-maven" > /data/ucov/repro/jsoup/ClientInfos/hanqiufengGit______sanri-tools-maven.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/elivinus/webgoat" > /data/ucov/repro/jsoup/ClientInfos/elivinus______webgoat.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Shimadzusan/dataAnalyzer" > /data/ucov/repro/jsoup/ClientInfos/Shimadzusan______dataAnalyzer.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/RePlaze/LoL_Bot" > /data/ucov/repro/jsoup/ClientInfos/RePlaze______LoL_Bot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/FabuDev7/MangaApp" > /data/ucov/repro/jsoup/ClientInfos/FabuDev7______MangaApp.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/akashgupta2307g/Smart-Buyer-" > /data/ucov/repro/jsoup/ClientInfos/akashgupta2307g______Smart-Buyer-.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/doecode/server" > /data/ucov/repro/jsoup/ClientInfos/doecode______server.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Ansdance/Nike" > /data/ucov/repro/jsoup/ClientInfos/Ansdance______Nike.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/yx-Yaoxaing/these-thing" > /data/ucov/repro/jsoup/ClientInfos/yx-Yaoxaing______these-thing.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ginkotte/railwayGenerator" > /data/ucov/repro/jsoup/ClientInfos/ginkotte______railwayGenerator.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/mrAntonZenkov/ForkJoinPool" > /data/ucov/repro/jsoup/ClientInfos/mrAntonZenkov______ForkJoinPool.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/dangngocphuc/DATN-BE" > /data/ucov/repro/jsoup/ClientInfos/dangngocphuc______DATN-BE.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/DojinP/metahouse" > /data/ucov/repro/jsoup/ClientInfos/DojinP______metahouse.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ddaGarrido/oauth" > /data/ucov/repro/jsoup/ClientInfos/ddaGarrido______oauth.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/lycGitHub123/MallChat" > /data/ucov/repro/jsoup/ClientInfos/lycGitHub123______MallChat.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/MurtazoLutfulloyev/give-bot" > /data/ucov/repro/jsoup/ClientInfos/MurtazoLutfulloyev______give-bot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/RuidiChang/Distributed-Systems" > /data/ucov/repro/jsoup/ClientInfos/RuidiChang______Distributed-Systems.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/gbdishant/Website-Contact-Detail" > /data/ucov/repro/jsoup/ClientInfos/gbdishant______Website-Contact-Detail.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/amineMbarki1/local_news_miner" > /data/ucov/repro/jsoup/ClientInfos/amineMbarki1______local_news_miner.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/PastushenkoIlya/CitiesGame" > /data/ucov/repro/jsoup/ClientInfos/PastushenkoIlya______CitiesGame.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/wmz-personal/heima-leadnews" > /data/ucov/repro/jsoup/ClientInfos/wmz-personal______heima-leadnews.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/pyatikin/ParseHabr" > /data/ucov/repro/jsoup/ClientInfos/pyatikin______ParseHabr.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/paramint/Autowasp" > /data/ucov/repro/jsoup/ClientInfos/paramint______Autowasp.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/MaxAntonioDeSouza/test-jenkins" > /data/ucov/repro/jsoup/ClientInfos/MaxAntonioDeSouza______test-jenkins.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/rajeshyemul/Java_Selenium_Framework2" > /data/ucov/repro/jsoup/ClientInfos/rajeshyemul______Java_Selenium_Framework2.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ankit979n/Web-Scraping-using-Java" > /data/ucov/repro/jsoup/ClientInfos/ankit979n______Web-Scraping-using-Java.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/kvn746/store_grabber" > /data/ucov/repro/jsoup/ClientInfos/kvn746______store_grabber.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/spitty/VKConnector" > /data/ucov/repro/jsoup/ClientInfos/spitty______VKConnector.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/DreamFlower14/MongoPRJ" > /data/ucov/repro/jsoup/ClientInfos/DreamFlower14______MongoPRJ.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/100rootrain/KeunWooRepository" > /data/ucov/repro/jsoup/ClientInfos/100rootrain______KeunWooRepository.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/shk95/GitEditor-backend" > /data/ucov/repro/jsoup/ClientInfos/shk95______GitEditor-backend.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/OneDayOnePost/ODOP" > /data/ucov/repro/jsoup/ClientInfos/OneDayOnePost______ODOP.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ChristinaK97/KnowledgeGraphs" > /data/ucov/repro/jsoup/ClientInfos/ChristinaK97______KnowledgeGraphs.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/karimerri04/Azelha" > /data/ucov/repro/jsoup/ClientInfos/karimerri04______Azelha.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/finos/legend-engine" > /data/ucov/repro/jsoup/ClientInfos/finos______legend-engine.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/tyronewj/FakeNetEaseMusicPlayer" > /data/ucov/repro/jsoup/ClientInfos/tyronewj______FakeNetEaseMusicPlayer.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/neatlogic/neatlogic-parent" > /data/ucov/repro/jsoup/ClientInfos/neatlogic______neatlogic-parent.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/SimonRth/Scrapper_JAVA" > /data/ucov/repro/jsoup/ClientInfos/SimonRth______Scrapper_JAVA.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/xiaofan0408/View-Back-End" > /data/ucov/repro/jsoup/ClientInfos/xiaofan0408______View-Back-End.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/eahau/douyin-openapi" > /data/ucov/repro/jsoup/ClientInfos/eahau______douyin-openapi.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/chlwjddn7/spring-legacy-proejct-sample" > /data/ucov/repro/jsoup/ClientInfos/chlwjddn7______spring-legacy-proejct-sample.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/bigskysoftware/chill" > /data/ucov/repro/jsoup/ClientInfos/bigskysoftware______chill.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/TobiasTheDanish/MovieScraping" > /data/ucov/repro/jsoup/ClientInfos/TobiasTheDanish______MovieScraping.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/DannyGalvan/Project_boletos" > /data/ucov/repro/jsoup/ClientInfos/DannyGalvan______Project_boletos.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Satyabrata6gb/Twitter-Clone" > /data/ucov/repro/jsoup/ClientInfos/Satyabrata6gb______Twitter-Clone.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/RacabRasulov/ariwalPort" > /data/ucov/repro/jsoup/ClientInfos/RacabRasulov______ariwalPort.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/zhangjushun/xms-base" > /data/ucov/repro/jsoup/ClientInfos/zhangjushun______xms-base.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/xiphis/swingutils" > /data/ucov/repro/jsoup/ClientInfos/xiphis______swingutils.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/priyamtiwari1245/SearchEngine" > /data/ucov/repro/jsoup/ClientInfos/priyamtiwari1245______SearchEngine.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/hassanazh-telenor/Webgoat-Devops" > /data/ucov/repro/jsoup/ClientInfos/hassanazh-telenor______Webgoat-Devops.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/kylelin1998/ReleasesMonitorTelegramBot" > /data/ucov/repro/jsoup/ClientInfos/kylelin1998______ReleasesMonitorTelegramBot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/SAP-samples/security-research-cruzzer" > /data/ucov/repro/jsoup/ClientInfos/SAP-samples______security-research-cruzzer.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Ngazoa/ci-cd" > /data/ucov/repro/jsoup/ClientInfos/Ngazoa______ci-cd.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/pologood/anvars" > /data/ucov/repro/jsoup/ClientInfos/pologood______anvars.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/spiliti/oldgrams" > /data/ucov/repro/jsoup/ClientInfos/spiliti______oldgrams.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/AP-Kai/MyWebScanner" > /data/ucov/repro/jsoup/ClientInfos/AP-Kai______MyWebScanner.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/danielgoren14/CurrencyExchangeRate1" > /data/ucov/repro/jsoup/ClientInfos/danielgoren14______CurrencyExchangeRate1.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/bellmit/andwell235" > /data/ucov/repro/jsoup/ClientInfos/bellmit______andwell235.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Chiping28/WeatherParser" > /data/ucov/repro/jsoup/ClientInfos/Chiping28______WeatherParser.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/go-for-naver/Spring_Legacy_Templates" > /data/ucov/repro/jsoup/ClientInfos/go-for-naver______Spring_Legacy_Templates.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/markarko/dawson-scheduler-api" > /data/ucov/repro/jsoup/ClientInfos/markarko______dawson-scheduler-api.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/MYEHUB0/starlink" > /data/ucov/repro/jsoup/ClientInfos/MYEHUB0______starlink.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/JVictorC/partly-repo" > /data/ucov/repro/jsoup/ClientInfos/JVictorC______partly-repo.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Dima2021/SecShepherdReachability" > /data/ucov/repro/jsoup/ClientInfos/Dima2021______SecShepherdReachability.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/SamudithaD97/ElctroGrid-Individual" > /data/ucov/repro/jsoup/ClientInfos/SamudithaD97______ElctroGrid-Individual.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/guy0090/bdo-market-api" > /data/ucov/repro/jsoup/ClientInfos/guy0090______bdo-market-api.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/JeraCodeHub/testPublic" > /data/ucov/repro/jsoup/ClientInfos/JeraCodeHub______testPublic.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Ahmadedu/webgoat" > /data/ucov/repro/jsoup/ClientInfos/Ahmadedu______webgoat.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/HariharanBaskarraj/Camunda8" > /data/ucov/repro/jsoup/ClientInfos/HariharanBaskarraj______Camunda8.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/alex-petkevich/joplin-forwarder-server" > /data/ucov/repro/jsoup/ClientInfos/alex-petkevich______joplin-forwarder-server.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/sudham16/WebDataExtractor" > /data/ucov/repro/jsoup/ClientInfos/sudham16______WebDataExtractor.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/GDj001010/springstudy" > /data/ucov/repro/jsoup/ClientInfos/GDj001010______springstudy.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/MikolaChe/JavaSpringTelegramBot" > /data/ucov/repro/jsoup/ClientInfos/MikolaChe______JavaSpringTelegramBot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/qatester121/filpkart" > /data/ucov/repro/jsoup/ClientInfos/qatester121______filpkart.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/gag068/WebGoat1" > /data/ucov/repro/jsoup/ClientInfos/gag068______WebGoat1.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/liubangde88/oooo" > /data/ucov/repro/jsoup/ClientInfos/liubangde88______oooo.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/rakeshthumar111/WebGoat-DevOps" > /data/ucov/repro/jsoup/ClientInfos/rakeshthumar111______WebGoat-DevOps.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/alexves-b/searchengine" > /data/ucov/repro/jsoup/ClientInfos/alexves-b______searchengine.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Kolivim/search-engine" > /data/ucov/repro/jsoup/ClientInfos/Kolivim______search-engine.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/CMTcode/sign-in-assistant" > /data/ucov/repro/jsoup/ClientInfos/CMTcode______sign-in-assistant.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/arkadasgupta17/TeamSAP" > /data/ucov/repro/jsoup/ClientInfos/arkadasgupta17______TeamSAP.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/DDOSer1337/SiteSearchEngine" > /data/ucov/repro/jsoup/ClientInfos/DDOSer1337______SiteSearchEngine.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/nylm9/MovieReservation" > /data/ucov/repro/jsoup/ClientInfos/nylm9______MovieReservation.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/nikitinaak/Search_engine" > /data/ucov/repro/jsoup/ClientInfos/nikitinaak______Search_engine.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/HihaoWang/123" > /data/ucov/repro/jsoup/ClientInfos/HihaoWang______123.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/XAHTEPC/MyCarManager" > /data/ucov/repro/jsoup/ClientInfos/XAHTEPC______MyCarManager.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/timi137137/EatWhatLibrary" > /data/ucov/repro/jsoup/ClientInfos/timi137137______EatWhatLibrary.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/bootiful-podcast/podcast-search-service" > /data/ucov/repro/jsoup/ClientInfos/bootiful-podcast______podcast-search-service.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Cupcake-master/2023_ITIS_IS_11-906_BilalovBF" > /data/ucov/repro/jsoup/ClientInfos/Cupcake-master______2023_ITIS_IS_11-906_BilalovBF.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/cristiantfs/Web-goat-code-test" > /data/ucov/repro/jsoup/ClientInfos/cristiantfs______Web-goat-code-test.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/DataGremlin/SonarBot" > /data/ucov/repro/jsoup/ClientInfos/DataGremlin______SonarBot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/shiva-art/webgoat2906" > /data/ucov/repro/jsoup/ClientInfos/shiva-art______webgoat2906.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/liwagu/liwa-so" > /data/ucov/repro/jsoup/ClientInfos/liwagu______liwa-so.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/zhongfeather/JAVA-" > /data/ucov/repro/jsoup/ClientInfos/zhongfeather______JAVA-.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/webbnba/restaurant_voting" > /data/ucov/repro/jsoup/ClientInfos/webbnba______restaurant_voting.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Evolution-X/external_cldr" > /data/ucov/repro/jsoup/ClientInfos/Evolution-X______external_cldr.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/bentrieu/NRA" > /data/ucov/repro/jsoup/ClientInfos/bentrieu______NRA.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/swade222/UCSDstarter" > /data/ucov/repro/jsoup/ClientInfos/swade222______UCSDstarter.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/indexss/EMeiYou" > /data/ucov/repro/jsoup/ClientInfos/indexss______EMeiYou.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/GhofraneFerchichi/blog-front" > /data/ucov/repro/jsoup/ClientInfos/GhofraneFerchichi______blog-front.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/dharanimoram/yourstoreapplication" > /data/ucov/repro/jsoup/ClientInfos/dharanimoram______yourstoreapplication.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/aiapo/RepoGrabber" > /data/ucov/repro/jsoup/ClientInfos/aiapo______RepoGrabber.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/yangjing-start/GXA-web" > /data/ucov/repro/jsoup/ClientInfos/yangjing-start______GXA-web.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/surajkr23/GmailAPI" > /data/ucov/repro/jsoup/ClientInfos/surajkr23______GmailAPI.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/MatejBujdak/Webcrawler_oldversion" > /data/ucov/repro/jsoup/ClientInfos/MatejBujdak______Webcrawler_oldversion.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/sukhi90/simpli-project" > /data/ucov/repro/jsoup/ClientInfos/sukhi90______simpli-project.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/leRequiem/BD" > /data/ucov/repro/jsoup/ClientInfos/leRequiem______BD.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/yuejianli/Stock_Api" > /data/ucov/repro/jsoup/ClientInfos/yuejianli______Stock_Api.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Christianqling2/Haggle" > /data/ucov/repro/jsoup/ClientInfos/Christianqling2______Haggle.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/kiransg89/chatgpt" > /data/ucov/repro/jsoup/ClientInfos/kiransg89______chatgpt.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/EvgeniiSamarin/JavaCrawler" > /data/ucov/repro/jsoup/ClientInfos/EvgeniiSamarin______JavaCrawler.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/yazsul/media-nav" > /data/ucov/repro/jsoup/ClientInfos/yazsul______media-nav.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/END888/yincy-springboot-init" > /data/ucov/repro/jsoup/ClientInfos/END888______yincy-springboot-init.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/RSHKwee/GnuCashCharts" > /data/ucov/repro/jsoup/ClientInfos/RSHKwee______GnuCashCharts.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/dzasta997/super_projekt" > /data/ucov/repro/jsoup/ClientInfos/dzasta997______super_projekt.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/emretterzi/Scraper-App-Web" > /data/ucov/repro/jsoup/ClientInfos/emretterzi______Scraper-App-Web.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/sergey-zabolotnyi/javaPro" > /data/ucov/repro/jsoup/ClientInfos/sergey-zabolotnyi______javaPro.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/jaimeizuz/jenkins-docker" > /data/ucov/repro/jsoup/ClientInfos/jaimeizuz______jenkins-docker.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/yeozhenhao/Java_HTMLtoPDF" > /data/ucov/repro/jsoup/ClientInfos/yeozhenhao______Java_HTMLtoPDF.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Void-XKG/test01" > /data/ucov/repro/jsoup/ClientInfos/Void-XKG______test01.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Nipuna1234567/ElectroGrid" > /data/ucov/repro/jsoup/ClientInfos/Nipuna1234567______ElectroGrid.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/maz004/webgoqt2" > /data/ucov/repro/jsoup/ClientInfos/maz004______webgoqt2.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Alicechui/Web-Scraping-NLP-App" > /data/ucov/repro/jsoup/ClientInfos/Alicechui______Web-Scraping-NLP-App.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/icWinter/common-util" > /data/ucov/repro/jsoup/ClientInfos/icWinter______common-util.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ZMitya9/SearchEngine" > /data/ucov/repro/jsoup/ClientInfos/ZMitya9______SearchEngine.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/yasith1234/CustomerManagement" > /data/ucov/repro/jsoup/ClientInfos/yasith1234______CustomerManagement.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/yzqnmg/heima-leadnews" > /data/ucov/repro/jsoup/ClientInfos/yzqnmg______heima-leadnews.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ircecam/module_10" > /data/ucov/repro/jsoup/ClientInfos/ircecam______module_10.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Exanily/java_basics" > /data/ucov/repro/jsoup/ClientInfos/Exanily______java_basics.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/saulmella12/Formula1" > /data/ucov/repro/jsoup/ClientInfos/saulmella12______Formula1.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/daomanhluan/ai.stock" > /data/ucov/repro/jsoup/ClientInfos/daomanhluan______ai.stock.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/victory460/K8S" > /data/ucov/repro/jsoup/ClientInfos/victory460______K8S.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/guzevka/telegram-bot" > /data/ucov/repro/jsoup/ClientInfos/guzevka______telegram-bot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/brianb1996/CompSci_2261-Project-6" > /data/ucov/repro/jsoup/ClientInfos/brianb1996______CompSci_2261-Project-6.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Nasidiqi/ControversyInNews" > /data/ucov/repro/jsoup/ClientInfos/Nasidiqi______ControversyInNews.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/karimyasser107/search-engine-java" > /data/ucov/repro/jsoup/ClientInfos/karimyasser107______search-engine-java.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/1975947214/paicoding" > /data/ucov/repro/jsoup/ClientInfos/1975947214______paicoding.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/spacezyx/DataGovernancePlatform_Backend" > /data/ucov/repro/jsoup/ClientInfos/spacezyx______DataGovernancePlatform_Backend.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/timbercld/timbercld-sys-service" > /data/ucov/repro/jsoup/ClientInfos/timbercld______timbercld-sys-service.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/tianxiaotouyuna/lianghua_java_service" > /data/ucov/repro/jsoup/ClientInfos/tianxiaotouyuna______lianghua_java_service.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/jwdeveloper/TikTokLiveJava" > /data/ucov/repro/jsoup/ClientInfos/jwdeveloper______TikTokLiveJava.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/EsionCHEN/Esion" > /data/ucov/repro/jsoup/ClientInfos/EsionCHEN______Esion.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/globalbioticinteractions/nomer" > /data/ucov/repro/jsoup/ClientInfos/globalbioticinteractions______nomer.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/botkoda/moex" > /data/ucov/repro/jsoup/ClientInfos/botkoda______moex.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/backendgame/JavaBackend" > /data/ucov/repro/jsoup/ClientInfos/backendgame______JavaBackend.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/DGoyal29/Maven-dependency" > /data/ucov/repro/jsoup/ClientInfos/DGoyal29______Maven-dependency.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/AlexandrKhalilulin/crypto" > /data/ucov/repro/jsoup/ClientInfos/AlexandrKhalilulin______crypto.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/KingPrimes/NyxBot" > /data/ucov/repro/jsoup/ClientInfos/KingPrimes______NyxBot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/woshilmx/animer-backend" > /data/ucov/repro/jsoup/ClientInfos/woshilmx______animer-backend.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/AnnaPotupalo/QuotesRunet_github" > /data/ucov/repro/jsoup/ClientInfos/AnnaPotupalo______QuotesRunet_github.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/SadCryFamily/DataOxScrapingTask" > /data/ucov/repro/jsoup/ClientInfos/SadCryFamily______DataOxScrapingTask.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/AlekseyShibayev/additional-education-info" > /data/ucov/repro/jsoup/ClientInfos/AlekseyShibayev______additional-education-info.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/jaig1995/accionistas-eebp" > /data/ucov/repro/jsoup/ClientInfos/jaig1995______accionistas-eebp.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Aztroe/Scraper" > /data/ucov/repro/jsoup/ClientInfos/Aztroe______Scraper.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/AndreiBudevich/cryptocurrencywatcher" > /data/ucov/repro/jsoup/ClientInfos/AndreiBudevich______cryptocurrencywatcher.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/oropeza/sat-cfdi-web-scraper" > /data/ucov/repro/jsoup/ClientInfos/oropeza______sat-cfdi-web-scraper.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/dhieff73/CampsideForumBackend" > /data/ucov/repro/jsoup/ClientInfos/dhieff73______CampsideForumBackend.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/shinyeeun789/haebeop" > /data/ucov/repro/jsoup/ClientInfos/shinyeeun789______haebeop.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/saifali1035/Jenkins-ZerotoHero" > /data/ucov/repro/jsoup/ClientInfos/saifali1035______Jenkins-ZerotoHero.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/5kylight/wikiscrap" > /data/ucov/repro/jsoup/ClientInfos/5kylight______wikiscrap.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/evgenyzhulpa/searchengine" > /data/ucov/repro/jsoup/ClientInfos/evgenyzhulpa______searchengine.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/AlejandraMUBA/3_WebGoat-JAVA" > /data/ucov/repro/jsoup/ClientInfos/AlejandraMUBA______3_WebGoat-JAVA.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/duTianze/memo" > /data/ucov/repro/jsoup/ClientInfos/duTianze______memo.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/rezzgabriel/webcrawler" > /data/ucov/repro/jsoup/ClientInfos/rezzgabriel______webcrawler.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/addy360/whizzy" > /data/ucov/repro/jsoup/ClientInfos/addy360______whizzy.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Mutess/SpringStudy" > /data/ucov/repro/jsoup/ClientInfos/Mutess______SpringStudy.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Maxbleu/AccountManager" > /data/ucov/repro/jsoup/ClientInfos/Maxbleu______AccountManager.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/RolinFirelink/orange-backend" > /data/ucov/repro/jsoup/ClientInfos/RolinFirelink______orange-backend.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/jt5766/final_project" > /data/ucov/repro/jsoup/ClientInfos/jt5766______final_project.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ritesh107/jenkinsbackup" > /data/ucov/repro/jsoup/ClientInfos/ritesh107______jenkinsbackup.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/chiencao2402/BookShop1234" > /data/ucov/repro/jsoup/ClientInfos/chiencao2402______BookShop1234.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/lequangtoi202/good_news" > /data/ucov/repro/jsoup/ClientInfos/lequangtoi202______good_news.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/chen769330532/20230309" > /data/ucov/repro/jsoup/ClientInfos/chen769330532______20230309.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/thirtycapital/hanger" > /data/ucov/repro/jsoup/ClientInfos/thirtycapital______hanger.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/jainteg2/jainteg2" > /data/ucov/repro/jsoup/ClientInfos/jainteg2______jainteg2.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/a943356255/GrouthRecord" > /data/ucov/repro/jsoup/ClientInfos/a943356255______GrouthRecord.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Adact-NGN/priskalkulator-service" > /data/ucov/repro/jsoup/ClientInfos/Adact-NGN______priskalkulator-service.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/jaymulani/ScraperSmart" > /data/ucov/repro/jsoup/ClientInfos/jaymulani______ScraperSmart.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/yinxs2003/flink" > /data/ucov/repro/jsoup/ClientInfos/yinxs2003______flink.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ProductManage-Leo/alldata" > /data/ucov/repro/jsoup/ClientInfos/ProductManage-Leo______alldata.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/SulaimanHumaid/ParallelWebCrawler" > /data/ucov/repro/jsoup/ClientInfos/SulaimanHumaid______ParallelWebCrawler.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/gopichandpuli06/lab1" > /data/ucov/repro/jsoup/ClientInfos/gopichandpuli06______lab1.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Arielnoder/news" > /data/ucov/repro/jsoup/ClientInfos/Arielnoder______news.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Lees0-0/Team_project_group_3" > /data/ucov/repro/jsoup/ClientInfos/Lees0-0______Team_project_group_3.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/nareshbabumandula/Flipkart_Automation" > /data/ucov/repro/jsoup/ClientInfos/nareshbabumandula______Flipkart_Automation.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/akter4855/Group-B" > /data/ucov/repro/jsoup/ClientInfos/akter4855______Group-B.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Hooorus/mshive-backend" > /data/ucov/repro/jsoup/ClientInfos/Hooorus______mshive-backend.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/pantelicn/nms-be" > /data/ucov/repro/jsoup/ClientInfos/pantelicn______nms-be.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/rodrigobash-eld/gitlab-java-vuln" > /data/ucov/repro/jsoup/ClientInfos/rodrigobash-eld______gitlab-java-vuln.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ctcampbellcom/WebGoat" > /data/ucov/repro/jsoup/ClientInfos/ctcampbellcom______WebGoat.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Kevil-Karnage/WHO_WINS" > /data/ucov/repro/jsoup/ClientInfos/Kevil-Karnage______WHO_WINS.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/GuardMY/demo" > /data/ucov/repro/jsoup/ClientInfos/GuardMY______demo.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Jxxchxn/Board" > /data/ucov/repro/jsoup/ClientInfos/Jxxchxn______Board.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/SulthanFahrein/UAS_ConfigMaster_MKPL" > /data/ucov/repro/jsoup/ClientInfos/SulthanFahrein______UAS_ConfigMaster_MKPL.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/suryaoff/Weby" > /data/ucov/repro/jsoup/ClientInfos/suryaoff______Weby.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/junkkookk/saffron_cloud" > /data/ucov/repro/jsoup/ClientInfos/junkkookk______saffron_cloud.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ekgame/storasbot" > /data/ucov/repro/jsoup/ClientInfos/ekgame______storasbot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/PattonLi/music-player-server-java" > /data/ucov/repro/jsoup/ClientInfos/PattonLi______music-player-server-java.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/AvihayBenAmi/MonitoringSystem" > /data/ucov/repro/jsoup/ClientInfos/AvihayBenAmi______MonitoringSystem.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/richnou/vui2" > /data/ucov/repro/jsoup/ClientInfos/richnou______vui2.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/dmitriy-utkin/searchengine" > /data/ucov/repro/jsoup/ClientInfos/dmitriy-utkin______searchengine.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/AcceleratorMX/javaCoreTeamProject" > /data/ucov/repro/jsoup/ClientInfos/AcceleratorMX______javaCoreTeamProject.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/dlalfo1/springstudy" > /data/ucov/repro/jsoup/ClientInfos/dlalfo1______springstudy.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Ale1x/rss-scraper" > /data/ucov/repro/jsoup/ClientInfos/Ale1x______rss-scraper.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Vidula16/PMS" > /data/ucov/repro/jsoup/ClientInfos/Vidula16______PMS.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/youbenwu/abs-cloud" > /data/ucov/repro/jsoup/ClientInfos/youbenwu______abs-cloud.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/aaejo/institution-finder" > /data/ucov/repro/jsoup/ClientInfos/aaejo______institution-finder.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/suryaoff/WGT" > /data/ucov/repro/jsoup/ClientInfos/suryaoff______WGT.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ytlou/Rurate" > /data/ucov/repro/jsoup/ClientInfos/ytlou______Rurate.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/YaroslavBrek/api-tests" > /data/ucov/repro/jsoup/ClientInfos/YaroslavBrek______api-tests.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/paulguckian/WebGoat-DevOps" > /data/ucov/repro/jsoup/ClientInfos/paulguckian______WebGoat-DevOps.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/intrapus/WebGoat" > /data/ucov/repro/jsoup/ClientInfos/intrapus______WebGoat.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/asmaaadel0/Search_Engine" > /data/ucov/repro/jsoup/ClientInfos/asmaaadel0______Search_Engine.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Longren2458/AvitoParser" > /data/ucov/repro/jsoup/ClientInfos/Longren2458______AvitoParser.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Zuko44/job4j_threads" > /data/ucov/repro/jsoup/ClientInfos/Zuko44______job4j_threads.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Sidhanta3366/sid_Project" > /data/ucov/repro/jsoup/ClientInfos/Sidhanta3366______sid_Project.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Acareld/JDAMusicBot" > /data/ucov/repro/jsoup/ClientInfos/Acareld______JDAMusicBot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/1021862752/CommunityAppletBackend" > /data/ucov/repro/jsoup/ClientInfos/1021862752______CommunityAppletBackend.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ghas-results/htl-tck" > /data/ucov/repro/jsoup/ClientInfos/ghas-results______htl-tck.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Yura09/tour-booking" > /data/ucov/repro/jsoup/ClientInfos/Yura09______tour-booking.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Arrowplaz/BetterPokedex" > /data/ucov/repro/jsoup/ClientInfos/Arrowplaz______BetterPokedex.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/GeekMasher/WebGoat" > /data/ucov/repro/jsoup/ClientInfos/GeekMasher______WebGoat.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/cyPark95/My-Study" > /data/ucov/repro/jsoup/ClientInfos/cyPark95______My-Study.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/serhioms/Zoo" > /data/ucov/repro/jsoup/ClientInfos/serhioms______Zoo.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/SamTL91/Webgoat-DevOps" > /data/ucov/repro/jsoup/ClientInfos/SamTL91______Webgoat-DevOps.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/zw543190914/cloud" > /data/ucov/repro/jsoup/ClientInfos/zw543190914______cloud.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/christosservosNCIN/WebGoat" > /data/ucov/repro/jsoup/ClientInfos/christosservosNCIN______WebGoat.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/sandeep-negi/web-testing-b2b" > /data/ucov/repro/jsoup/ClientInfos/sandeep-negi______web-testing-b2b.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/wujun728/jun_java_plugin" > /data/ucov/repro/jsoup/ClientInfos/wujun728______jun_java_plugin.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/sukkyun2/cbnu-allimi" > /data/ucov/repro/jsoup/ClientInfos/sukkyun2______cbnu-allimi.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/dayeaha/moviefan" > /data/ucov/repro/jsoup/ClientInfos/dayeaha______moviefan.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Akhil-Samineni/FlightPricesTracker" > /data/ucov/repro/jsoup/ClientInfos/Akhil-Samineni______FlightPricesTracker.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/AbdulkareemAliu/SudokuSuggest" > /data/ucov/repro/jsoup/ClientInfos/AbdulkareemAliu______SudokuSuggest.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/jensdietrich/xshady" > /data/ucov/repro/jsoup/ClientInfos/jensdietrich______xshady.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/zmoony/multi-util" > /data/ucov/repro/jsoup/ClientInfos/zmoony______multi-util.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/yanghuaiGit/hadooplaab" > /data/ucov/repro/jsoup/ClientInfos/yanghuaiGit______hadooplaab.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/tchuno/projeto-tcc" > /data/ucov/repro/jsoup/ClientInfos/tchuno______projeto-tcc.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/alohahawaii1004/NEW_LMS" > /data/ucov/repro/jsoup/ClientInfos/alohahawaii1004______NEW_LMS.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/ck7526296/tiktok-api" > /data/ucov/repro/jsoup/ClientInfos/ck7526296______tiktok-api.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/TeamLeadder/WebGoat-DevOps" > /data/ucov/repro/jsoup/ClientInfos/TeamLeadder______WebGoat-DevOps.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/LapTopLT/taogeSearch" > /data/ucov/repro/jsoup/ClientInfos/LapTopLT______taogeSearch.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/jini67/web" > /data/ucov/repro/jsoup/ClientInfos/jini67______web.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/wittyphantom333/SkarsisOSRS" > /data/ucov/repro/jsoup/ClientInfos/wittyphantom333______SkarsisOSRS.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/UrosKastel/WebGoat" > /data/ucov/repro/jsoup/ClientInfos/UrosKastel______WebGoat.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/shergazievdanred/test-api-parser" > /data/ucov/repro/jsoup/ClientInfos/shergazievdanred______test-api-parser.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Sumy-Coding/atlas-rest-client-groovy" > /data/ucov/repro/jsoup/ClientInfos/Sumy-Coding______atlas-rest-client-groovy.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/Fresh-Coding/student-app" > /data/ucov/repro/jsoup/ClientInfos/Fresh-Coding______student-app.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/HeChuangJun/springcloud-demo" > /data/ucov/repro/jsoup/ClientInfos/HeChuangJun______springcloud-demo.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/KINGxhao/Online-Test-System.github.io" > /data/ucov/repro/jsoup/ClientInfos/KINGxhao______Online-Test-System.github.io.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/EvgeniyGal/TelegramBot" > /data/ucov/repro/jsoup/ClientInfos/EvgeniyGal______TelegramBot.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/smeligrana/amazon-buybox" > /data/ucov/repro/jsoup/ClientInfos/smeligrana______amazon-buybox.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/llyyzzs/cloud-bcyy" > /data/ucov/repro/jsoup/ClientInfos/llyyzzs______cloud-bcyy.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/libo-create/sephora-aisa-china" > /data/ucov/repro/jsoup/ClientInfos/libo-create______sephora-aisa-china.txt
./fetchRepoInfo.sh "/data/ucov/repro/jsoup/Clients/aviyan7/networkProgramming" > /data/ucov/repro/jsoup/ClientInfos/aviyan7______networkProgramming.txt
